### ISSUE TITLE
Bench migrate-to-v5 exception

### ISSUE THREAD

**Issue by sinaisix** [frappe/bench#100]
Running bench migrate-to-v5 fails with following exception
Executing frappe.patches.v5_0.update_shared in site1.local (site1.local)
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.9.2', 'console_scripts', 'frappe')()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 39, in main
    ret = run(fn, args)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
    out = globals().get(fn)(**args)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 442, in latest
    frappe.modules.patch_handler.run_all()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/patches/v5_0/update_shared.py", line 13, in execute
    frappe.share.add("User", user.name, user.name, write=1)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/share.py", line 37, in add
    doc.save(ignore_permissions=True)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in save
    self.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 165, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 495, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 461, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 572, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 555, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/docshare/docshare.py", line 16, in validate
    self.get_doc().run_method("validate_share", self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 461, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 572, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 555, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 95, in validate_share
    frappe.throw(_("Sorry! User should have complete access to their own record."))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 234, in throw
    msgprint(msg, raise_exception=exc)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 227, in msgprint
    _raise_exception()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 211, in _raise_exception
    raise raise_exception, msg
frappe.exceptions.ValidationError: Sorry! User should have complete access to their own record.
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/ubuntu/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/bench-repo/bench/cli.py", line 172, in update
    patch_sites()
  File "/home/ubuntu/bench-repo/bench/utils.py", line 93, in patch_sites
    exec_cmd("{frappe} --latest all".format(frappe=get_frappe(bench=bench)), cwd=os.path.join(bench, 'sites'))
  File "/home/ubuntu/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ubuntu/frappe-bench/env/bin/frappe --latest all' returned non-zero exit status 1
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/ubuntu/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/bench-repo/bench/cli.py", line 210, in _migrate_to_v5
    migrate_to_v5(bench=bench)
  File "/home/ubuntu/bench-repo/bench/migrate_to_v5.py", line 16, in migrate_to_v5
    exec_cmd("{bench} update".format(bench=sys.argv[0]))
  File "/home/ubuntu/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/bench update' returned non-zero exit status 1

**Comment by pdvyas** [comment]
sorry to keep bouncing you, please post to frappe/erpnext

**Comment by sinaisix** [comment]
OK That's fine
