### ISSUE TITLE
'./apps.txt' Not Found

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#1015]
With every bench command I get this error. Not sure how to reproduce, as I didn't set up this server.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 13, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 24, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path='.')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 891, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1028, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1053, in read_file
    raise IOError("{} Not Found".format(path))
OSError: b'./apps.txt' Not Found
```

## Versions

Bench 4.1.0
Debian 10

**Comment by gavindsouza** [comment]
My guess is the `bench init` process did not complete successfully. Create a `apps.txt` file under the `sites` folder and populate it with the frappe apps installed on your bench
