### ISSUE TITLE
The 'bench' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#1031]
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
> pip3 install --user frappe-bench
> bench
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bench' distribution was not found and is required by the application
```

**Comment by gavindsouza** [comment]
Did you uninstall the previously installed bench from your system? `/usr/local/bin/bench` seems to be pointing to bench installed on `PY2.7`. 

To resolve your issue, you should get rid of the package installed on PY2 completely; reinstalling (pip3 install frappe-bench) may be needed depending on where your wrapper script exists.
 
To uninstall old package:
1. `pip2 uninstall bench`
2. removing the `.egg-link` file manually from PY2's site-packages 
3. delete the `/usr/local/bin/bench` manually (check the contents, it might explicitly be pointing to PY2) 

if your pip is up to date, steps 2 and 3 will be already taken care by it. Else, you'll have to do it manually.
