### ISSUE TITLE
Syntax error while installing frappe

### ISSUE THREAD

**Issue by shashirepo** [frappe/bench#106]
This is what I see - 

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hackers/bench-repo/bench/cli.py", line 48
    print click.Context(bench).get_help()

I guess this is happening due to my python version 3.4, although I tried running the same command with virtualenv running python version 2.7 - But no luck 

any thoughts ?

**Comment by pdvyas** [comment]
yes, try running it with python2, ie. uninstall from your python3 env and install it in a python 2 env. 

```
sudo pip uninstall bench 
sudo pip-2.7 install -e ~/bench-repo #adjust pip-2.7 as per your env
```

**Comment by shashirepo** [comment]
Cool, this is what I am getting now - 

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: honcho

honcho is already installed though, what may be wrong ?

**Comment by pdvyas** [comment]
What command did you run?
Did you init the `frappe-bench` dir?

**Comment by shashirepo** [comment]
Yes, I am running -  bench init frappe-bench

**Comment by pdvyas** [comment]
rm -rf the frappe-bench dir and `bench init` again (with the python2 version)

**Comment by shashirepo** [comment]
1) removed the cloned dir 
2)  git clone https://github.com/frappe/bench bench-repo
3) bench init 
4) same error :(
5) python --version gives 2.7.8 within virtualenv

**Comment by pdvyas** [comment]
It'll be better to solve this on discuss (discuss.frappe.io) or chat (https://gitter.im/frappe/erpnext)

I suspect that virtualenv in frappe-bench dir is on python 3,

From frappe-bench dir, run
```
./env/bin/python --version
```
