### ISSUE TITLE
bench init should exit with status 1 on error during "Installing frappe"

### ISSUE THREAD

**Issue by ceefour** [frappe/bench#1082]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
bench init should exit with status 1 on error during "Installing frappe"

**To Reproduce** :page_with_curl:
1. Ensure pg_config is not installed
2. Run: `bench init /home/frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13-beta --python python3`
3. Installing frappe had errors, but bench init continues, resulting in broken installation and **misleading** message **SUCCESS: Bench /home/frappe/frappe-bench initialized**

```
frappe@ip-172-30-0-218:~$ bench init /home/frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13-beta --python python3
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

get_frappe_commands returned []
$ /usr/local/bin/virtualenv -q env -p python3

Getting frappe
$ git clone https://github.com/frappe/frappe --branch version-13-beta --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2924, done.
remote: Counting objects: 100% (2924/2924), done.
remote: Compressing objects: 100% (2724/2724), done.
remote: Total 2924 (delta 385), reused 1083 (delta 131), pack-reused 0
Receiving objects: 100% (2924/2924), 11.96 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (385/385), done.

Installing frappe
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/frappe 
    ERROR: Command errored out with exit status 1:
     command: /home/frappe/frappe-bench/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ev_pbji1/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ev_pbji1/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uutg3ruj
         cwd: /tmp/pip-install-ev_pbji1/psycopg2-binary/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-uutg3ruj/psycopg2_binary.egg-info
    writing /tmp/pip-pip-egg-info-uutg3ruj/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-uutg3ruj/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-uutg3ruj/psycopg2_binary.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-uutg3ruj/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
[4/4] Building fresh packages...
$ yarn run snyk-protect
yarn run v1.22.10
$ snyk protect
Successfully applied Snyk patches

Done in 8.75s.
Done in 158.55s.
Updating node packages...

Installing node dependencies for frappe
$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.10
$ snyk protect
Successfully applied Snyk patches

Done in 3.69s.
Done in 4.58s.
$ bench build
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

/home/frappe/frappe-bench/env/bin/python: Error while finding module specification for 'frappe.utils.bench_helper' (ModuleNotFoundError: No module named 'frappe')

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 33, in <module>
    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())
  File "/home/frappe/.bench/bench/cli.py", line 48, in cli
    if sys.argv[1] in (get_frappe_commands() + ["--site", "--verbose", "--force", "--profile"]):
  File "/home/frappe/.bench/bench/cli.py", line 138, in get_frappe_commands
    print('get_frappe_commands from generate_command_cache()', generate_command_cache())
  File "/home/frappe/.bench/bench/utils.py", line 1067, in generate_command_cache
    raise e
  File "/home/frappe/.bench/bench/utils.py", line 1058, in generate_command_cache
    output = get_cmd_output(command, cwd=sites_path)
  File "/home/frappe/.bench/bench/utils.py", line 517, in get_cmd_output
    output = subprocess.check_output(cmd, cwd=cwd, shell=True, stderr=subprocess.PIPE).strip()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper get-frappe-commands' returned non-zero exit status 1.
SUCCESS: Bench /home/frappe/frappe-bench initialized
```

**Expected behavior** :chart_with_upwards_trend:
bench init should exit with status 1 on error during "Installing frappe"

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [x] Linux: `ubuntu:20.04:arm64`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: `develop`
- Frappe Version: `version-13-beta`
- ERPNext Version: not applicable

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:

Detect if command failed, then exit with status 1.

In `bench/app.py` `install_app()` -> `bench.utils.exec_cmd()`

**Comment by gavindsouza** [comment]
Seems like I've managed to fix this - can't pinpoint exactly in which release (but feels like this has been fixed a while).

```python
 % bench init /tmp/temp-bench --python $(which python3.7)
Setting Up Environment
$ /home/frappe/.nix-profile/bin/python3.7 -m venv env
$ /tmp/temp-bench/env/bin/python -m pip install --quiet --upgrade pip
Getting frappe
$ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3133, done.
remote: Counting objects: 100% (3133/3133), done.
remote: Compressing objects: 100% (2778/2778), done.
remote: Total 3133 (delta 441), reused 1504 (delta 256), pack-reused 0
Receiving objects: 100% (3133/3133), 15.94 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (441/441), done.
Installing frappe
$ /tmp/temp-bench/env/bin/python -m pip install --quiet --upgrade -e /tmp/temp-bench/apps/frappe 
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/tmp/temp-bench/env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/tmp/temp-bench/env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/temp-bench/env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-vy6ly3pa/overlay/lib/python3.7/site-packages/flit_core/buildapi.py", line 32, in get_requires_for_build_wheel
          docstring, version = get_docstring_and_version_via_ast(module)
        File "/tmp/pip-build-env-vy6ly3pa/overlay/lib/python3.7/site-packages/flit_core/common.py", line 132, in get_docstring_and_version_via_ast
          node = ast.parse(f.read())
        File "/nix/store/4y7nxvxd01gmbs9a42kmwcn7ij9550l2-python3-3.7.13/lib/python3.7/ast.py", line 35, in parse
          return compile(source, filename, mode, PyCF_ONLY_AST)
        File "<unknown>", line 1080
          if key := can_cache_doc(args):
                  ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/home/frappe/bench/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/bench/bench/utils/system.py", line 79, in init
    get_app(
  File "/home/frappe/bench/bench/app.py", line 432, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/bench/bench/app.py", line 230, in install
    install_app(
  File "/home/frappe/bench/bench/app.py", line 561, in install_app
    bench.run(
  File "/home/frappe/bench/bench/bench.py", line 47, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/frappe/bench/bench/utils/__init__.py", line 155, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating /tmp/temp-bench
Do you want to rollback these changes? [y/N]: 
```

Closing this.
