### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Nonetype' and 'list' 

### ISSUE THREAD

**Issue by El-profesor-0** [frappe/bench#1100]
I am facing this issue while using 'bench init frappe-bench'.
I have downloaded it using 'pip3 install frappe-bench'
I found this issue closed but no solution has seemed to work.

/usr/local/Cellar/python/3.7.6_1/bin/python3.7: Error while finding module specification for 'frappe.utils.bench_helper' (ModuleNotFoundError: No module named 'frappe')

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('frappe-bench', 'console_scripts', 'bench')()
  File "/Users/narendra/Development/bench-repo/bench/cli.py", line 48, in cli
    if sys.argv[1] in get_frappe_commands() + ["--site", "--verbose", "--force", "--profile"]:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by saru2020** [comment]
I have been trying this for quite some time now and still see the same issue. Is there really a solution to this issue?

**Comment by gavindsouza** [comment]
This error seems to come up when frappe hasn't been installed properly in your bench's `env`.
