### ISSUE TITLE
NameError: name 'utils' is not defined

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#1104]
Switch from `version-12` to `version-13-beta`:

```
> bench switch-to-branch --upgrade version-13-beta frappe erpnext
...
$ snyk protect
Successfully applied Snyk patches

Done in 2.20s.
Done in 7.49s.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/alyf/.bench/bench/cli.py", line 41, in cli
    bench_command()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/alyf/.bench/bench/commands/update.py", line 43, in switch_to_branch
    switch_to_branch(branch=branch, apps=list(apps), upgrade=upgrade)
  File "/home/alyf/.bench/bench/app.py", line 417, in switch_to_branch
    switch_branch(branch, apps=apps, bench_path=bench_path, upgrade=upgrade)
  File "/home/alyf/.bench/bench/app.py", line 409, in switch_branch
    reload_module(utils)
NameError: name 'utils' is not defined
```

**Comment by gavindsouza** [comment]
Fixed via https://github.com/frappe/bench/pull/983

**Comment by ekquashie** [comment]
How did you solve this error
