### ISSUE TITLE
No module named bench.cli

### ISSUE THREAD

**Issue by MaxMorais** [frappe/bench#112]
I'm getting the error below when put `bench` on console, but when I open the `python` and import `bench` its work fine

```python
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named bench.cli```

**Comment by MaxMorais** [comment]
After a complete reinstall
```python
frappe app is not installed. Run the following command to install frappe
bench get-app frappe https://github.com/frappe/frappe.git
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/usr/frappe5/bench-repo/bench/cli.py", line 42, in cli
    return old_frappe_cli()
  File "/usr/frappe5/bench-repo/bench/cli.py", line 91, in old_frappe_cli
    os.execv(f, [f] + sys.argv[2:])
OSError: [Errno 2] No such file or directory
```

**Comment by pdvyas** [comment]
As per gitter chat `sudo pip install --upgrade pip` fixed this issue.
