### ISSUE TITLE
Error while initiating a new frappe bench on centos6.6

### ISSUE THREAD

**Issue by gemchand** [frappe/bench#114]
erpelumba@erp.elumba.com [~]#  bench init frappe-bench
Traceback (most recent call last):
  File "/usr/bin/bench", line 8, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/erpelumba/bench-repo/bench/cli.py", line 55, in cli
    bench()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/erpelumba/bench-repo/bench/cli.py", line 158, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch)
  File "/home/erpelumba/bench-repo/bench/utils.py", line 40, in init
    print 'Directory {} already exists!'.format(path)
ValueError: zero length field name in format

How to fix this problem?
Thank you

**Comment by pdvyas** [comment]
Remove /etc/frappe_bench_dir

**Comment by gemchand** [comment]
there is no /etc/frappe_bench_dir

**Comment by pdvyas** [comment]
Does frappe-bench dir already exist?
