### ISSUE TITLE
bash setup_frappe.sh --setup-production failling 

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/bench#115]
After the merge of v5 into master today bash setup_frappe.sh --setup-production is failling :(

CentOS 7
http://pastebin.com/LRjMdyvh

Ubuntu 14.04 1 GB RAM
http://pastebin.com/JjG6PfWu

CentOS 6.5
http://pastebin.com/M9hqWz43

Debian 7 1GB RAM
http://pastebin.com/9XufTDJp

Looks like 1GB of RAM is the minimal for install ERPNext.

**Comment by pdvyas** [comment]
Setup swap

**Comment by williamjmorenor** [comment]
Even with 2GB of RAM install faill with:

frappe app is not installed. Run the following command to install frappe
bench get-app frappe https://github.com/frappe/frappe.git

Full log:

bash setup_frappe.sh --setup-production
Installing for centos 7 amd64
In case you encounter an error, you can post on https://discuss.frappe.io

Adding centos mariadb repo
Installing packages for centos. This might take time...
Installing wkhtmltopdf
Configuring CentOS services
Starting services
Adding frappe user
Installing frappe-bench
Setting up first site
frappe app is not installed. Run the following command to install frappe
bench get-app frappe https://github.com/frappe/frappe.git
Traceback (most recent call last):
  File "/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 42, in cli
    return old_frappe_cli()
  File "/home/frappe/bench-repo/bench/cli.py", line 94, in old_frappe_cli
    os.execv(f, [f] + sys.argv[2:])
OSError: [Errno 2] No such file or directory
[root@erpnext5 ~]# free
             total       used       free     shared    buffers     cached
Mem:       2050060    1951396      98664       8452      76456    1511600
-/+ buffers/cache:     363340    1686720
Swap:            0          0          0
[root@erpnext5 ~]#

**Comment by williamjmorenor** [comment]
:(

  Exception:
  Traceback (most recent call last):
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
      requirement_set.prepare_files(finder)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_set.py", line 345, in prepare_files
      functools.partial(self._prepare_file, finder))
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_set.py", line 290, in _walk_req_to_install
      more_reqs = handler(req_to_install)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_set.py", line 487, in _prepare_file
      download_dir, do_download, session=self.session,
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/download.py", line 827, in unpack_url
      session,
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
      from_path, content_type = _download_http_url(link, session, temp_dir)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/download.py", line 888, in _download_http_url
      _download_url(resp, link, content_file)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
      for chunk in progress_indicator(resp_read(4096), 4096):
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
      decode_content=False):
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 273, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 203, in read
      data = self._fp.read(amt)
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
      self.__callback(self.__buf.getvalue())
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
      self.serializer.dumps(request, response, body=body),
    File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
      ).encode("utf8"),
  MemoryError

installing frappe
Error: None
Traceback (most recent call last):
  File "/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 56, in cli
    bench()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 161, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch)
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in init
    get_app('frappe', frappe_path, branch=frappe_branch, bench=path, build_asset_files=False)
  File "/home/frappe/bench-repo/bench/app.py", line 54, in get_app
    install_app(app, bench=bench)
  File "/home/frappe/bench-repo/bench/app.py", line 78, in install_app
    find_links=find_links))
  File "/home/frappe/bench-repo/bench/utils.py", line 76, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe' returned non-zero exit status 2

**Comment by pdvyas** [comment]
Memory error. Make swap

**Comment by williamjmorenor** [comment]
2GB of RAM and 4GB of Swap and everthing if working good, thans a lot @pdvyas
