### ISSUE TITLE
Easy Install - Fail

### ISSUE THREAD

**Issue by clockwiseq** [frappe/bench#1187]
Issue: Easy Install

CentOS 8 new server, ran through the "simple steps" and downloaded the .py file from the githubusercontent.com path and ran the command `python3 install.py --production` and got the following error:

`Logs are saved under /tmp/logs/easy-install__2021-07-01__04-55.log
Error: Unable to find a match: python-setuptools python-devel
Traceback (most recent call last):
  File "install.py", line 495, in <module>
    install_prerequisites()
  File "install.py", line 158, in install_prerequisites
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 143, in run_os_command
    returncode = subprocess.check_call(command, shell=True, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel' returned non-zero exit status 1.`

I'm not linux expert, but when I tried to `yum install python-setuptools` it returns an error that the package cannot be found, but `python3-setuptools` is already installed.  So, what do I need to do to get this thing going?

**Comment by Osfuco** [comment]
> It failed for me on three instances on AWS, Centos 7, Ubuntu 16.04 and Debian 10.

Were you able to install it on Centos7?
