### ISSUE TITLE
Exception found while running 'bench init frappe-bench'

### ISSUE THREAD

**Issue by izaakdo** [frappe/bench#120]
Do anyone has a solution for this exception? Tring to install frappe with 'bench init frappe-brench'.

```
installing frappe
/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 291, in run
    wb.build(autobuilding=True)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 317, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 304, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 469, in _prepare_file
    session=self.session)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError

Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/erp/bench-repo/bench/cli.py", line 56, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/erp/bench-repo/bench/cli.py", line 161, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch)
  File "/home/erp/bench-repo/bench/utils.py", line 64, in init
    get_app('frappe', frappe_path, branch=frappe_branch, bench=path, build_asset_files=False)
  File "/home/erp/bench-repo/bench/app.py", line 54, in get_app
    install_app(app, bench=bench)
  File "/home/erp/bench-repo/bench/app.py", line 78, in install_app
    find_links=find_links))
  File "/home/erp/bench-repo/bench/utils.py", line 79, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe' returned non-zero exit status 2
```

**Comment by dud3** [comment]
Same here.

**Comment by dud3** [comment]
cc @pdvyas

**Comment by anandpdoshi** [comment]
This might solve the issue: https://discuss.erpnext.com/t/installing-erpnext-5-in-a-low-memory-vps/6008

**Comment by izaakdo** [comment]
Thanks @anandpdoshi !

**Comment by dud3** [comment]
Solved.
