### ISSUE TITLE
Can't unistall app

### ISSUE THREAD

**Issue by zongo811** [frappe/bench#1217]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

**Do the checklist before filing an issue:**
 - [X] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
I uninstalled an app and then did "bench version". This produced an exception:
``` 
frappe@erpnextmy:~/frappe-bench/apps$ bench version
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 762, in get_version
    frappe.init("")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 212, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1148, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1016, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 974, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test_2'
frappe@erpnextthkr:~/frappe-bench/apps$ mv test_2_bak test_2
``` 

**To Reproduce** :page_with_curl:
1. bench new-app test_2
2. bench install-app test_2
3. Check in Frappe if new app is available, e.g. by creating a Module Def.
4. bench uninstall-app test_2
5. bench remove-from-installed-apps test_2
6. Do "bench app-list" to check if app is still present
7. Remove directory apps/test_2
8. bench version
9. See error.

**Expected behavior** :chart_with_upwards_trend:
Directory containing the uninstalled app can be removed and "bench version" does not throw an exception.

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [X] Linux: `debian:buster`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.6.0
- Frappe Version: 13.14.1
- ERPNext Version: 13.14.1

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by zongo811** [comment]
Overlooked the remove -app command, everything is fine.
