### ISSUE TITLE
Easy Install Restart the bench issue

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/bench#1232]
Issue: Easy Install

OS:-Ubuntu 20.04

TASK [bench : Restart the bench] ***********************************************
task path: /tmp/.bench/bench/playbooks/roles/bench/tasks/setup_bench_production.yml:24
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp `"&& mkdir /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419 && echo ansible-tmp-1638965670.819283-93202-229818035404419="` echo /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-89675z2diq2sx/tmpd_ez9xvl TO /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:frappe:r-x /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419/ /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u frappe /bin/sh -c '"'"'echo BECOME-SUCCESS-yqzxamrkvboykaorqnkhgxkcsjbhktev ; /usr/bin/python3 /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419/AnsiballZ_command.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1638965670.819283-93202-229818035404419/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "restart"
    ],
    "delta": "0:00:10.232825",
    "end": "2021-12-08 04:14:41.311687",
    "invocation": {
        "module_args": {
            "_raw_params": "bench restart",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/home/frappe/frappe-bench",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-12-08 04:14:31.078862",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/bench\", line 33, in <module>\n    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())\n  File \"/home/frappe/.bench/bench/cli.py\", line 117, in cli\n    raise e\n  File \"/home/frappe/.bench/bench/cli.py\", line 107, in cli\n    bench_command()\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/.bench/bench/commands/utils.py\", line 31, in restart\n    restart_supervisor_processes(bench_path='.', web_workers=web)\n  File \"/home/frappe/.bench/bench/utils/bench.py\", line 267, in restart_supervisor_processes\n    bench.run(f\"supervisorctl restart {group}\")\n  File \"/home/frappe/.bench/bench/bench.py\", line 43, in run\n    return exec_cmd(cmd, cwd=cwd or self.cwd)\n  File \"/home/frappe/.bench/bench/utils/__init__.py\", line 126, in exec_cmd\n    raise CommandFailedError\nbench.exceptions.CommandFailedError",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/local/bin/bench\", line 33, in <module>",
        "    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())",
        "  File \"/home/frappe/.bench/bench/cli.py\", line 117, in cli",
        "    raise e",
        "  File \"/home/frappe/.bench/bench/cli.py\", line 107, in cli",
        "    bench_command()",
        "  File \"/usr/lib/python3/dist-packages/click/core.py\", line 764, in __call__",
        "    return self.main(*args, **kwargs)",
        "  File \"/usr/lib/python3/dist-packages/click/core.py\", line 717, in main",
        "    rv = self.invoke(ctx)",
        "  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1137, in invoke",
        "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
        "  File \"/usr/lib/python3/dist-packages/click/core.py\", line 956, in invoke",
        "    return ctx.invoke(self.callback, **ctx.params)",
        "  File \"/usr/lib/python3/dist-packages/click/core.py\", line 555, in invoke",
        "    return callback(*args, **kwargs)",
        "  File \"/home/frappe/.bench/bench/commands/utils.py\", line 31, in restart",
        "    restart_supervisor_processes(bench_path='.', web_workers=web)",
        "  File \"/home/frappe/.bench/bench/utils/bench.py\", line 267, in restart_supervisor_processes",
        "    bench.run(f\"supervisorctl restart {group}\")",
        "  File \"/home/frappe/.bench/bench/bench.py\", line 43, in run",
        "    return exec_cmd(cmd, cwd=cwd or self.cwd)",
        "  File \"/home/frappe/.bench/bench/utils/__init__.py\", line 126, in exec_cmd",
        "    raise CommandFailedError",
        "bench.exceptions.CommandFailedError"
    ],
    "stdout": "WARN: bench is installed in editable mode!\n\nThis is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`\n\n$ supervisorctl restart frappe-bench-workers: frappe-bench-web:\nfrappe-bench-workers:frappe-bench-frappe-schedule: stopped\nfrappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped\nfrappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped\nfrappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped\nfrappe-bench-web:frappe-bench-node-socketio: stopped\nfrappe-bench-web:frappe-bench-frappe-web: stopped\nfrappe-bench-workers:frappe-bench-frappe-schedule: started\nfrappe-bench-workers:frappe-bench-frappe-default-worker-0: started\nfrappe-bench-workers:frappe-bench-frappe-short-worker-0: started\nfrappe-bench-workers:frappe-bench-frappe-long-worker-0: started\nfrappe-bench-web:frappe-bench-node-socketio: ERROR (spawn error)\nfrappe-bench-web:frappe-bench-frappe-web: started\nERROR: ",
    "stdout_lines": [
        "WARN: bench is installed in editable mode!",
        "",
        "This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`",
        "",
        "$ supervisorctl restart frappe-bench-workers: frappe-bench-web:",
        "frappe-bench-workers:frappe-bench-frappe-schedule: stopped",
        "frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped",
        "frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped",
        "frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped",
        "frappe-bench-web:frappe-bench-node-socketio: stopped",
        "frappe-bench-web:frappe-bench-frappe-web: stopped",
        "frappe-bench-workers:frappe-bench-frappe-schedule: started",
        "frappe-bench-workers:frappe-bench-frappe-default-worker-0: started",
        "frappe-bench-workers:frappe-bench-frappe-short-worker-0: started",
        "frappe-bench-workers:frappe-bench-frappe-long-worker-0: started",
        "frappe-bench-web:frappe-bench-node-socketio: ERROR (spawn error)",
        "frappe-bench-web:frappe-bench-frappe-web: started",
        "ERROR: "
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=79   changed=18   unreachable=0    failed=1    skipped=66   rescued=0    ignored=0   

Traceback (most recent call last):
  File "install.py", line 500, in <module>
    install_bench(args)
  File "install.py", line 281, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 416, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.

**Comment by mohsinalimat** [comment]
issue solve with https://discuss.erpnext.com/t/error-while-start-erpnext/22135/8

```
sudo supervisorctl stop all
sudo service nginx stop
sudo bench setup requirements
sudo bench setup socketio
sudo bench setup config
sudo bench setup redis
sudo bench setup supervisor
sudo bench setup procfile
bench start
```
