### ISSUE TITLE
Easy Install is show an error at the end of command

### ISSUE THREAD

**Issue by thecoder066** [frappe/bench#1244]
Issue: Easy Install

**Command I run** 
steps that I used :
1- sudo -i
2- sudo apt update && sudo apt upgrade --yes
3- sudo adduser frappe
4- sudo usermod -aG sudo frappe
5- su - frappe
6- export LC_ALL=C.UTF-8
7- wget https://raw.githubusercontent.com/frappe/bench/develop/install.py
8- sudo python3 install.py --verbose --production --frappe-branch version-13 --erpnext-branch version-13 --user frappe

-------------
**All command run very well, but the number 8 finally show this error :** 

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "init",
        "/home/frappe/frappe-bench",
        "--frappe-path",
        "https://github.com/frappe/frappe",
        "--frappe-branch",
        "version-13",
        "--python",
        "python3"
    ],
    "delta": "0:00:00.287644",
    "end": "2021-12-28 09:20:43.892713",
    "invocation": {
        "module_args": {
            "_raw_params": "bench init /home/frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13 --python python3",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/home/frappe/frappe-bench",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-12-28 09:20:43.605069",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/bench\", line 33, in <module>\n    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'b
[easy-install__2021-12-27__10-44.log](https://github.com/frappe/bench/files/7784067/easy-install__2021-12-27__10-44.log)
[easy-install__2021-12-27__10-44.log](https://github.com/frappe/bench/files/7784068/easy-install__2021-12-27__10-44.log)
ench')())\n  File \"/u
[easy-install__2021-12-27__10-44.log](https://github.com/frappe/bench/files/7784066/easy-install__2021-12-27__10-44.log)
sr/bin/bench\", line 22, in importlib_load_entry_point\n    for entry_point in distribution(dist_name).entry_points\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution\n    return Distribution.from_name(distribution_name)\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name\n    raise PackageNotFoundError(name)\nimportlib.metadata.PackageNotFoundError: frappe-bench",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/bin/bench\", line 33, in <module>",
        "    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())",
        "  File \"/usr/bin/bench\", line 22, in importlib_load_entry_point",
        "    for entry_point in distribution(dist_name).entry_points",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution",
        "    return Distribution.from_name(distribution_name)",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name",
        "    raise PackageNotFoundError(name)",
        "importlib.metadata.PackageNotFoundError: frappe-bench"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=67   changed=18   unreachable=0    failed=1    skipped=63   rescued=0    ignored=0

Traceback (most recent call last):
  File "install.py", line 497, in <module>
    install_bench(args)
  File "install.py", line 278, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 413, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.

**Comment by wolfcreative** [comment]
I have the same problem. 

Clean system.

**Comment by thecoder066** [comment]
> I have the same problem.
> 
> Clean system.

Could you please share commands that you use to fix error ?

**Comment by wolfcreative** [comment]
Do it right here 

https://github.com/frappe/bench/issues/1240#issuecomment-1000982450

**Comment by Oridici** [comment]
problem still exists. any solutions? the above solutions does not work for me

**Comment by smitz96** [comment]
Same issue. Tried installing on Ubuntu Server 20.04 and 18.04.

**Comment by Osfuco** [comment]
were you able to install it on Centos7?

**Comment by smitz96** [comment]
Yeah! I tried but it didn’t workout. Ended up installing it on Ubuntu 18.04LTS. I installed using the link below. You can give it a try on CentOS if you like.
https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-18-04
