### ISSUE TITLE
Unable to install custom app

### ISSUE THREAD

**Issue by CleoMenezesJr** [frappe/bench#1245]
## Context information (for bug reports)
After running:  `bench get-app --branch main myapp git@github.com:path/repo.git`

```
Cloning into 'myapp'...
fatal: unable to access 'https://github.com/git@github.com:path/repo.git/': The requested URL returned error: 400
ERROR: 
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 33, in <module>
    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())
  File "/home/frappe/.bench/bench/cli.py", line 117, in cli
    raise e
  File "/home/frappe/.bench/bench/cli.py", line 107, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/make.py", line 142, in get_app
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 348, in get_app
    app.get()
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 153, in get
    self.bench.run(
  File "/home/frappe/.bench/bench/bench.py", line 43, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
```
**Output of `bench version`**
```
frappe 13.15.0
```

## Steps to reproduce the issue

1. git clone https://github.com/frappe/frappe_docker.git; cd frappe_docker
2. cp -R devcontainer-example .devcontainer; cd .devcontainer
3. docker-compose up -d
4. docker exec -it *frappe/bench container id* bash
5. bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench; cd frappe-bench
6. bench set-mariadb-host mariadb; bench set-redis-cache-host redis-cache:6379; bench set-redis-queue-host redis-queue:6379; bench set-redis-socketio-host redis-socketio:6379
7. bench new-site mysite.localhost --mariadb-root-password 123 --admin-password admin --no-mariadb-socket
8. bench --site mysite.localhost clear-cache;
9. bench get-app --branch main myapp git@github.com:path/repo.git;
10. bench --site mysite.localhost install-app myapp;
11. bench start

## Additional information

Fedora Workstation 35,
Docker version 20.10.11, build dea9396,

**Comment by gavindsouza** [comment]
I've been away for a while so the fixes have been delayed. These and other issues have been fixed in the patch releases made since. The latest version [5.7.4](https://github.com/frappe/bench/releases/tag/v5.7.4) should work just fine.

---

A quick fix would've been to downgrade the Bench package via `pip install -U frappe-bench==5.6.0` or whatever older version you were using. 

For future references, if upgrading the Bench CLI is causing some issues then you can easily downgrade to the version that worked fine for you.
