### ISSUE TITLE
"Unknown color 'bright_black'

### ISSUE THREAD

**Issue by daraul** [frappe/bench#1246]
I encountered a weird error while attempting to `bench init` today. The trace is below. The bench folder still gets created. Should I ignore the error, and use it anyway?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/click/termui.py", line 372, in style
    bits.append('\033[%dm' % (_ansi_colors.index(fg) + 30))
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bench/commands/make.py", line 83, in init
    verbose=verbose,
  File "/usr/local/lib/python3.6/dist-packages/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bench/utils/system.py", line 64, in init
    bench.setup.env(python=python)
  File "/usr/local/lib/python3.6/dist-packages/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bench/bench.py", line 249, in env
    self.run(f"{virtualenv} {quiet_flag} env -p {python}")
  File "/usr/local/lib/python3.6/dist-packages/bench/bench.py", line 43, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/usr/local/lib/python3.6/dist-packages/bench/utils/__init__.py", line 116, in exec_cmd
    click.secho(f"$ {cmd}", fg="bright_black")
  File "/usr/lib/python3/dist-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/lib/python3/dist-packages/click/termui.py", line 374, in style
    raise TypeError('Unknown color %r' % fg)
TypeError: Unknown color 'bright_black'

ERROR: There was a problem while creating bench
Do you want to rollback these changes? [y/N]: 
Aborted!
```

**Comment by daraul** [comment]
I've tried using the folder, and it doesn't work. I don't have bench commands like 'new-site'. It looks like it doesn't get recognized as a bench folder.

**Comment by gavindsouza** [comment]
The env creation failed. You can safely delete this folder. Can you try upgrading Click (`pip install -U Click`) and try again?

**Comment by daraul** [comment]
That did it! Is there some prerequisite that I might have missed?

**Comment by gavindsouza** [comment]
No, we don't pin Click versions for Bench because we were predominately using old APIs and utils which are consistent for all versions + if multiple global libraries use pinned versions of Click, it's a pain to install them for the end user; but we might have to change that now.

bright_black was added in Click v7.0 (ref: https://github.com/pallets/click/blob/7.0/click/termui.py). Will add a pin for this in requirements.txt
