### ISSUE TITLE
InvalidRemoteException during update

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#1267]
### Traceback

<details>
<summary>bench update --reset</summary>

```
remote: Enumerating objects: 1594, done.
remote: Counting objects: 100% (1008/1008), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 164 (delta 143), reused 52 (delta 38), pack-reused 0
Receiving objects: 100% (164/164), 48.90 KiB | 16.30 MiB/s, done.
Resolving deltas: 100% (143/143), completed with 143 local objects.
From https://github.com/frappe/frappe
 * branch                  version-13 -> FETCH_HEAD
 + e263789156...17362d7189 version-13 -> upstream/version-13  (forced update)
Backing up sites...
Backup Summary for my-site at 2022-02-14 17:25:15.254051
Config  : ./my-site/private/backups/20220214_172500-my_site-site_config_backup.json 695.0B
Database: ./my-site/private/backups/20220214_172500-my_site-database.sql.gz         72.5MiB
Backup for Site my-site has been successfully completed
Updating apps source...
$ git fetch --depth=1 --no-tags upstream version-13
Username for 'https://github.com': username
Password for 'https://username@github.com':
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 21 (delta 16), reused 8 (delta 5), pack-reused 0
Unpacking objects: 100% (21/21), 6.97 KiB | 792.00 KiB/s, done.
From https://github.com/MYORG/MYREPO
 * branch            version-13 -> FETCH_HEAD
 + a89c5c4...e9ce19d version-13 -> upstream/version-13  (forced update)
$ git reset --hard upstream/version-13
HEAD is now at e9ce19d feat: add timesheet to project and task
$ git reflog expire --all
$ git gc --prune=all
Enumerating objects: 1079, done.
Counting objects: 100% (1079/1079), done.
Delta compression using up to 4 threads
Compressing objects: 100% (369/369), done.
Writing objects: 100% (1079/1079), done.
Total 1079 (delta 714), reused 1046 (delta 699)
$ find . -name "*.pyc" -delete
$ git fetch --depth=1 --no-tags upstream version-13
remote: Enumerating objects: 1934, done.
remote: Counting objects: 100% (1448/1448), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 209 (delta 181), reused 97 (delta 86), pack-reused 0
Receiving objects: 100% (209/209), 111.52 KiB | 1.57 MiB/s, done.
Resolving deltas: 100% (181/181), completed with 175 local objects.
From https://github.com/frappe/erpnext
 * branch                  version-13 -> FETCH_HEAD
 + 5c8fc3890f...540559d6fd version-13 -> upstream/version-13  (forced update)
$ git reset --hard upstream/version-13
HEAD is now at 540559d6fd Merge branch 'version-13-pre-release' into version-13
$ git reflog expire --all
$ git gc --prune=all
Enumerating objects: 388415, done.
Counting objects: 100% (388415/388415), done.
Delta compression using up to 4 threads
Compressing objects: 100% (82062/82062), done.
Writing objects: 100% (388415/388415), done.
Total 388415 (delta 303102), reused 388402 (delta 303089)
Checking connectivity: 388415, done.
$ find . -name "*.pyc" -delete
$ git fetch --depth=1 --no-tags upstream version-13
Username for 'https://github.com': username
Password for 'https://username@github.com':
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 1.15 KiB | 1.15 MiB/s, done.
From https://github.com/alyf-de/erpnext_datev-uo
 * branch            version-13 -> FETCH_HEAD
 + 19e4117...72fc64a version-13 -> upstream/version-13  (forced update)
$ git reset --hard upstream/version-13
HEAD is now at 72fc64a docs: setup, disclaimer
$ git reflog expire --all
$ git gc --prune=all
Enumerating objects: 32, done.
Counting objects: 100% (32/32), done.
Delta compression using up to 4 threads
Compressing objects: 100% (26/26), done.
Writing objects: 100% (32/32), done.
Total 32 (delta 3), reused 27 (delta 1)
$ find . -name "*.pyc" -delete
$ git fetch --depth=1 --no-tags upstream version-13
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/frappe/frappe
 * branch                  version-13 -> FETCH_HEAD
$ git reset --hard upstream/version-13
HEAD is now at 17362d7189 Merge branch 'version-13-pre-release' into version-13
$ git reflog expire --all
$ git gc --prune=all
Enumerating objects: 287356, done.
Counting objects: 100% (287356/287356), done.
Delta compression using up to 4 threads
Compressing objects: 100% (64085/64085), done.
Writing objects: 100% (287356/287356), done.
Total 287356 (delta 221868), reused 287351 (delta 221863)
$ find . -name "*.pyc" -delete
Setting up requirements...
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
Installing 4 applications...
Installing frappe
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/frappe 
$ yarn install
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.17", while you're on "1.22.11".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
$ yarn run snyk-protect
yarn run v1.22.11
$ snyk protect
Successfully applied Snyk patches

Done in 8.70s.  
Done in 16.44s. 
$ bench build --app frappe
Linking /home/frappe/frappe-bench/apps/frappe/node_modules to ./assets/frappe/noLinking /home/frappe/frappe-bench/apps/myrepo/myrepo/public to ./assets/myapp
Linking /home/frappe/frappe-bench/apps/erpnext/erpnext/public to ./assets/erpnexLinking /home/frappe/frappe-bench/apps/erpnext/node_modules to ./assets/erpnext/✔ Application Assets Linked

yarn run v1.22.11
$ FRAPPE_ENV=production node rollup/build.js --app frappe
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js

Building frappe assets...

✔ Built js/checkout.min.js
✔ Built js/dialog.min.js
✔ Built js/user_profile_controller.min.js
✔ Built js/web_form.min.js
✔ Built js/list.min.js
✔ Built js/barcode_scanner.min.js
✔ Built js/bootstrap-4-web.min.js
✔ Built js/frappe-recorder.min.js
✔ Built js/frappe-web.min.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
✔ Built css/report.min.css
✔ Built css-rtl/report.min.css
✔ Built js/data_import_tools.min.js
✔ Built css/web_form.css
✔ Built css-rtl/web_form.css
✔ Built js/report.min.js
✔ Built js/control.min.js
✔ Built css/printview.css
✔ Built css/email.css
✔ Built css/login.css
✔ Built css/frappe-web-b4.css
✔ Built css/desk.min.css
✔ Built js/desk.min.js
✔ Built css-rtl/printview.css
✔ Built css-rtl/email.css
✔ Built css-rtl/login.css
✔ Built css-rtl/frappe-web-b4.css
✔ Built css-rtl/desk.min.css
✔ Built js/form.min.js
✨  Done in 57.833s
Done in 60.23s. 
$ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
ERROR:
Traceback (most recent call last):
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/__init__.py", line 416, in fetch_details_from_tag
    org, repo = org_repo
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/cli.py", line 121, in cli
    raise e
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/cli.py", line 111, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/commands/update.py", line 23, in update
    update(pull=pull, apps=apps, patch=patch, build=build, requirements=requirements, restart_supervisor=restart_supervisor, restart_systemd=restart_systemd, backup=not no_backup, compile=not no_compile, force=force, reset=reset)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/bench.py", line 394, in update
    bench.setup.requirements()
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/bench.py", line 341, in requirements
    App(app, bench=self.bench, to_clone=False).install()
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 184, in install
    setup_app_dependencies(
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 278, in setup_app_dependencies
    get_app(
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 308, in get_app
    app = App(git_url, branch=branch, bench=bench)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 148, in __init__
    super().__init__(name, branch, *args, **kwargs)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 65, in __init__
    self.setup_details()
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 91, in setup_details
    self._setup_details_from_name_tag()
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/app.py", line 97, in _setup_details_from_name_tag
    self.org, self.repo, self.tag = fetch_details_from_tag(self.name)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/__init__.py", line 418, in fetch_details_from_tag
    org, repo = find_org(org_repo)
  File "/home/frappe/.local/lib/python3.8/site-packages/bench/utils/__init__.py", line 400, in find_org
    raise InvalidRemoteException
bench.exceptions.InvalidRemoteException
```

</details>

Other ways to reproduce this error

```bash
bench setup requirements # produces above error
bench setup requirements --python # everything fine
bench setup requirements --node # everything fine
```

Looking at the code, this error should happen if any app is installed that doesn't belong to the GitHub organizations "frappe" or "erpnext".

### Versions
```
> bench version -f table 
+------------------+---------+------------+---------+
| App              | Version | Branch     | Commit  |
+------------------+---------+------------+---------+
| myapp            | 0.0.1   | version-13 | e9ce19d |
| erpnext          | 13.20.1 | version-13 | 540559d |
| frappe           | 13.20.1 | version-13 | 17362d7 |
+------------------+---------+------------+---------+

> bench --version
5.7.5
```

frappe-bench 5.7.6 ist affected as well

### Offending code

https://github.com/frappe/bench/blob/46ddb6131301e522a85e7007b34408d8e721dede/bench/utils/__init__.py#L390-L400

### Workaround

Downgrade your bench

```
pip3 install -U frappe-bench~=5.5.0
```

**Comment by barredterra** [comment]
bench 5.7.6 ist affected as well

**Comment by barredterra** [comment]
```bash
bench setup requirements # produces above error
bench setup requirements --python # everything fine
bench setup requirements --node # everything fine
```

**Comment by barredterra** [comment]
Workaround: downgrade your bench

```
pip3 install -U frappe-bench~=5.5.0
```

**Comment by barredterra** [comment]
@gavindsouza would you be so kind to have a look at this, if you can spare ay time? Thanks in advance!

**Comment by gavindsouza** [comment]
Just tried out the latest `develop` with a non-frappe app. Works fine. I think this should get resolved in the upcoming release.

<img width="879" alt="Screenshot 2022-03-17 at 12 55 22 PM" src="https://user-images.githubusercontent.com/36654812/158757946-0806386e-aedc-4efb-9580-c5729473d745.png">
