### ISSUE TITLE
bench new-app <app name>

### ISSUE THREAD

**Issue by charleslcso** [frappe/bench#1283]
Issue: Bug report

bench --version
5.7.5

**Describe the bug** :chart_with_downwards_trend:
Used an invalid name for new-app command. When prompted, input a valid name. But bench still remember the invalid name and use it to build new app.

**To Reproduce** :page_with_curl:
See screen capture.

Linux: ubuntu 20.04

**Comment by charleslcso** [comment]
Strangely I can't add screen capture.

Here is the output:

erpnext@app2:/opt/bench/frappe-bench$ bench new-app 3d_app
App Title (default: 3D App): 
App Title should start with a letter and it can only consist of letters, numbers, spaces and underscores
App Title (default: 3D App): ThreeD App
App Description: Advanced 3D Garment Model        
App Publisher: Mi
App Email: email@email.com
App Icon (default 'octicon octicon-file-directory'): octicon octicon-bug
App Color (default 'grey'): red
App License (default 'MIT'): 
'3d_app' created at /opt/bench/frappe-bench/apps/3d_app
Installing 3d_app
$ /opt/bench/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /opt/bench/frappe-bench/apps/3d_app 
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/opt/bench/frappe-bench/apps/3d_app/setup.py", line 7
          from 3d_app import __version__ as version
               ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ERROR: 
Traceback (most recent call last):
  File "/home/erpnext/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/cli.py", line 121, in cli
    raise e
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/cli.py", line 111, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/commands/make.py", line 162, in new_app
    new_app(app_name, no_git)
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/app.py", line 385, in new_app
    install_app(app, bench_path=bench_path)
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/app.py", line 412, in install_app
    bench.run(f"{bench.python} -m pip install {quiet_flag} --upgrade -e {app_path} {cache_flag}")
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/bench.py", line 43, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/erpnext/.local/lib/python3.9/site-packages/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

**Comment by revant** [comment]
try to name the app threed_app instead of 3d_app.

Or search for how to import module that starts with number.

**Comment by charleslcso** [comment]
True. If we use the proper name to start off then we won't face any issues.

But some users aren't familiar with this issue, and they specified another name after being prompted by the script, and still, the script is not using the new name.

I believe this should be handled properly.
