### ISSUE TITLE
Failing to create a bench environment for Frappe 12 development.

### ISSUE THREAD

**Issue by sebastian-code** [frappe/bench#1284]
## Description of the issue
After following the instruction in the README file to create a Frappe v12 environment for development, the installation fails.

## Context information (for bug reports)
Frappe Docker project on the last version as of today.
## Steps to reproduce the issue
1. Run the given command to create a Frappe v12 development environment `bench init --skip-redis-config-generation --frappe-branch version-12 --python python3.7 frappe-bench`.

### Observed result
Error message offering to rollback changes:
```bash
ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]: 
```
### Expected result
A proper bench environment.
### Stacktrace / full error message if available
```python
$ /home/frappe/.local/bin/virtualenv --quiet env -p python3.7
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
Getting frappe
$ git clone https://github.com/frappe/frappe.git --branch version-12 --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2664, done.
remote: Counting objects: 100% (2664/2664), done.
remote: Compressing objects: 100% (2487/2487), done.
remote: Total 2664 (delta 349), reused 1073 (delta 127), pack-reused 0
Receiving objects: 100% (2664/2664), 12.46 MiB | 8.08 MiB/s, done.
Resolving deltas: 100% (349/349), done.
Installing frappe
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/frappe 
$ yarn install
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
[4/4] Building fresh packages...
Done in 128.32s.
Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 70, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 78, in init
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 371, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets)
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 198, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 436, in install_app
    bench.reload()
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 142, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web)
  File "/home/frappe/.bench/bench/utils/bench.py", line 256, in restart_supervisor_processes
    supervisor_status = get_cmd_output("supervisorctl status", cwd=bench_path)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 185, in get_cmd_output
    output = subprocess.check_output(
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'supervisorctl status' returned non-zero exit status 127.
```

**Comment by revant** [comment]
Discussed here : https://discuss.erpnext.com/t/unable-to-initialize-bench/87449/2

**Comment by gavindsouza** [comment]
Cannot replicate on latest Bench CLI (5.14.0). Can't pinpoint when but this seems to have been addressed in the releases since then.

```python
frappe@warmachine ~/Desktop % bench init --skip-redis-config-generation --frappe-branch version-12 --python $(which python3.7) frappe-bench-v12-py37
Setting Up Environment
$ /home/frappe/.nix-profile/bin/python3.7 -m venv env
$ /home/frappe/Desktop/frappe-bench-v12-py37/env/bin/python -m pip install --quiet --upgrade pip
Getting frappe
$ git clone https://github.com/frappe/frappe.git --branch version-12 --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2665, done.
remote: Counting objects: 100% (2665/2665), done.
remote: Compressing objects: 100% (2461/2461), done.
remote: Total 2665 (delta 352), reused 1133 (delta 154), pack-reused 0
Receiving objects: 100% (2665/2665), 12.43 MiB | 3.64 MiB/s, done.
Resolving deltas: 100% (352/352), done.
Installing frappe
$ /home/frappe/Desktop/frappe-bench-v12-py37/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/Desktop/frappe-bench-v12-py37/apps/frappe 
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
[4/4] Building fresh packages...
Done in 88.66s.
Found existing apps updating states...
$ bench build
yarn run v1.22.19
$ FRAPPE_ENV=production node rollup/build.js
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js

Building frappe assets...

✔ Built js/modules.min.js
✔ Built js/dialog.min.js
✔ Built js/social.min.js
✔ Built js/checkout.min.js
✔ Built js/web_form.min.js
✔ Built js/list.min.js
✔ Built js/chat.js
✔ Built frappe/css/email.css
✔ Built js/barcode_scanner.min.js
✔ Built js/bootstrap-4-web.min.js
✔ Built js/frappe-recorder.min.js
✔ Built js/frappe-web.min.js
✔ Built js/desk.min.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
✔ Built css/frappe-rtl.css
✔ Built css/printview.css
✔ Built css/list.min.css
✔ Built css/module.min.css
✔ Built css/form.min.css
✔ Built css/report.min.css
✔ Built js/control.min.js
✔ Built css/frappe-chat-web.css
✔ Built css/web_form.css
✔ Built js/form.min.js
✔ Built css/desk.min.css
✔ Built js/data_import_tools.min.js
✔ Built css/frappe-web-b4.css
✔ Built js/report.min.js
✨  Done in 28.349s
Done in 28.91s.
SUCCESS: Bench frappe-bench-v12-py37 initialized
```
