### ISSUE TITLE
Error Installing ERPNext - 'latin-1' codec can't encode character '\u2714' in position 6: ordinal not in range(256)

### ISSUE THREAD

**Issue by ghost** [frappe/bench#1316]
I am attempting a manual installation of ERPNext. After installing all required dependencies, creating the frappe user, once I run the command:

`bench init frappe-bench --frappe-branch version-13`

This is what I receive:
```

$ bench build
Retrieving assets...
'latin-1' codec can't encode character '\u2714' in position 6: ordinal not in range(256)
Traceback (most recent call last):apps/frappe/node_modules to ./assets/frappe/node_modules                                                                                                                         
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 58, in build
    frappe.build.bundle(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 230, in bundle
    make_asset_dirs(hard_link=hard_link)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 420, in make_asset_dirs
    print(unstrip(f"{green('\u2714')} Application Assets Linked") + "\n")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2714' in position 5: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bench/commands/make.py", line 70, in init
    init(
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/system.py", line 93, in init
    build_assets(bench_path=path)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/bench.py", line 308, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]: y

```

**Comment by faisal-zahoor** [comment]
it's comes with the latest version of python, install 3.7.1 python version for erpnext version-13, and then when you run the bench init command pass the python 3.7.1 path in the parameter --python
