### ISSUE TITLE
Bench build command failed 

### ISSUE THREAD

**Issue by W2AlharbiMe** [frappe/bench#1350]
Issue: Bench build command failed 

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
when running the following command:
```bash
$ bench -v init frappe-bench
```
the installation failed with the following traceback:
```bash
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @frappe/esbuild-plugin-postcss2@0.1.3" has unmet peer dependency "less@^4.x".
warning " > @frappe/esbuild-plugin-postcss2@0.1.3" has unmet peer dependency "stylus@^0.x".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
success Saved lockfile.
Done in 22.55s.
Found existing apps updating states...
$ bench build
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/bench/commands/make.py", line 68, in init
    init(
  File "/home/username/.local/lib/python3.10/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/bench/utils/system.py", line 104, in init
    build_assets(bench_path=path)
  File "/home/username/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 330, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/home/username/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 150, in exec_cmd
    return_code = subprocess.call(cmd, cwd=cwd, universal_newlines=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bench'

ERROR: There was a problem while creating frappe-bench-second
Do you want to rollback these changes? [y/N]: 
```

**To Reproduce** :page_with_curl:
1. install bench using `pip install frappe-bench`
2. add the following alias `alias bench="/home/username/.local/bin/bench"` to `.bashrc` and then run `source .bashrc`
3. run `bench -v init frappe-bench`
4. wait for the installation to fail once reaching to `bench build`

**Expected behavior** :chart_with_upwards_trend:
installing frappe framework

**OS (please complete the following information):** :cyclone:
- [x] Linux: `arch:5.18.15-arch1-1`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.13.3
- Frappe Version: -
- ERPNext Version: -

**Additional context** :page_facing_up:
```bash
$ node -v
v18.7.0
$ yarn -v
1.22.19
$ python -V
Python 3.10.5
$ pip -V
pip 22.2.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by gavindsouza** [comment]
The problem lies in your second step. You ought to add pip's install location to `PATH` (in case pip doesn't already do that). 

---

Try adding `export PATH="$HOME/.local/bin:$PATH"` to your rc file and source it then.

**Comment by W2AlharbiMe** [comment]
thanks that worked :+1:
