### ISSUE TITLE
    raise Exception("No process manager found")

### ISSUE THREAD

**Issue by siddhant3030** [frappe/bench#1369]
I'm getting an error when I do bench start 

```
Traceback (most recent call last):
  File "/Users/arun/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/Users/arun/Documents/bench-repo/bench/cli.py", line 127, in cli
    bench_command()
  File "/Users/arun/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/arun/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/arun/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arun/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/arun/.asdf/installs/python/3.9.10/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/arun/Documents/bench-repo/bench/commands/utils.py", line 22, in start
    start(
  File "/Users/arun/Documents/bench-repo/bench/utils/system.py", line 144, in start
    raise Exception("No process manager found")
Exception: No process manager found
```

So I tried reinstalling honcho but no luck 

what should I do here?

**Comment by smzhao** [comment]
me too
