### ISSUE TITLE
Issue with Manual Install - Ubuntu 22.04

### ISSUE THREAD

**Issue by Matthewenderle** [frappe/bench#1381]
Issue: Manual Install

**Distro Information (Required)**
```
frappe@nerdUniversity:~$ uname -a
Linux nerdUniversity 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
frappe@nerdUniversity:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
frappe@nerdUniversity:~$
```

**Command Run (Required)**
`bench init frappe-bench`
```
 ERROR  There were some problems during build

Error: The service was stopped: write EPIPE
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1332:25
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:663:9
    at afterClose (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:641:7)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:2041:11
    at onwriteError (node:internal/streams/writable:417:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
Terminated
error Command failed with exit code 143.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 82, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --run-build-command' returned non-zero exit status 143.
Traceback (most recent call last):
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/system.py", line 104, in init
    build_assets(bench_path=path)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 330, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 155, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]:
```

**Additional context**

- Python `3.10.6`
- Pip `pip 22.3 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)`
- Node `v16.18.0`
- Redis server `v=7.0.5 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=68bf11aad5b039df`
- Yarn `1.22.19`
- Bench `5.14.4`

**Possible Solution**
I have no idea. I'm running this on a fresh VM of Ubuntu on DigitialOcean.

**Complete Command History**
```
root@server:~# history
    1  sudo apt update && sudo apt upgrade
    2  sudo apt install software-properties-common -y
    3  sudo add-apt-repository ppa:deadsnakes/ppa -y
    4  sudo apt update
    5  sudo apt install python3.10 -y
    6  python3.10 --version
    7  python --version
    8  which python3.10
    9  which python3
   10  python3 --version
   11  ln -s /usr/bin/python3.10 /usr/bin/python
   12  python --version
   13  sudo apt install python3.10-venv -y
   14  sudo apt install python3.10-distutils -y
   15  sudo apt install python3.10-lib2to3 -y
   16  sudo apt install python3.10-dev -y
   17  sudo reboot
   18  curl -s https://deb.nodesource.com/setup_16.x | sudo bash
   19  sudo apt install nodejs -y
   20  node -v
   21  sudo add-apt-repository ppa:redislabs/redis
   22  sudo apt-get install redis
   23  redis-server -v
   24  sudo apt install mariadb-server
   25  sudo mysql_secure_installation
   26  npm install --global yarn
   27  sudo apt install python3-pip
   34  wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
   40  sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
   41  cron
   42  apt-get install nginx
   43  apt install git
   44  apt-get install mariadb-client -y
   45  nano /etc/mysql/my.cnf
   48  service mysql restart
   49  apt-get install xvfb libfontconfig
   50  adduser
   51  adduser frappe
   52  usermod -aG sudo frappe
   53  su - frappe
frappe@server:~$ history
    1  pip3 install frappe-bench
    2  bench --version
    3  pip3 --version
    4  pip3 install frappe-bench
    10  pip3 install frappe-bench
    11  bench --version
    12  cd ~
    13  bench init frappe-bench
    20  sudo pip3 install --upgrade pip
```

**Comment by Matthewenderle** [comment]
Solved,

I had to specify the branch instead.
`bench init --frappe-branch version-14 frappe-bench`

Also, I followed the following guide.
https://frappeframework.com/docs/v14/user/en/installation
I had to relogin after `pip3 install frappe-bench` was ran since `bench -version` didn't work.
