### ISSUE TITLE
bench download-translations - requests.exceptions.HTTPError: 404 Client Error: NOT FOUND

### ISSUE THREAD

**Issue by yashodhank** [frappe/bench#143]
```
frappe@orocrm:~$ bench download-translations
downloaded for frappe fr
downloaded for frappe he
downloaded for frappe bs
downloaded for frappe hr
downloaded for frappe da
downloaded for frappe es
downloaded for frappe it
downloaded for frappe ar
downloaded for frappe kn
downloaded for frappe ca
downloaded for frappe hu
downloaded for frappe de
downloaded for frappe id
downloaded for frappe hi
downloaded for frappe ja
downloaded for frappe fa
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 592, in _download_translations
    download_translations_p()
  File "/home/frappe/bench-repo/bench/utils.py", line 553, in download_translations_p
    pool.map(update_translations_p, args)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND
```

**Comment by pdvyas** [comment]
I think you're not on the latest frappe. We changed a few lang codes
