### ISSUE TITLE
Generating Compose File Failed

### ISSUE THREAD

**Issue by Kartoffelbreili** [frappe/bench#1430]
Issue: Easy Install

**Do the checklist before filing an issue:**
 - [x] Did you retain the logfile (path of logfile is shared while the script is run)? We definitely **need** the logfile to debug any easy install related issues.
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Distro Information (Required)**
Ubuntu 22.04.1 LTS DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Command Run (Required)**
python3 easy-install.py --prod --email your@email.tld 

**Log File (Required)**
  File "/home/[redacted]/easy-install.py", line 146, in setup_prod
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'compose', '--project-name', 'frappe', '-f', 'compose.yaml', '-f', 'overrides/compose.mariadb.yaml', '-f', 'overrides/compose.redis.yaml', '-f', 'overrides/compose.https.yaml', '--env-file', '.env', 'config']' returned non-zero exit status 15.

And heres what the terminal threw:

Setting Up Production Instance

Please refer to .example.env file in the frappe_docker folder to know which keys to set

invalid interpolation format for services.frontend.labels.[].
You may need to escape any $ with another $.
required variable SITES is missing a value: List of sites not set

Generating Compose File failed

**Screenshots**

**Additional context**

Pulled newest easy-install.py. I did try with docker preinstalled and also let the script install docker. Both hat the same outcome.

**Possible Solution**
Maybe typo. Or changes in docker.

**Comment by revant** [comment]
can you test the script from this pr

https://github.com/frappe/bench/pull/1424

**Comment by Kartoffelbreili** [comment]
That one works. But now i am hitting a 404 error when trying to open the page.
Also tried setting the current site to site1.localhost again but to no avail. 
Seems to be traefik related:
[Neues Textdokument (5).txt](https://github.com/frappe/bench/files/10687261/Neues.Textdokument.5.txt)

**Comment by revant** [comment]
> frappe-proxy-1           | time="2023-02-08T15:15:56Z" level=error msg="Unable to obtain ACME certificate for domains \"site1.localhost\": unable to generate a certificate for the domains [site1.localhost]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"site1.localhost\": Domain name does not end with a valid public suffix (TLD)" providerName=main-resolver.acme routerName=frontend-http@docker rule="Host(`site1.localhost`)"

localhost domains will not work for traefik.

make sure the site exists in sites directory.

**Comment by Kartoffelbreili** [comment]
when that error comes up those directories dont exist in docker. It is a fresh install. what would i have to enter in the script to make it work?

**Comment by OsricDhoubhadel** [comment]
Confirming that I get the same error from subprocess.py when using the command from README.

Command used:
`$ wget https://raw.githubusercontent.com/frappe/bench/develop/easy-install.py
$ python3 easy-install.py --prod --email your@email.tld`

Error received:
`File "/usr/lib/python3.10/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'compose', '--project-name', 'frappe', '-f', 'compose.yaml', '-f', 'overrides/compose.mariadb.yaml', '-f', 'overrides/compose.redis.yaml', '-f', 'overrides/compose.https.yaml', '--env-file', '.env', 'config']' returned non-zero exit status 15.`

Which wget command should we use to test pr#1424?

**Comment by Henry-Do-Su** [comment]
I also have the same problem with a fresh server install

**Comment by Hel5ing** [comment]
same problem

**Comment by orbweaver-dev** [comment]
I get the same error, on every method to install:

[easy-install.log]

2023-02-20 17:30:49,912 - INFO - Running Production Setup
2023-02-20 17:30:50,591 - INFO - Downloaded frappe_docker zip file from GitHub
2023-02-20 17:30:50,608 - INFO - Unzipped and Renamed frappe_docker
2023-02-20 17:30:50,608 - INFO - Removed the downloaded zip file
2023-02-20 17:30:50,698 - ERROR - Docker Compose generation failed
Traceback (most recent call last):
  File "/home/adrian/projects/easy-install.py", line 146, in setup_prod
    subprocess.run(
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'compose', '--project-name', 'frappe', '-f', 'compose.ya

[terminal output]

[adrian@hqmain projects]$ wget https://raw.githubusercontent.com/frappe/bench/develop/easy-install.py
--2023-02-20 17:30:43--  https://raw.githubusercontent.com/frappe/bench/develop/easy-install.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9144 (8.9K) [text/plain]
Saving to: ‘easy-install.py’

easy-install.py               100%[==============================================>]   8.93K  --.-KB/s    in 0.001s  

2023-02-20 17:30:43 (6.80 MB/s) - ‘easy-install.py’ saved [9144/9144]

[adrian@hqmain projects]$ python3 easy-install.py --prod --email admin@pisys.us
 
Setting Up Production Instance
  
Please refer to .example.env file in the frappe_docker folder to know which keys to set
 
A .env file is generated with basic configs. Please edit it to fit to your needs 
 
invalid interpolation format for services.frontend.labels.[].
You may need to escape any $ with another $.
required variable SITES is missing a value: List of sites not set
 
Generating Compose File failed

**Comment by sodhancha** [comment]
### Generating Compose File failed

2024-05-19 13:42:51,493 - INFO - Running Production Setup
2024-05-19 13:42:51,502 - ERROR - Docker Compose generation failed
Traceback (most recent call last):
  File "/Users/Documents/www/erpnext/easy-install.py", line 150, in setup_prod
    subprocess.run(
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/docker', 'compose', '--project-name', 'frappe', '-f', 'compose.yaml', '-f', 'overrides/compose.mariadb.yaml', '-f', 'overrides/compose.redis.yaml', '-f', 'overrides/compose.https.yaml', '--env-file', '.env', 'config']' returned non-zero exit status 125.

**Comment by schwankd** [comment]
is there a solution yet? Im not able to install nor use frappe learning because of that issue

**Comment by asieftejani** [comment]
@schwankd can you try this and let us know if you are still facing issues: -

https://github.com/frappe/frappe_docker/issues/1640#issuecomment-3303368460

**Comment by schwankd** [comment]
Hey, i got it fixed with Claude, here is the repo for the custom installer file i builded, hope this helps smb. https://github.com/schwankd/frappe-lms-docker

No garantie it works for anybody else and i dont got rights on any of this its frappes thing i just wanted a fix for  myself
