### ISSUE TITLE
Bench fails on update when using ssh shorthands in git repository

### ISSUE THREAD

**Issue by gbm001** [frappe/bench#1432]
Issue: Bug report

**Describe the bug**
Bench update fails if you have a custom app with an unusual git repository (as seen using git remote show upstream).
For example, erpnext has git repository `https://github.com/frappe/erpnext`
Our custom app has git repository `github_unigreenscheme:bglazier/unigreenscheme.git` where github_unigreenscheme is an ssh shorthand.
Line 139 of bench app.py does not like this:

```ERROR: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/commands/update.py", line 59, in update
    update(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 440, in update
    bench.setup.requirements()
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/bench.py", line 463, in requirements
    app = App(path_to_app, bench=self.bench, to_clone=False).install(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 176, in __init__
    super().__init__(name, branch, *args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 77, in __init__
    self.setup_details()
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 88, in setup_details
    self._setup_details_from_mounted_disk()
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 113, in _setup_details_from_mounted_disk
    self._setup_details_from_git_url(self.git_repo.remotes[0].url)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 128, in _setup_details_from_git_url
    return self.__setup_details_from_git(url)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 139, in __setup_details_from_git
    self.remote_server, self.org, _repo = name.replace(protocal, "").rsplit("/", 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

**To Reproduce**
Run `bench update --reset -no-backup` with an app with a git repository with a similar URL...

**Expected behavior**
Bench Update to succeed

**OS (please complete the following information):** :cyclone:
- [x] Linux: `Ubuntu 22.04`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Version: 5.16.1
- Frappe Version: version-13
- ERPNext Version: version-13

**Possible Solution**

Fix app.py so it doesn't assume that git repositories are either at http or https addresses...

Replacing `if name.startswith("git@") or name.startswith("ssh://"):` with `if not name.startswith("http"):` was sufficient for me.

**Comment by toofun666** [comment]
That is a serious bug for on premise customer applications. Any other workarounds? Updates to bench application parsing structure planned?
self.org, _repo = _second_part.rsplit("/", 1)
is the source of idiotness... what if your second_part does not have / and it should not naturally. Big BS

**Comment by toofun666** [comment]
Use / in your local repo path and the problem is solved.
