### ISSUE TITLE
[v5.14.0+] bench setup production does not work properly

### ISSUE THREAD

**Issue by scdanieli** [frappe/bench#1434]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?

**Describe the bug** :chart_with_downwards_trend:
`sudo bench setup production frappe` does not seem work as expected: `chmod = 0760` and `chown = frappe:frappe` is not written to `/etc/supervisor/supervisord.conf`.

This causes the following error:

```
frappe@dev:~/bench$ bench restart
$ supervisorctl restart frappe:
error: <class 'PermissionError'>, [Errno 13] Permission denied: file: /usr/lib/python3/dist-packages/supervisor/xmlrpc.py line: 560
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/commands/utils.py", line 41, in restart
    Bench(".").reload(web, supervisor, systemd)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/bench.py", line 151, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web, _raise=_raise)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/bench.py", line 315, in restart_supervisor_processes
    failure = bench.run(f"{sudo}supervisorctl restart {group}", _raise=_raise)
  File "/usr/local/lib/python3.8/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
```

**Expected behavior** :chart_with_upwards_trend:
First 4 lines of `/etc/supervisor/supervisord.conf` look like this:

```
[unix_http_server]
file = /var/run/supervisor.sock   ; (the path to the socket file)
chmod = 0760
chown = frappe:frappe
```

**OS (please complete the following information):** :cyclone:
- [x] Linux: `Ubuntu 20.04.5 LTS`

**Version Information**

- Bench Branch: 5.14.0 to 5.16.1 (works fine until 5.13.4)
- Frappe Version: 13.49.2
- ERPNext Version: 13.46.1

**Additional context** :page_facing_up:
Others affected by this as well: [Frappe Discuss](https://discuss.frappe.io/t/error-class-permissionerror-errno-13-permission-denied-file-usr-lib-python3-dist-packages-supervisor-xmlrpc-py-line-560/93632)

**Possible Solution** :bookmark_tabs:
Seems something has changed between version 5.13.4 and 5.14.0 on Aug 4, 2022 causing the issue (@gavindsouza).

**Comment by matbgn** [comment]
Noop still have issue on a fresh install `bench --version == 5.16.2`

```
$ sudo supervisorctl restart frappe:
frappe: ERROR (no such group)
frappe: ERROR (no such group)
WARN: restarting supervisor failed. Use `bench restart` to retry.
$ bench build
Assets for Commit 86f72195251c5abfcacf5f9db0351fb0b54f8e1c don't exist
✔ Application Assets Linked
```

After manually fixing the file I still have following issue:

```
$ supervisorctl restart frappe:
unix:///var/run/supervisor.sock no such file
WARN: restarting supervisor failed. Use `bench restart` to retry.

**Comment by Utesar72** [comment]
Hi, does anyone have a answer? Pls kindly help the erpnext 14 community....Because of this a lot of people are hesitating to go with ERPNEXT. instead they go with ODOO

**Comment by uc77** [comment]
Hi everyone, is there any updates to this issue please? Since several issues are thrown predominantly due to this issue.

I get "WARN: restart failed: Couldn't find supervisorctl in PATH" and cannot restart bench due to the supervisor issue. Although I did follow a guide to install supervisor nothing works.

Thanks guys!

**Comment by uc77** [comment]
I have used the ERPNext Bitnami package for Google Cloud and am facing this issue without any solutions.

**Comment by Abdeali099** [comment]
Any Solution for this?

Error Log:

```log
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at /usr/share/cargo/registry/pyo3-0.20.2/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 5, in <module>
    from ansible.cli.playbook import main
  File "/usr/local/lib/python3.11/dist-packages/ansible/cli/__init__.py", line 96, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/local/lib/python3.11/dist-packages/ansible/inventory/manager.py", line 37, in <module>
    from ansible.plugins.loader import inventory_loader
  File "/usr/local/lib/python3.11/dist-packages/ansible/plugins/loader.py", line 30, in <module>
    from ansible.parsing.utils.yaml import from_yaml
  File "/usr/local/lib/python3.11/dist-packages/ansible/parsing/utils/yaml.py", line 15, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/local/lib/python3.11/dist-packages/ansible/parsing/yaml/loader.py", line 22, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/local/lib/python3.11/dist-packages/ansible/parsing/yaml/constructor.py", line 26, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/local/lib/python3.11/dist-packages/ansible/parsing/vault/__init__.py", line 40, in <module>
    from cryptography.exceptions import InvalidSignature
  File "/usr/lib/python3/dist-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
pyo3_runtime.PanicException: Python API call failed
ERROR: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '{"production": true, "admin_emails": "", "mysql_root_password": null, "container": false}', '-t', 'fail2ban']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bench/commands/setup.py", line 370, in setup_roles
    run_playbook("site.yml", extra_vars=extra_vars, tag=role)
  File "/usr/local/lib/python3.11/dist-packages/bench/utils/__init__.py", line 348, in run_playbook
    subprocess.check_call(args, cwd=os.path.join(bench.__path__[0], "playbooks"))
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '{"production": true, "admin_emails": "", "mysql_root_password": null, "container": false}', '-t', 'fail2ban']' returned non-zero exit status 1.
ERROR: bench setup role fail2ban
subprocess.CalledProcessError: Command 'bench setup role fail2ban' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.11/dist-packages/bench/commands/setup.py", line 110, in setup_production
    setup_production(user=user, yes=yes)
  File "/usr/local/lib/python3.11/dist-packages/bench/config/production_setup.py", line 37, in setup_production
    setup_production_prerequisites()
  File "/usr/local/lib/python3.11/dist-packages/bench/config/production_setup.py", line 28, in setup_production_prerequisites
    exec_cmd("bench setup role fail2ban")
  File "/usr/local/lib/python3.11/dist-packages/bench/utils/__init__.py", line 181, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench setup role fail2ban

```
