### ISSUE TITLE
bench setup requirements failed

### ISSUE THREAD

**Issue by amalpaul54111** [frappe/bench#1451]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:
Running the `bench setup requirements` command raises an exception.
The last CI/ Tests shows the same issue 
https://github.com/frappe/bench/actions/runs/4881678149/jobs/8712432796

```Installing 1 applications...
ERROR: . not found in frappe or erpnext
Traceback (most recent call last):
  File "/home/frappe/.bench/bench/utils/__init__.py", line 437, in fetch_details_from_tag
    org, repo = org_repo
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.bench/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/setup.py", line 228, in setup_requirements
    bench.setup.requirements(apps=apps)
  File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 463, in requirements
    app = App(path_to_app, bench=self.bench, to_clone=False).install(
  File "/home/frappe/.bench/bench/app.py", line 174, in __init__
    super().__init__(name, branch, *args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 77, in __init__
    self.setup_details()
  File "/home/frappe/.bench/bench/app.py", line 100, in setup_details
    self._setup_details_from_name_tag()
  File "/home/frappe/.bench/bench/app.py", line 122, in _setup_details_from_name_tag
    self.org, self.repo, self.tag = fetch_details_from_tag(self.name)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 439, in fetch_details_from_tag
    org, repo = find_org(org_repo)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 421, in find_org
    raise InvalidRemoteException(f"{org_repo} not found in frappe or erpnext")
bench.exceptions.InvalidRemoteException: . not found in frappe or erpnext
```

**To Reproduce** :chart_with_downwards_trend: 
1. bench init --version=v14.30.0 --frappe-path=https://github.com/frappe/frappe --skip-redis-config-generation --verbose --skip-assets /home/frappe/frappe-bench
2. cd /home/frappe/frappe-bench
3.  bench setup requirements

**Expected behavior** :chart_with_upwards_trend:
An exit code of 0

**OS (please complete the following information):** :cyclone:
Linux, frappe/bench:latest docker image

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: develop
- Frappe Version: v14.30.0

**Comment by amalpaul54111** [comment]
The current docker image of bench only lists two tags on https://hub.docker.com/r/frappe/bench/tags. One is the latest with the bug and other one is something of version-12(not useful). I could find a tag from the GitHub actions docker.io/frappe/bench:latest@sha256:de5f548750f2b9c1375ad477d06dd3d0da3a513a5695564ba9ee9d1bee8a8ad7
https://github.com/frappe/frappe_docker/actions/runs/4867010254/job8679149437#step:7:1954

This is a week older image and could be used in case if the latest bench image doesn't work for you.

**Comment by CleoMenezesJr** [comment]
Can reproduce it!

**Comment by ankush** [comment]
Ah not sure why frappe docker is installing bench from source. This is fixed for now.

We should be using releases? @revant
