### ISSUE TITLE
Incorrect documentation: bench update --bench

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/bench#1473]
The [Frappe Framework docs](https://frappeframework.com/docs/user/en/bench/resources/bench-commands-cheatsheet) mention a `bench update --bench` command.
However, it results in `Error: No such option: --bench`. The `--help` command doesn't mention the `--bench` flag either.

The archived [Frappe Docs repo](https://github.com/frappe/frappe_docs) points to https://frappeframework.com/contribute for contribution guidelines for the documentation. But following the link results in a HTTP 417 with the following error traceback.

```py
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_renderer.py", line 46, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 518, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 49, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 65, in update_context
    ret = self.doc.get_context(self.context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_page.py", line 230, in get_context
    context.wiki_search_scope = self.get_space_route()
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_page.py", line 197, in get_space_route
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 550, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 518, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 467, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Wiki Page doesn't have a Wiki Space associated with it. Please add them via Desk.
```

![image](https://github.com/frappe/bench/assets/57280279/f914944b-ba23-4e84-b36f-4ca98a2bdca6)

**Comment by lamphanjk** [comment]
We have same issue. Could we have any update for this bug

**Comment by SvbZ3r0** [comment]
In the meantime, you can use `pip install -U frappe-bench`.
