### ISSUE TITLE
bench switch-to-v5 --upgrade fails: error: pathspec 'v5.x.x' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by jevonearth** [frappe/bench#148]
Running on an up-to-date V4.

```
erpnext@erp-sandbox:~/frappe-bench$ bench switch-to-v5 --upgrade
Already on 'v5.x.x'
Your branch is up-to-date with 'upstream/v5.x.x'.
Already up-to-date.
Already on 'v5.x.x'
Your branch is up-to-date with 'upstream/v5.x.x'.
Already up-to-date.
error: pathspec 'v5.x.x' did not match any file(s) known to git.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.92', 'console_scripts', 'bench')()
  File "/home/erpnext/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/bench-repo/bench/cli.py", line 345, in _switch_to_v5
    switch_to_v5(upgrade=upgrade)
  File "/home/erpnext/bench-repo/bench/app.py", line 183, in switch_to_v5
    switch_branch('v5.x.x', apps=apps, bench=bench, upgrade=upgrade)
  File "/home/erpnext/bench-repo/bench/app.py", line 161, in switch_branch
    exec_cmd("git checkout {branch}".format(branch=branch), cwd=app_dir)
  File "/home/erpnext/bench-repo/bench/utils.py", line 104, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git checkout v5.x.x
erpnext@erp-sandbox:~/frappe-bench$
```

**Comment by pdvyas** [comment]
Do you have `shopping_cart` in your apps dir by any chance?

**Comment by jevonearth** [comment]
Yes! Should it be removed? I don't use it.

**Comment by pdvyas** [comment]
Yeah, funny pre-upgrade should have done it.

```
remove the dir, and also run
bench remove-from-installed-apps shopping_cart
bench retry-upgrade
```

Why don't you directly upgrade to v6 (master branch)?

**Comment by jevonearth** [comment]
remove-from-installed-apps doesn't seem to be implemented.

```
erpnext@erp-sandbox:~/frappe-bench$ bench remove-from-installed-apps shopping_cart
Usage: bench [OPTIONS] COMMAND [ARGS]...

Error: No such command "remove-from-installed-apps".

```

**Comment by pdvyas** [comment]
It should be there in v4 to 5 patches as well. If this is a test instance, not prod, please try  the `bench retry-upgrade`

**Comment by bfoxtrot** [comment]
Getting this same issue. Found this in the forums 

https://discuss.erpnext.com/t/v5-upgrade-failing/7248/9

Any resolution to this issue?
