### ISSUE TITLE
ERROR: supervisorctl restart frappe running: bench restart 

### ISSUE THREAD

**Issue by jonas-kupferschmid** [frappe/bench#1514]
**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
When I try to run branch restart I get 

```

$ supervisorctl restart frappe:
frappe: ERROR (no such group)
frappe: ERROR (no such group)
ERROR: supervisorctl restart frappe:
subprocess.CalledProcessError: Command 'supervisorctl restart frappe:' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/site-packages/bench/commands/utils.py", line 41, in restart
    Bench(".").reload(web, supervisor, systemd)
  File "/usr/local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bench/bench.py", line 152, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web, _raise=_raise)
  File "/usr/local/lib/python3.10/site-packages/bench/utils/bench.py", line 321, in restart_supervisor_processes
    failure = bench.run(f"{sudo}supervisorctl restart {group}", _raise=_raise)
  File "/usr/local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: supervisorctl restart frappe:

```

**Comment by iqbaltld** [comment]
I tried these commands and it worked

```
bench setup socketio
bench setup supervisor
bench setup redis
sudo supervisorctl reload
```

**Comment by hawkwang** [comment]
> I tried these commands and it worked
> 
> ```
> bench setup socketio
> bench setup supervisor
> bench setup redis
> sudo supervisorctl reload
> ```



> I tried these commands and it worked
> 
> ```
> bench setup socketio
> bench setup supervisor
> bench setup redis
> sudo supervisorctl reload
> ```

when I run "sudo supervisorctl reload", I got following error message:
error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib64/python2.7/socket.py line: 224

???

**Comment by aditi-techbird** [comment]
> error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib64/python2.7/socket.py line: 224

Did you find any solution for this?

**Comment by yelbanna** [comment]
try this: https://discuss.frappe.io/t/stopping-bench-in-a-multi-bench-setup/48499/11?u=yasserelbana
