### ISSUE TITLE
Why is it so difficult to get started?

### ISSUE THREAD

**Issue by pokhiii** [frappe/bench#1535]
Issue: Easy Install

**Do the checklist before filing an issue:**
 - [x] Did you retain the logfile (path of logfile is shared while the script is run)? We definitely **need** the logfile to debug any easy install related issues.
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Distro Information (Required)**

Paste the contents of
1. uname -a
   ```
   Darwin Pokhis-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64
   ```
1. cat /etc/*-release

   ```
   This command does not work
   ```

**Command Run (Required)**
```
bench init frappe-bench
```

**Log File (Required)**

```
Setting Up Environment
$ python3 -m venv env
$ /Users/pokhi/Projects/experiments/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
$ /Users/pokhi/Projects/experiments/frappe-bench/env/bin/python -m pip install --quiet wheel
Getting frappe
$ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3226, done.
remote: Counting objects: 100% (3226/3226), done.
remote: Compressing objects: 100% (2838/2838), done.
remote: Total 3226 (delta 440), reused 2036 (delta 275), pack-reused 0
Receiving objects: 100% (3226/3226), 11.09 MiB | 276.00 KiB/s, done.
Resolving deltas: 100% (440/440), done.
Installing frappe
$ /Users/pokhi/Projects/experiments/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /Users/pokhi/Projects/experiments/frappe-bench/apps/frappe
$ yarn install --check-files
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
subprocess.CalledProcessError: Command 'yarn install --check-files' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/bench/commands/make.py", line 75, in init
    init(
  File "/opt/homebrew/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bench/utils/system.py", line 87, in init
    get_app(
  File "/opt/homebrew/lib/python3.11/site-packages/bench/app.py", line 771, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/opt/homebrew/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bench/app.py", line 254, in install
    install_app(
  File "/opt/homebrew/lib/python3.11/site-packages/bench/app.py", line 914, in install_app
    bench.run(yarn_install, cwd=app_path)
  File "/opt/homebrew/lib/python3.11/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bench/utils/__init__.py", line 169, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: yarn install --check-files

ERROR: There was a problem while creating frappe-bench
```

**Screenshots**
![image](https://github.com/frappe/bench/assets/11808845/77913fe2-b5d8-49da-9c00-d81abc47a333)

**Additional context**

**Possible Solution**

**Comment by arunmathaisk** [comment]
Hey please try using the docker setup 

https://github.com/frappe/frappe_docker

or simply run the easy-install.py with the dev flag.

Btw  below is your issue of node version. Rectify this and you should be good to go :)

```
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.15.0"
error Found incompatible module.
```

**Comment by pokhiii** [comment]
Thanks @arunmathaisk. Indeed Node was the issue.
