### ISSUE TITLE
dependency failed to start: container frappe-db-1 is unhealthy

### ISSUE THREAD

**Issue by RealYingxi** [frappe/bench#1548]
Issue: Bug report

system: debian-11.3.0-amd64

python3 easy-install.py --prod --email *@*.*

`Setting Up Production Instance
 
 Docker is not installed, Installing Docker... 
 Waiting Docker to start 
 
Please refer to .example.env file in the frappe_docker folder to know which keys to set

 
 
A .env file is generated with basic configs. Please edit it to fit to your needs 
 
[+] Running 40/40
 ✔ queue-short Pulled                                                                           185.1s 
 ✔ websocket Pulled                                                                             185.0s 
 ✔ proxy 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                  76.7s 
   ✔ 97518928ae5f Pull complete                                                                  51.1s 
   ✔ 8f1084cd7998 Pull complete                                                                  50.5s 
   ✔ cd589cd7ab30 Pull complete                                                                  60.4s 
   ✔ 34d201bdb744 Pull complete                                                                  53.3s 
 ✔ queue-long Pulled                                                                            185.1s 
 ✔ redis-queue Pulled                                                                            76.9s 
 ✔ scheduler Pulled                                                                             185.0s 
 ✔ backend 10 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                        184.9s 
   ✔ 1f7ce2fa46ab Pull complete                                                                   6.7s 
   ✔ 442c5d63eafd Pull complete                                                                   2.6s 
   ✔ c3aa3af0d581 Pull complete                                                                   3.9s 
   ✔ 4bfbe15b3e01 Pull complete                                                                   4.5s 
   ✔ 848d19a36773 Pull complete                                                                   6.0s 
   ✔ 66ef31aea013 Pull complete                                                                  47.6s 
   ✔ 633a43b3e8e7 Pull complete                                                                   8.0s 
   ✔ a3230aeb1c36 Pull complete                                                                   9.6s 
   ✔ 91253bb17311 Pull complete                                                                  55.8s 
   ✔ 4f4fb700ef54 Pull complete                                                                  15.0s 
 ✔ db 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                 92.2s 
   ✔ 17d0386c2fff Pull complete                                                                  58.6s 
   ✔ 88de752949fb Pull complete                                                                  56.0s 
   ✔ 91371705b999 Pull complete                                                                  59.8s 
   ✔ 3ea86c9dd2a8 Pull complete                                                                  60.1s 
   ✔ cf50ec0c5825 Pull complete                                                                  61.2s 
   ✔ c340bc5dcc0f Pull complete                                                                  70.8s 
   ✔ 8fe6fbd48eb3 Pull complete                                                                  61.7s 
   ✔ 886a789bf7bc Pull complete                                                                  62.9s 
 ✔ redis-cache 7 layers [⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                         76.9s 
   ✔ 4abcf2066143 Pull complete                                                                  26.2s 
   ✔ 2c3a1d240687 Pull complete                                                                  33.8s 
   ✔ 643f361aa308 Pull complete                                                                  37.0s 
   ✔ a693cf0e318c Pull complete                                                                  41.5s 
   ✔ ade57efb0b22 Pull complete                                                                  46.3s 
   ✔ 2fa2e1566407 Pull complete                                                                  46.3s 
   ✔ 4464e0709769 Pull complete                                                                  47.7s 
 ✔ configurator Pulled                                                                          185.1s 
 ✔ frontend Pulled                                                                              185.0s 
[+] Running 4/17
 ⠋ Network frappe_default            Created                                                     27.0s 
 ⠦ Volume "frappe_cert-data"         Created                                                     26.6s 
 ⠦ Volume "frappe_redis-cache-data"  Created                                                     26.6s 
 ⠦ Volume "frappe_sites"             Created                                                     26.6s 
 ⠦ Volume "frappe_redis-queue-data"  Created                                                     26.6s 
 ⠴ Volume "frappe_db-data"           Created                                                     26.6s 
 ✔ Container frappe-redis-cache-1    Started                                                      9.9s 
 ✔ Container frappe-redis-queue-1    Started                                                      9.5s 
 ✔ Container frappe-proxy-1          Started                                                      9.6s 
 ✘ Container frappe-db-1             Error                                                       26.5s 
 ⠴ Container frappe-configurator-1   Created                                                     23.5s 
 ⠼ Container frappe-queue-short-1    Created                                                     22.4s 
 ⠼ Container frappe-backend-1        Created                                                     22.4s 
 ⠼ Container frappe-websocket-1      Created                                                     22.4s 
 ⠼ Container frappe-scheduler-1      Created                                                     22.4s 
 ⠼ Container frappe-queue-long-1     Created                                                     22.4s 
 ⠙ Container frappe-frontend-1       Created                                                     20.1s 
dependency failed to start: container frappe-db-1 is unhealthy
  Docker Compose failed, please check the container logs
 Command '['/usr/bin/docker', 'compose', '-p', 'frappe', '-f', '/root/frappe-compose.yml', 'up', '-d']' returned non-zero exit status 1.`

full log

`2024-03-27 06:23:13,419 - INFO - Running Production Setup
2024-03-27 06:23:13,419 - INFO - Docker not found, installing Docker
2024-03-27 06:25:19,609 - INFO - Downloaded frappe_docker zip file from GitHub
2024-03-27 06:25:19,669 - INFO - Unzipped and Renamed frappe_docker
2024-03-27 06:25:19,669 - INFO - Removed the downloaded zip file
2024-03-27 06:28:52,146 - ERROR - Prod docker-compose failed
Traceback (most recent call last):
  File "/root/easy-install.py", line 188, in setup_prod
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'compose', '-p', 'frappe', '-f', '/root/frappe-compose.yml', 'up', '-d']' returned non-zero exit status 1.
`

**Comment by RafaelJohn9** [comment]
can I be assigned this issue

**Comment by abdullah-azab** [comment]
same here 
` >python3 easy-install.py --prod --email your@email.tld

Setting Up Production Instance


Please refer to .example.env file in the frappe_docker folder to know which keys to set



A .env file is generated with basic configs. Please edit it to fit to your needs

[+] Running 7/7
 ✔ scheduler Pulled                                                                                                6.1s
 ✔ queue-long Pulled                                                                                               5.7s
 ✔ configurator Pulled                                                                                             5.1s
 ✔ frontend Pulled                                                                                                 5.7s
 ✔ websocket Pulled                                                                                                6.1s
 ✔ backend Pulled                                                                                                  6.0s
 ✔ queue-short Pulled                                                                                              5.0s
[+] Running 12/12
 ✔ Network frappe_default           Created                                                                        0.3s
 ✔ Container frappe-proxy-1         Started                                                                      438.9s
 ✘ Container frappe-db-1            Error                                                                        464.4s
 ✔ Container frappe-redis-cache-1   Started                                                                      463.8s
 ✔ Container frappe-redis-queue-1   Started                                                                      463.6s
 ✔ Container frappe-configurator-1  Created                                                                       73.6s
 ✔ Container frappe-queue-short-1   Created                                                                      154.2s
 ✔ Container frappe-scheduler-1     Created                                                                      154.3s
 ✔ Container frappe-backend-1       Created                                                                      154.3s
 ✔ Container frappe-queue-long-1    Created                                                                      154.2s
 ✔ Container frappe-websocket-1     Created                                                                      154.3s
 ✔ Container frappe-frontend-1      Created                                                                       61.4s
dependency failed to start: container frappe-db-1 is unhealthy
  Docker Compose failed, please check the container logs
 Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.EXE', 'compose', '-p', 'frappe', '-f', 'C:\\Users\\abdul\\frappe-compose.yml', 'up', '-d']' returned non-zero exit status 1.
 `
