### ISSUE TITLE
Can't run bench.

### ISSUE THREAD

**Issue by agatho-daemon** [frappe/bench#1552]
Issue: Bug report

I have just installed bench but can't run it at all. The only command I can run is plain `bench` which would display the help menu.

Ran on Ubuntu22, and now 24.
Used Ubuntu python/pip and pyenv python/pip

I always get he same error:
```shell
$ bench version
Traceback (most recent call last):
  File "/home/ismail/.pyenv/versions/3.11.9/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ismail/.pyenv/versions/3.11.9/lib/python3.11/site-packages/bench/cli.py", line 74, in cli
    cmd_from_sys = get_cmd_from_sysargv()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ismail/.pyenv/versions/3.11.9/lib/python3.11/site-packages/bench/utils/__init__.py", line 568, in get_cmd_from_sysargv
    if sys_argv.index(arg) == 0 and arg in Bench(".").apps:
                                           ^^^^^^^^^^
  File "/home/ismail/.pyenv/versions/3.11.9/lib/python3.11/site-packages/bench/bench.py", line 67, in __init__
    self.apps = BenchApps(self)
                ^^^^^^^^^^^^^^^
  File "/home/ismail/.pyenv/versions/3.11.9/lib/python3.11/site-packages/bench/bench.py", line 175, in __init__
    self.initialize_apps()
  File "/home/ismail/.pyenv/versions/3.11.9/lib/python3.11/site-packages/bench/bench.py", line 282, in initialize_apps
    self.apps.remove("frappe")
ValueError: list.remove(x): x not in list
```

The same is true if I try to run any command in the list.

**Comment by agatho-daemon** [comment]
I did a clean fresh install with a clean user directory (removed all user data files, caches etc) and the problem is gone.

**Comment by agatho-daemon** [comment]
I did a clean fresh install with a clean user directory (removed all user data files, caches etc) and the problem is gone.
