### ISSUE TITLE
Bench setup script fails when running frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe

### ISSUE THREAD

**Issue by kgurnani96** [frappe/bench#164]
Here are the logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.92', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 166, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch, verbose=verbose)
  File "/home/frappe/bench-repo/bench/utils.py", line 72, in init
    get_app('frappe', frappe_path, branch=frappe_branch, bench=path, build_asset_files=False, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 54, in get_app
    install_app(app, bench=bench, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 80, in install_app
    find_links=find_links))
  File "/home/frappe/bench-repo/bench/utils.py", line 105, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
```

It causes a MemoryError:

```
Exception:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError
```

**Comment by anandpdoshi** [comment]
You need >= 1gb of ram. If you don't have it, you should setup swap.

**Comment by kgurnani96** [comment]
I didnt know that, i kept on trying to set it up on a 512mb droplet, you guys should write it somewhere in this project's README, anyway thanks for the heads up.

**Comment by ni8mr** [comment]
@kgurnani96  swap should be set in case of low memory for better Linux based development. :)

**Comment by anandpdoshi** [comment]
@kgurnani96 you are right, we need to write that down in the bench's [readme](https://github.com/frappe/bench/blob/master/README.md). Would you like to update it and record you contribution?

**Comment by kgurnani96** [comment]
@ni8mr i forgot to, my bad, thought it would run on low mem because i had previously setup erpnext 4.x on 512mb droplet and it worked flawlessly, also thanks. @anandpdoshi sure, i will do it once i get home.
