### ISSUE TITLE
bench update --patch error

### ISSUE THREAD

**Issue by Eslem** [frappe/bench#172]
Hello.
I'm trying to update but i'm getting this error when i execute  ```
bench update --path.```

```
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
From https://github.com/frappe/shopping-cart
 * branch            master     -> FETCH_HEAD
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 213, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v5_0/rename_table_fieldnames.py", line 32, in execute
    rename_field(dt, field[0], field[1])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/rename_field.py", line 38, in rename_field
    update_property_setters(doctype, old_fieldname, new_fieldname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/rename_field.py", line 123, in update_property_setters
    (doctype, old_fieldname), as_dict=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 135, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'email_alert_recipients'%'' at line 2")
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 241, in _update
    update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/cli.py", line 270, in update
    patch_sites(bench=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 161, in patch_sites
    run_frappe_cmd('--site', 'all', 'migrate', bench=bench)
  File "/home/frappe/bench-repo/bench/utils.py", line 496, in run_frappe_cmd
    raise CommandFailedError(args)
bench.utils.CommandFailedError: ('--site', 'all', 'migrate')
```

Also i'm getting this server error:
```
Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 99, in __init__
    self.make_session(resume=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 148, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 168, in __init__
    self.resume()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 223, in resume
    data = self.get_session_record()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 240, in get_session_record
    r = self.get_session_data()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 255, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 276, in get_session_data_from_db
    self.device = frappe.db.get_value("Sessions", {"sid": self.sid}, "device") or 'desktop'
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 396, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 437, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 549, in _get_values_from_table
    conditions, order_by), values, as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 135, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
 OperationalError: (1054, "Unknown column 'device' in 'field list'")

```

**Comment by nabinhait** [comment]
Pushed a fix in develop branch
https://github.com/frappe/frappe/commit/8b88b18f1172b6dbe13d4c241adce80eb1dc1d11
