### ISSUE TITLE
Arch Linux Support?

### ISSUE THREAD

**Issue by gutenye** [frappe/bench#177]
I love open source and use Arch Linux for Development, any plans that the install script to support Arch Linux?

Thanks for the erpnext.

**Comment by pdvyas** [comment]
It's not on the list but you should be able to install it the manual way, https://github.com/frappe/bench#manual-install

**Comment by gutenye** [comment]
@pdvyas I try to install manually, but got errors.

$ bench --site site1.local install-app erpnext

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/installer.py", line 92, in install_app
    frappe.clear_cache()
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 424, in clear_cache
    for fn in frappe.get_hooks("clear_cache"):
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 716, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/utils/redis_wrapper.py", line 68, in get_value
    val = generator()
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 684, in load_app_hooks
    for app in [app_name] if app_name else get_installed_apps(sort=True):
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 664, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/database.py", line 641, in get_global
    return self.get_default(key, user)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/database.py", line 653, in get_default
    d = self.get_defaults(key, parent)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/database.py", line 659, in get_defaults
    defaults = frappe.defaults.get_defaults(parent)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/defaults.py", line 72, in get_defaults
    globald = get_defaults_for()
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/defaults.py", line 177, in get_defaults_for
    where parent = %s order by creation""", (parent,), as_dict=1)
  File "/home/guten/app/erpnext/app/apps/frappe/frappe/database.py", line 135, in sql
    self._cursor.execute(query, values)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table '1bd3e0294d.tabDefaultValue' doesn't exist")
```

I can not debug it for I don't know what's going on under the command.

**Comment by anandpdoshi** [comment]
Hmm did you do `bench new-site site1.local` first?

**Comment by gutenye** [comment]
@anandpdoshi thanks, I've fixed it, but got a new error, https://github.com/frappe/bench/issues/178
