### ISSUE TITLE
RuntimeError: no object bound to conf

### ISSUE THREAD

**Issue by gutenye** [frappe/bench#178]
There're my steps to install it manually, I've fixed the install-app problem, but got a new one

```
$ bench init frappe-bench && cd frappe-bench
$ bench get-app erpnext https://github.com/frappe/erpnext
$ bench new-site site1.local
$ bench --site site1.local install-app erpnext 
$ bench start
```

run `$ bench install-app erpnext` has an error for me, I must run as `$ bench --site site1.local install-app erpnext`

After running and go to `http://localhost:8000`, I've got the new error:

```
13:54:47 web.1                |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
13:54:47 web.1                |  * Restarting with inotify reloader
13:54:48 web.1                |  * Debugger is active!
13:54:48 web.1                |  * Debugger pin code: 298-656-964
13:54:55 web.1                | Traceback (most recent call last):
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/middlewares.py", line 15, in __call__
13:54:55 web.1                |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
13:54:55 web.1                |     return self.app(environ, start_response)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
13:54:55 web.1                |     return self.app(environ, start_response)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
13:54:55 web.1                |     return ClosingIterator(app(environ, start_response), self.cleanup)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
13:54:55 web.1                |     return f(*args[:-2] + (request,))(*args[-2:])
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/app.py", line 113, in application
13:54:55 web.1                |     response = frappe.website.render.render("message", http_status_code=http_status_code)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/website/render.py", line 22, in render
13:54:55 web.1                |     path = resolve_path(path.strip("/ "))
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/website/render.py", line 152, in resolve_path
13:54:55 web.1                |     path = resolve_from_map(path)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/website/render.py", line 158, in resolve_from_map
13:54:55 web.1                |     for r in frappe.get_hooks("website_route_rules")])
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 716, in get_hooks
13:54:55 web.1                |     hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/apps/frappe/frappe/__init__.py", line 196, in cache
13:54:55 web.1                |     redis_server = RedisWrapper.from_url(conf.get("cache_redis_server") or "redis://localhost:11311")
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
13:54:55 web.1                |     return getattr(self._get_current_object(), name)
13:54:55 web.1                |   File "/home/guten/app/erpnext/app/env/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
13:54:55 web.1                |     raise RuntimeError('no object bound to %s' % self.__name__)
13:54:55 web.1                | RuntimeError: no object bound to conf
```

/cc @pdvyas

**Comment by anandpdoshi** [comment]
try doing `bench use site1.local` and then try to open localhost:8000

**Comment by anandpdoshi** [comment]
@gutenye once you get it working, can you quickly write a wiki article on how to install erpnext on archlinux? https://github.com/frappe/bench/wiki

**Comment by gutenye** [comment]
@anandpdoshi 

sure, and It IS WORKING. :heart: :heart:  :heart:

**Comment by gutenye** [comment]
Here you go,
https://github.com/frappe/bench/wiki/Install-ERPNext-on-ArchLinux

On Fri, Jan 29, 2016 at 2:20 PM, Anand Doshi <notifications@github.com>
wrote:

> @gutenye <https://github.com/gutenye> once you get it working, can you
> quickly write a wiki article on how to install erpnext on archlinux?
> https://github.com/frappe/bench/wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/bench/issues/178#issuecomment-176599054>.
>



-- 
Linux, Vim, Ruby, Go and Javascript
- Guten.me  <http://GutenYe.com>
- GitHub.com/GutenYe <http://Github.com/GutenYe>

**Comment by anandpdoshi** [comment]
@gutenye thanks a lot. You are awesome!

**Comment by Livuza** [comment]
> try doing `bench use site1.local` and then try to open localhost:8000

This worked for me!

**Comment by tanveer-ahmad74** [comment]
> try doing `bench use site1.local` and then try to open localhost:8000

its working bro thank you so much
