### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when doing bench install-app

### ISSUE THREAD

**Issue by mach-kernel** [frappe/bench#180]
Hi,

Steps to reproduce:

```
cd ~
bench init frappe-bench
cd frappe-bench
bench get-app erpnext https://github.com/frappe/erpnext         # Add ERPNext to your bench apps
bench new-site site1.local                      # Create a new site
bench install-app erpnext                       # Install ERPNext for the site
```

Output:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/David/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/David/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/David/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/David/frappe-bench/apps/frappe/frappe/commands.py", line 159, in install_app
    for site in context.sites:
TypeError: 'NoneType' object is not iterable
```

I have updated my `my.cnf` with the provided information. When I try running `bench --site site1.local install-app erpnext` I get:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/David/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/David/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/David/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/David/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/Users/David/frappe-bench/apps/frappe/frappe/installer.py", line 92, in install_app
    frappe.clear_cache()
  File "/Users/David/frappe-bench/apps/frappe/frappe/__init__.py", line 424, in clear_cache
    for fn in frappe.get_hooks("clear_cache"):
  File "/Users/David/frappe-bench/apps/frappe/frappe/__init__.py", line 716, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/Users/David/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 68, in get_value
    val = generator()
  File "/Users/David/frappe-bench/apps/frappe/frappe/__init__.py", line 684, in load_app_hooks
    for app in [app_name] if app_name else get_installed_apps(sort=True):
  File "/Users/David/frappe-bench/apps/frappe/frappe/__init__.py", line 664, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/Users/David/frappe-bench/apps/frappe/frappe/database.py", line 641, in get_global
    return self.get_default(key, user)
  File "/Users/David/frappe-bench/apps/frappe/frappe/database.py", line 653, in get_default
    d = self.get_defaults(key, parent)
  File "/Users/David/frappe-bench/apps/frappe/frappe/database.py", line 659, in get_defaults
    defaults = frappe.defaults.get_defaults(parent)
  File "/Users/David/frappe-bench/apps/frappe/frappe/defaults.py", line 72, in get_defaults
    globald = get_defaults_for()
  File "/Users/David/frappe-bench/apps/frappe/frappe/defaults.py", line 177, in get_defaults_for
    where parent = %s order by creation""", (parent,), as_dict=1)
  File "/Users/David/frappe-bench/apps/frappe/frappe/database.py", line 135, in sql
    self._cursor.execute(query, values)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/David/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table '1bd3e0294d.tabdefaultvalue' doesn't exist")
```

If I try creating the table manually it doesn't work either. At this point it makes my Apache Hadoop deploy process look like a breeze. Is there anything I can do?

**Comment by anandpdoshi** [comment]
Looks like the new-site command failed. Remove the site folder site1.local and try again.

**Comment by mach-kernel** [comment]
@anandpdoshi I have tried over and over again multiple times.

**Comment by mach-kernel** [comment]
@anandpdoshi, 

After doing some digging, I found the schema that is supposed to be used for the `new-site` command here: https://github.com/nijil/wnframework/blob/master/conf/Framework.sql

But that's not right, because `tabUserRole` does not exist after the table is populated with this data, but the schema for `tabDocPerm` appears to be similar enough to the point where it will get past any errors. I'm running into a permissions error now.

```
➜  frappe-bench  bench --site ass.local install-app erpnext
Installing erpnext...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/David/Git/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/installer.py", line 114, in install_app
    frappe.only_for("System Manager")
  File "/Users/David/Git/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in only_for
    raise PermissionError
frappe.exceptions.PermissionError
```

**Comment by rmehta** [comment]
@mach-kernel that is a pretty old code. Can you pull the latest frappe / erpnext and check again? This is pretty standard stuff and should work out of the box.

**Comment by mach-kernel** [comment]
@rmehta I was able to build using the latest snapshot from `develop` branch. Do you guys have a `stable` branch?

**Comment by anandpdoshi** [comment]
That branch is 'master'

**Comment by viral85** [comment]
I had the same issues .

bench init frappe-demo
cd frappe-demo
bench get-app erpnext https://github.com/frappe/erpnext
bench new-site demo.1

Found the following file was missing in sites folder. added this file
echo "demo.1" > currentsite.txt

After addeing the currentsite.txt file under "/frappe-demo/sites/"
was able to run
bench install-app erpnext
