### ISSUE TITLE
error bench start

### ISSUE THREAD

**Issue by moustfaAyad** [frappe/bench#22]
command   bench start  cause error:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/fourmax/bench/bench/cli.py", line 24, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 767, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(_args, **kwargs)
  File "/home/fourmax/bench/bench/cli.py", line 97, in start
    _start()
  File "/home/fourmax/bench/bench/utils.py", line 157, in start
    raise Exception("No process manager found")
Exception: No process manager found

**Comment by akinwale-habibullah** [comment]
This error message: Exception("No process manager found") only means you dont have a process manager installed. Frappe uses either of this three foreman, forego, honcho. 
If you any installed but.seeing this error message, add the path to system path in ,/etc/paths and then restart the computer

**Comment by bbeninal898-arch** [comment]
> This error message: Exception("No process manager found") only means you dont have a process manager installed. Frappe uses either of this three foreman, forego, honcho. If you any installed but.seeing this error message, add the path to system path in ,/etc/paths and then restart the computer



install follwing commands:(ubutu)
1.pipx install honcho
2.which honcho
3. you will see home directory it will be installed
4.bench start
