### ISSUE TITLE
Error while installing EPRNext on Ubuntu 14.04

### ISSUE THREAD

**Issue by mehtapawan007** [frappe/bench#238]
Hi,

I tried the steps mentioned at https://github.com/frappe/bench#beta-development-setup  for installation of ERPNext development environment and ran into the below error:
 Can someone help?

ERROR! Unexpected Exception: (setuptools 3.3 (/usr/lib/python2.7/dist-packaes), Requirement.parse('setuptools>=11.3'))
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 73, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 30, in <module>
    from ansible.executor.playbook_executor import PlaybookExecutor
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 27, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 32, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'))
Traceback (most recent call last):
  File "install.py", line 261, in <module>
    install_bench(args)
  File "install.py", line 76, in install_bench
    run_playbook('develop/create_user.yml', extra_vars=extra_vars)
  File "install.py", line 214, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(tmp_bench_repo, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'develop/create_user.yml', '-e', '@/tmp/extra_vars.json']' returned non-zero exit status 250
pawan@Pawan-LP01:~$

**Comment by yashodhank** [comment]
Please install curl on your machine, before running the script install.py

**Comment by vjFaLk** [comment]
@yashodhank Pawan is actually a Frappe employee, hehe, we've fixed his issue. @mehtapawan007 Can you close this?

**Comment by yashodhank** [comment]
@vjFaLk Well, Thanks and good to know that we have 007 now! :) @mehtapawan007

**Comment by rmehta** [comment]
@yashodhank would be happy to give you issue access on this if you are interested and can spend sometime. Will add you as an outside collaborator and give you write access. Let me know 😄

**Comment by vjFaLk** [comment]
@yashodhank That's huge dude, even I don't have write access 😜

**Comment by yashodhank** [comment]
@rmehta I am not sure how much time I will able to dedicate on regular basis, but I really appreciate your offer and if you think I may be of any help to the team and community. I am already in! 😃 👍 

@vjFaLk 💃 😄 Thanks
