### ISSUE TITLE
setup fails on ubuntu 14.04

### ISSUE THREAD

**Issue by sbkolate** [frappe/bench#272]
I am testing v7, but unable to install v7 production on ubuntu 14.04

```

[WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create user] *************************************************************
ok: [localhost]

TASK [Set home folder perms] ***************************************************
ok: [localhost]

TASK [Set home folder perms] ***************************************************
skipping: [localhost]

TASK [Set /tmp/.bench folder perms] ********************************************
changed: [localhost]
 [WARNING]: Consider using file module with owner rather than running chown


PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0

Please enter mysql root password:
Re-enter mysql root password:
Please enter Administrator password:
Re-enter Administrator password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
skipping: [localhost] => (item=cmake)
skipping: [localhost] => (item=redis)
skipping: [localhost] => (item=mariadb)
skipping: [localhost] => (item=nodejs)

TASK [cask installs] ***********************************************************
skipping: [localhost] => (item=wkhtmltopdf)

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
ok: [localhost] => (item=[u'build-essential', u'redis-server', u'software-properties-common', u'libxrender1', u'libxext6', u'xfonts-75dpi', u'xfonts-base', u'libjpeg8-dev', u'zlib1g-dev', u'libfreetype6-dev', u'liblcms2-dev', u'libwebp-dev', u'python-tk'])

TASK [install pillow prerequisites for Ubuntu < 14.04] *************************
skipping: [localhost] => (item=[])

TASK [install pillow prerequisites for Ubuntu >= 14.04] ************************
ok: [localhost] => (item=[u'libtiff5-dev', u'tcl8.6-dev', u'tk8.6-dev'])

TASK [Add nodejs v5 repo] ******************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "curl -sL https://deb.nodesource.com/setup_5.x", "delta": "0:00:00.005364", "end": "2016-07-25 19:48:43.484806", "failed": true, "rc": 127, "start": "2016-07-25 19:48:43.479442", "stderr": "/bin/bash: curl: command not found", "stdout": "", "stdout_lines": [], "warnings": ["Consider using get_url module rather than running curl"]}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 264, in <module>
    install_bench(args)
  File "install.py", line 99, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 217, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(tmp_bench_repo, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```

**Comment by vjFaLk** [comment]
@shreyasp Have a look when you can

**Comment by shreyasp** [comment]
@sbkolate Please install curl on your machine, before running the script `install.py`
