### ISSUE TITLE
error in bench SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by ccfiel** [frappe/bench#273]
I did a bench update today using master. I got this error 

```
 create mode 100644 bench/patches/v4/update_node.py
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/chris/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/.bench/bench/commands/update.py", line 30, in update
    patches.run(bench_path='.')
  File "/home/chris/.bench/bench/patches/__init__.py", line 19, in run
    module = importlib.import_module(patch.split()[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/chris/.bench/bench/patches/v4/update_node.py", line 22
    'Installation instructions for CentOS and Ubuntu can be found on the following link,\n
                                                                                         ^
SyntaxError: EOL while scanning string literal

```

**Comment by rmehta** [comment]
Thanks fixed!
