### ISSUE TITLE
Ubuntu 16.04 LTS - Exception: Please run this script as a non-root user with sudo privileges, but without using sudo or pass --user=USER

### ISSUE THREAD

**Issue by yashodhank** [frappe/bench#286]
Fresh Ubuntu 16.04 LTS
Comes preloaded with python3 and no python2.7
So installed `sudo apt-get install python2.7 python2.7-dev` then continued bench setup.
```
$ sudo python2.7 install.py --develop
```

Error Log:
```
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from ansible==2.0.2.0)
Collecting pycrypto>=2.6 (from ansible==2.0.2.0)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 2.6MB/s 
Collecting pyasn1>=0.1.7 (from paramiko->ansible==2.0.2.0)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cryptography>=1.1 (from paramiko->ansible==2.0.2.0)
  Downloading cryptography-1.4.tar.gz (399kB)
    100% |████████████████████████████████| 409kB 2.9MB/s 
Collecting MarkupSafe (from jinja2->ansible==2.0.2.0)
  Downloading MarkupSafe-0.23.tar.gz
Collecting idna>=2.0 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading idna-2.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 9.0MB/s 
Collecting six>=1.4.1 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl (383kB)
    100% |████████████████████████████████| 389kB 2.8MB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible==2.0.2.0)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 4.9MB/s 
Building wheels for collected packages: ansible, PyYAML, pycrypto, cryptography, MarkupSafe, pycparser
  Running setup.py bdist_wheel for ansible ... done
  Stored in directory: /root/.cache/pip/wheels/7a/56/e4/5dbcf0564a8cad5175b8c85bb123fdc81ad48bd31d27ac6011
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/4a/bf/14/d79994d19a59d4f73efdafb8682961f582d45ed6b459420346
  Running setup.py bdist_wheel for pycrypto ... done
  Stored in directory: /root/.cache/pip/wheels/80/1f/94/f76e9746864f198eb0e304aeec319159fa41b082f61281ffce
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /root/.cache/pip/wheels/f6/6c/21/11ec069285a52d7fa8c735be5fc2edfb8b24012c0f78f93d20
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
Successfully built ansible PyYAML pycrypto cryptography MarkupSafe pycparser
Installing collected packages: pyasn1, idna, six, enum34, ipaddress, pycparser, cffi, cryptography, paramiko, MarkupSafe, jinja2, PyYAML, pycrypto, ansible
Successfully installed MarkupSafe-0.23 PyYAML-3.11 ansible-2.0.2.0 cffi-1.7.0 cryptography-1.4 enum34-1.1.6 idna-2.1 ipaddress-1.0.16 jinja2-2.8 paramiko-2.0.2 pyasn1-0.1.9 pycparser-2.14 pycrypto-2.6.1 six-1.10.0
Cloning into '/tmp/.bench'...
remote: Counting objects: 227, done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 227 (delta 5), reused 165 (delta 4), pack-reused 0
Receiving objects: 100% (227/227), 7.06 MiB | 2.54 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "install.py", line 319, in <module>
    install_bench(args)
  File "install.py", line 85, in install_bench
    raise Exception('Please run this script as a non-root user with sudo privileges, but without using sudo or pass --user=USER')
Exception: Please run this script as a non-root user with sudo privileges, but without using sudo or pass --user=USER
```

**Comment by yashodhank** [comment]
My bad, clearly ignored `sudo python install.py --develop --user frappe` and fired command as `root`
Closing.
