### ISSUE TITLE
CentOS 7 - Production Installation Issue (Fresh Setup)

### ISSUE THREAD

**Issue by Prashanth-Murthy** [frappe/bench#289]
Hi,

I'm trying to install ERPNext on production mode using following machine

Server: HP 380 DL
RAM: 4 GB
Processor: Xeon Quad Core

Most of the activities went without any errors, but during Install ERPNext App stage i'm getting the following error ...
```
TASK [Install erpnext app] *****************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "--site", "site1.local", "install-app", "erpnext"], "delta": "0:00:02.218924", "end": "2016-08-05 08:23:41.384855", "failed": true, "rc": 1, "start": "2016-08-05 08:23:39.165931", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 79, in <module>\n    main()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 16, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 716, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 696, in main\n    rv = self.invoke(ctx)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 1060, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 1060, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 889, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 534, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py\", line 24, in _func\n    ret = f(frappe._dict(ctx.obj), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 146, in install_app\n    _install_app(app, verbose=context.verbose)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/installer.py\", line 99, in install_app\n    frappe.clear_cache()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 466, in clear_cache\n    for fn in get_hooks(\"clear_cache\"):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 771, in get_hooks\n    hooks = _dict(cache().get_value(\"app_hooks\", load_app_hooks))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 68, in get_value\n    val = generator()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 749, in load_app_hooks\n    for app in [app_name] if app_name else get_installed_apps(sort=True):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 713, in get_installed_apps\n    installed = json.loads(db.get_global(\"installed_apps\") or \"[]\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 655, in get_global\n    return self.get_default(key, user)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 667, in get_default\n    d = self.get_defaults(key, parent)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 673, in get_defaults\n    defaults = frappe.defaults.get_defaults(parent)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/defaults.py\", line 72, in get_defaults\n    globald = get_defaults_for()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/defaults.py\", line 179, in get_defaults_for\n    where parent = %s order by creation\"\"\", (parent,), as_dict=1)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 106, in sql\n    self.connect()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 52, in connect\n    use_unicode=True, charset='utf8')\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py\", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py\", line 193, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\n_mysql_exceptions.OperationalError: (1045, \"Access denied for user '1bd3e0294d'@'localhost' (using password: YES)\")", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=42   changed=8    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 342, in <module>
    install_bench(args)
  File "install.py", line 111, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 292, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```
Can some one please help me out resolving this issue !

PS: I'm able to install ERPNext with Development mode flawlessly ! also i'm using the .py script for installation.

Following is the complete log ...
```
"
[prashanth@localhost ~]$ sudo python install.py --production
[sudo] password for prashanth:
Loaded plugins: fastestmirror
Repository mariadb is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: ftp.iitm.ac.in
 * epel: ftp.riken.jp
 * extras: ftp.iitm.ac.in
 * updates: ftp.iitm.ac.in
Maybe run: yum groups mark install (see man yum)
No packages in any requested group available to install or update
Loaded plugins: fastestmirror
Repository mariadb is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: ftp.iitm.ac.in
 * epel: epel.mirror.net.in
 * extras: ftp.iitm.ac.in
 * updates: ftp.iitm.ac.in
Package epel-release-7-7.noarch already installed and latest version
Package redhat-lsb-core-4.1-27.el7.centos.1.x86_64 already installed and latest version
Package git-1.8.3.1-6.el7_2.1.x86_64 already installed and latest version
Package python-setuptools-0.9.8-4.el7.noarch already installed and latest version
Package python-devel-2.7.5-34.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.1e-51.el7_2.5.x86_64 already installed and latest version
Package libffi-devel-3.0.13-16.el7.x86_64 already installed and latest version
Nothing to do
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): ansible==2.0.2.0 in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/lib/python2.7/site-packages (from ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/lib64/python2.7/site-packages (from ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.7/site-packages (from ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/lib64/python2.7/site-packages (from ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/lib64/python2.7/site-packages (from paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/lib64/python2.7/site-packages (from jinja2->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible==2.0.2.0)
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create user] *************************************************************
ok: [localhost]

TASK [Set home folder perms] ***************************************************
ok: [localhost]

TASK [Set home folder perms] ***************************************************
skipping: [localhost]

TASK [Set /tmp/.bench folder perms] ********************************************
changed: [localhost]
 [WARNING]: Consider using file module with owner rather than running chown


PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0

Please enter mysql root password:
Re-enter mysql root password:
Please enter Administrator password:
Re-enter Administrator password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
skipping: [localhost] => (item=cmake)
skipping: [localhost] => (item=redis)
skipping: [localhost] => (item=mariadb)
skipping: [localhost] => (item=nodejs)

TASK [cask installs] ***********************************************************
skipping: [localhost] => (item=wkhtmltopdf)

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
skipping: [localhost] => (item=[])

TASK [install pillow prerequisites for Ubuntu < 14.04] *************************
skipping: [localhost] => (item=[])

TASK [install pillow prerequisites for Ubuntu >= 14.04] ************************
skipping: [localhost] => (item=[])

TASK [Get nodejs 6.x bash script] **********************************************
skipping: [localhost]

TASK [Run nodejs bash script] **************************************************
skipping: [localhost]

TASK [Install nodejs 6.x] ******************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [development tools package] ***********************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
skipping: [localhost] => (item=[u'redis', u'mysql-devel', u'mysql-libs', u'libXrender', u'libXext', u'xorg-x11-fonts-75dpi', u'xorg-x11-fonts-Type1', u'libjpeg-devel', u'zlib-devel', u'libzip-devel', u'freetype-devel', u'lcms2-devel', u'libwebp-devel', u'libtiff-devel', u'tcl-devel', u'tk-devel'])

TASK [Get nodejs 6.x bash script] **********************************************
ok: [localhost]

TASK [Run nodejs 6.x bash script] **********************************************
changed: [localhost]

TASK [Install nodejs] **********************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /tmp/.bench/playbooks/develop/includes/mariadb_centos.yml for localhost

TASK [Add repository] **********************************************************
ok: [localhost]

TASK [Install MariaDB] *********************************************************
skipping: [localhost] => (item=[u'MariaDB-server', u'MariaDB-client'])

TASK [include] *****************************************************************
included: /tmp/.bench/playbooks/develop/includes/wkhtmltopdf_centos.yml for localhost

TASK [Download wkhtmltopdf] ****************************************************
ok: [localhost]

TASK [Install wkhtmltopdf deb] *************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /tmp/.bench/playbooks/develop/includes/setup_mariadb.yml for localhost

TASK [Install MySQLdb in global env] *******************************************
ok: [localhost]

TASK [Add configuration] *******************************************************
ok: [localhost]

TASK [restart mysql linux] *****************************************************
changed: [localhost]

TASK [Set root Password] *******************************************************
changed: [localhost]

TASK [add launchagents folder mac] *********************************************
skipping: [localhost]

TASK [add mysql to mac startup] ************************************************
skipping: [localhost]

TASK [stop mysql mac] **********************************************************
skipping: [localhost]

TASK [start mysql mac] *********************************************************
skipping: [localhost]

TASK [include] *****************************************************************
included: /tmp/.bench/playbooks/develop/includes/setup_bench.yml for localhost

TASK [Check if /tmp/.bench exists] *********************************************
ok: [localhost]

TASK [Check if bench_repo_path exists] *****************************************
ok: [localhost]

TASK [move /tmp/.bench if it exists] *******************************************
skipping: [localhost]

TASK [install bench] ***********************************************************
changed: [localhost]

TASK [Check whether bench exists] **********************************************
ok: [localhost]

TASK [init bench] **************************************************************
skipping: [localhost]

TASK [setup config] ************************************************************
ok: [localhost]

TASK [install frappe app] ******************************************************
ok: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add dotdeb apt repository key for Debian < 8] ****************************
skipping: [localhost]

TASK [Add dotdeb apt repository for redis-server for Debian < 8] ***************
skipping: [localhost]

TASK [install prequisites] *****************************************************
skipping: [localhost] => (item=[])

TASK [install pillow prerequisites for Debian < 8] *****************************
skipping: [localhost] => (item=[])

TASK [install pillow prerequisites for Debian >= 8] ****************************
skipping: [localhost] => (item=[])

TASK [Get nodejs 6.x bash script] **********************************************
skipping: [localhost]

TASK [Run nodejs bash script] **************************************************
skipping: [localhost]

TASK [Install nodejs 6.x] ******************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add nginx apt repository key for Debian < 8] *****************************
skipping: [localhost]

TASK [Add nginx apt repository for Debian < 8] *********************************
skipping: [localhost]

TASK [Install production pre-requisites] ***************************************
skipping: [localhost] => (item=[])

TASK [Install production pre-requisites] ***************************************
skipping: [localhost] => (item=[u'nginx', u'screen', u'vim', u'htop', u'git', u'postfix', u'MySQL-python'])

TASK [Install supervisor using yum for Centos 7] *******************************
ok: [localhost]

TASK [Rename default nginx.conf to nginx.conf.old] *****************************
changed: [localhost]

TASK [Copy the nginx_config template] ******************************************
changed: [localhost]

TASK [Reload the nginx service] ************************************************
changed: [localhost]

TASK [Enable nginx, mysql, and redis] ******************************************
ok: [localhost] => (item=nginx)
ok: [localhost] => (item=mysql)

TASK [Enable redis.service on centos] ******************************************
ok: [localhost]

TASK [Enable redis-server.service on ubuntu] ***********************************
skipping: [localhost]

TASK [Check whether default supervisor.conf exists] ****************************
ok: [localhost]

TASK [Check whether default supervisor.conf exists] ****************************
skipping: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Check whether a site exists] *********************************************
ok: [localhost]

TASK [Create new site] *********************************************************
skipping: [localhost]

TASK [Check ERPNext App exists] ************************************************
ok: [localhost]

TASK [Get-app erpnext app] *****************************************************
changed: [localhost]

TASK [Install erpnext app] *****************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "--site", "site1.local", "install-app", "erpnext"], "delta": "0:00:02.218924", "end": "2016-08-05 08:23:41.384855", "failed": true, "rc": 1, "start": "2016-08-05 08:23:39.165931", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 79, in <module>\n    main()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 16, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 716, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 696, in main\n    rv = self.invoke(ctx)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 1060, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 1060, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 889, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py\", line 534, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py\", line 24, in _func\n    ret = f(frappe._dict(ctx.obj), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 146, in install_app\n    _install_app(app, verbose=context.verbose)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/installer.py\", line 99, in install_app\n    frappe.clear_cache()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 466, in clear_cache\n    for fn in get_hooks(\"clear_cache\"):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 771, in get_hooks\n    hooks = _dict(cache().get_value(\"app_hooks\", load_app_hooks))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 68, in get_value\n    val = generator()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 749, in load_app_hooks\n    for app in [app_name] if app_name else get_installed_apps(sort=True):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 713, in get_installed_apps\n    installed = json.loads(db.get_global(\"installed_apps\") or \"[]\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 655, in get_global\n    return self.get_default(key, user)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 667, in get_default\n    d = self.get_defaults(key, parent)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 673, in get_defaults\n    defaults = frappe.defaults.get_defaults(parent)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/defaults.py\", line 72, in get_defaults\n    globald = get_defaults_for()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/defaults.py\", line 179, in get_defaults_for\n    where parent = %s order by creation\"\"\", (parent,), as_dict=1)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 106, in sql\n    self.connect()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 52, in connect\n    use_unicode=True, charset='utf8')\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py\", line 81, in Connect\n    return Connection(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py\", line 193, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\n_mysql_exceptions.OperationalError: (1045, \"Access denied for user '1bd3e0294d'@'localhost' (using password: YES)\")", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=42   changed=8    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 342, in <module>
    install_bench(args)
  File "install.py", line 111, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 292, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```
Regards,
Prashanth

**Comment by vjFaLk** [comment]
@Prashanth-Murthy Can you try reinstalling _fresh_ again? We have recently made changes and fixes!

**Comment by Prashanth-Murthy** [comment]
Sure, will try and let you know the results on this thread.

Thanks,
Prashanth

**Comment by Prashanth-Murthy** [comment]
P.S: I have downloaded this script on 4th-Aug-2016, i did not see any commits to .py file from long time !

Any case will let you know.

**Comment by Prashanth-Murthy** [comment]
@vjFaLk , getting the same error again ! can you suggest any workaround or a fix for this ?

**Comment by vjFaLk** [comment]
Ah, that is not good. Let me see if I can reproduce this and fix.

**Comment by Prashanth-Murthy** [comment]
Let me fill you in what exactly i did ...

1. Created a VM with Cent OS 7 (64 Bit) with 4 GB RAM
2. Updated Cent OS with Update & Upgrade
3. Installed net-tools
4. Installed libselinux-python openssh-server openssh-client python wget -y

Downloaded "https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py"

Ran : sudo python install.py --production

Note: In some situation we might need to reset the root password for mysql so that Installer can update the password !

Regards,
Prashanth

**Comment by yashodhank** [comment]
@Prashanth-Murthy  also post following when you prepare your os soon before installing ERPNext.
using `$ yum list installed | less`

**Comment by vjFaLk** [comment]
Hmm, so I'm unable to reproduce this on a Digital Ocean CentOS 7 droplet. Could you link me to the OS image you are creating a VM from?

**Comment by Prashanth-Murthy** [comment]
This is a direct download from Cent OS website ...
File name is "CentOS-7-x86_64-Minimal-1511.iso"

**Comment by Prashanth-Murthy** [comment]
@yashodhank i'm running the installer as a non root user (but has the admin privilege - can sudo)

**Comment by yashodhank** [comment]
@Prashanth-Murthy Thanks, Downloaded Image and trying setup now using VirtualBox V5.0.26
@vjFaLk I will post results shortly. I am on it.

**Comment by Prashanth-Murthy** [comment]
Thanks Guys, really appreciate your help

**Comment by Prashanth-Murthy** [comment]
Guys, was able to install with out any errors during my latest iteration, if i'm able to pin the issue or find any errors will post the details.

Meanwhile, after completing the setup, i tried the following command to test the system and getting following error ...

[frappe@localhost frappe-bench]$ curl -I http://localhost:8000
HTTP/1.1 404 NOT FOUND
Server: gunicorn/19.6.0
Date: Thu, 04 Aug 2016 12:12:54 GMT
Connection: close
Content-Type: text/html
Content-Length: 155

And i'm not able to access the ERPNext from my host browser with the IP 8000 ...
I'm using NAT and my URL is "http://192.168.146.135:8000" and i'm getting the 404 error

Can you guys direct me to the solution ? i have checked all the services and logs only error i found in the log is  ....

IncorrectSitePath: 404: Not Found
[2016-08-04 17:35:20 +0000] [3059] [INFO] Starting gunicorn 19.6.0
[2016-08-04 17:35:20 +0000] [3059] [INFO] Listening at: http://127.0.0.1:8000 (3059)
[2016-08-04 17:35:20 +0000] [3059] [INFO] Using worker: sync
[2016-08-04 17:35:20 +0000] [3120] [INFO] Booting worker with pid: 3120
[2016-08-04 17:35:55 +0000] [3149] [INFO] Starting gunicorn 19.6.0
[2016-08-04 17:35:55 +0000] [3149] [INFO] Listening at: http://127.0.0.1:8000 (3149)
[2016-08-04 17:35:55 +0000] [3149] [INFO] Using worker: sync
[2016-08-04 17:35:55 +0000] [3210] [INFO] Booting worker with pid: 3210
[2016-08-04 17:40:52 +0000] [3149] [INFO] Handling signal: term
[2016-08-04 17:40:52 +0000] [3210] [INFO] Worker exiting (pid: 3210)
[2016-08-04 17:40:52 +0000] [3149] [INFO] Shutting down: Master
[2016-08-04 17:41:05 +0000] [3564] [INFO] Starting gunicorn 19.6.0
[2016-08-04 17:41:05 +0000] [3564] [INFO] Listening at: http://127.0.0.1:8000 (3564)
[2016-08-04 17:41:05 +0000] [3564] [INFO] Using worker: sync
[2016-08-04 17:41:05 +0000] [3598] [INFO] Booting worker with pid: 3598
2016-08-04 17:42:54,666 - /home/frappe/frappe-bench/apps/frappe/frappe/app.py [ERROR]:
Site: localhost
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 102, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 121, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 175, in get_site_config
    raise IncorrectSitePath, "{0} does not exist".format(site_config)
IncorrectSitePath: 404: Not Found

Thanks,
Prashanth

**Comment by vjFaLk** [comment]
Is your port forwarded from 80 to 8000? Is there a folder called 'site1.local' in the `frappe-bench/sites` folder? What did you change to be able to install properly?

**Comment by Prashanth-Murthy** [comment]
@vjFaLk 
1. Do i need to port forward in case of NAT ? if yes i'm not familiar, please let me know the process.
2. Yes and app's folder contains erpnext and frappe
3. No change in the process and i'm not able to explain the reasons, but installation went flawless this time, i have been trying the same process several times and was stuck at the same error ! just out of curiosity, were you guys able to simulate the error ?

**Comment by Prashanth-Murthy** [comment]
Also, how can i check application logs (or error logs) so that i can provide more information.

**Comment by rmehta** [comment]
@Prashanth-Murthy can we move this to the forum?

**Comment by yashodhank** [comment]
Follow up further discussion/troubleshooting > [discuss.erpnext.com](https://discuss.erpnext.com/t/error-while-accessing-production-environment-404/14777)
