### ISSUE TITLE
Better exception handling for OSError: [Errno 2] No such file or directory: './apps/frappe'

### ISSUE THREAD

**Issue by yashodhank** [frappe/bench#292]
Bench throws errors which is confusing for new users who are dealing with `bench` tool for first time.
```
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 30, in update
    patches.run(bench_path='.')
  File "/home/frappe/.bench/bench/patches/__init__.py", line 21, in run
    result = execute(bench_path)
  File "/home/frappe/.bench/bench/patches/v3/celery_to_rq.py", line 7, in execute
    frappe_branch = get_current_branch('frappe', bench_path)
  File "/home/frappe/.bench/bench/app.py", line 179, in get_current_branch
    return get_cmd_output("basename $(git symbolic-ref -q HEAD)", cwd=repo_dir)
  File "/home/frappe/.bench/bench/utils.py", line 284, in get_cmd_output
    return subprocess.check_output(cmd, cwd=cwd, shell=True, stderr=open(os.devnull, 'wb')).strip()
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: './apps/frappe'
```
If we can pust few words about what whats wrong, it will be helpful to reduce number tickets on forum on github.

**Comment by shreyasp** [comment]
@yashodhank I presume you tried to run `bench update` while inside a folder which was not **root** bench folder `/home/frappe/frappe-bench` __(default)__

while patch attempts to find the `frappe` directory to pull some updates.

In such situations, I don't see what else we can tell a user to avoid the confusion.

**Comment by yashodhank** [comment]
@shreyasp Oh, if we dont have mechanism to handle this error and provide user friendly message, then it's better to close this request.
Thanks for your time and effort.

**Comment by strixaluco** [comment]
In regards to the topic's issue: what are the reasons/limits to not install `bench` somewhere to `/usr/local/bin` (PATH default), hence avoiding launching it from `/frappe-bench` only?
