### ISSUE TITLE
Error with bench updated and frappe and erpnext in v6

### ISSUE THREAD

**Issue by MaxMorais** [frappe/bench#303]
Hey, guys! I'm facing the below error while updating bench and using `frappe` and `erpnext` in the v6

```python
MySQL root password: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vagrant/frappe-bench-v6/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/vagrant/frappe-bench-v6/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vagrant/frappe-bench-v6/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/vagrant/frappe-bench-v6/apps/frappe/frappe/commands/site.py", line 26, in new_site
    
  File "/vagrant/frappe-bench-v6/apps/frappe/frappe/commands/site.py", line 69, in _new_site
    import __builtin__ as builtins
TypeError: coercing to Unicode: need string or buffer, bool found
``` 

Seens that something changed in the installation method from V6 to V7

**Comment by MaxMorais** [comment]
I found the issue!

Strangelly, after run the command `bench switch-branch v6.x.x` the git keep the folder commands with the .pyc files
