### ISSUE TITLE
Error while downloading import template

### ISSUE THREAD

**Issue by fransunf** [frappe/bench#305]
hi team,

when i'm trying to download the import item template i'm getting bellow error. please help to solve it.

Server Error
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/api.py", line 49, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/core/page/data_import_tool/exporter.py", line 261, in get_template
    build_field_columns(d)
  File "/home/frappe/benches/bench-2016-08-12/apps/frappe/frappe/core/page/data_import_tool/exporter.py", line 107, in build_field_columns
    tablerow[column_start_end[dt].start + 2] = doctype_parentfield[dt]
IndexError: list assignment index out of range

**Comment by rmehta** [comment]
@fransunf please raise these issues on the right repo. This is now fixed.
