### ISSUE TITLE
No module named bench.cli

### ISSUE THREAD

**Issue by ronnysugianto** [frappe/bench#320]
Hi, im trying to bench start my erpnext application. But always failed in return with this following message log "No module name bench.cli"

`Ronny-Sugiantos-MacBook:erpnext ronnysugianto$ bench start Traceback (most recent call last):
  
File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  
File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  
File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
 
 File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  
File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bench.cli

**Comment by vjFaLk** [comment]
Can you run `git status` in the .bench or bench-repo directory and tell me what you get?
