### ISSUE TITLE
Installation Failure Ubuntu 14.04 and 16.04 LTS

### ISSUE THREAD

**Issue by KaruguDev** [frappe/bench#336]
I have tried the installation three times with the same error message, The huge problem is that it has been marked [closed](https://github.com/frappe/bench/issues/313) with no solution provided and in discuss erpnext there is no answer to this problem

![image](https://cloud.githubusercontent.com/assets/9849488/19723749/5adf9536-9b85-11e6-9673-9cd091cc9cc0.png)

**Comment by shreyasp** [comment]
@paul-100 It would be great If you can run the command on a fresh server.

Execute: `python install.py --production --user frappe --verbose`

And post the complete traceback so that whomsoever tries to resolve your problem is aware of the failure, as this screenshot just tells that you are facing some issue while installing the bench.

**Comment by paul-100** [comment]
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"append": false, "comment": null, "createhome": true, "expires": null, "force": false, "generate_ssh_key": true, "group": null, "groups": null, "home": null, "login_class": null, "move_home": false, "name": "frappe", "non_unique": false, "password": null, "remove": false, "shell": null, "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on erpnext", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": false, "uid": null, "update_password": "always"}, "module_name": "user"}, "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", "name": "frappe", "rc": 1}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @develop/create_user.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 351, in <module>
    install_bench(args)
  File "install.py", line 98, in install_bench
    run_playbook('develop/create_user.yml', extra_vars=extra_vars)
  File "install.py", line 301, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'develop/create_user.yml', '-e', '@/tmp/extra_vars.json', '-vvvv']' returned non-zero exit status 2

**Comment by paul-100** [comment]
this is the output using sudo

```
failed: [localhost] (item=[u'nginx', u'screen', u'vim', u'htop', u'git', u'postf                                                                                        ix', u'supervisor']) => {"cache_update_time": 0, "cache_updated": false, "failed                                                                                        ": true, "invocation": {"module_args": {"cache_valid_time": null, "deb": null, "                                                                                        default_release": null, "dpkg_options": "force-confdef,force-confold", "force":                                                                                         false, "install_recommends": null, "name": ["nginx", "screen", "vim", "htop", "g                                                                                        it", "postfix", "supervisor"], "package": ["nginx", "screen", "vim", "htop", "gi                                                                                        t", "postfix", "supervisor"], "purge": false, "state": "present", "update_cache"                                                                                        : false, "upgrade": null}, "module_name": "apt"}, "item": ["nginx", "screen", "v                                                                                        im", "htop", "git", "postfix", "supervisor"], "msg": "'/usr/bin/apt-get -y -o \"                                                                                        Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   insta                                                                                        ll 'nginx' 'screen' 'vim' 'htop' 'postfix' 'supervisor'' failed: E: Sub-process                                                                                         /usr/bin/dpkg returned an error code (1)\n", "stderr": "E: Sub-process /usr/bin/                                                                                        dpkg returned an error code (1)\n", "stdout": "Reading package lists...\nBuildin                                                                                        g dependency tree...\nReading state information...\nThe following additional pac                                                                                        kages will be installed:\n  libgd3 libgpm2 libpython3.5 libvpx3 libxslt1.1 nginx                                                                                        -common nginx-core\n  python-meld3 ssl-cert vim-runtime\nSuggested packages:\n                                                                                          libgd-tools gpm fcgiwrap nginx-doc procmail postfix-mysql postfix-pgsql\n  postf                                                                                        ix-ldap postfix-pcre sasl2-bin dovecot-common postfix-cdb mail-reader\n  postfix                                                                                        -doc iselect | screenie | byobu openssl-blacklist supervisor-doc\n  ctags vim-do                                                                                        c vim-scripts vim-gnome-py2 | vim-gtk-py2 | vim-gtk3-py2\n  | vim-athena-py2 | v                                                                                        im-nox-py2\nThe following NEW packages will be installed:\n  htop libgd3 libgpm2                                                                                         libpython3.5 libvpx3 libxslt1.1 nginx nginx-common\n  nginx-core postfix python                                                                                        -meld3 screen ssl-cert supervisor vim vim-runtime\n0 upgraded, 16 newly installe                                                                                        d, 0 to remove and 2 not upgraded.\nNeed to get 11.1 MB of archives.\nAfter this                                                                                         operation, 45.9 MB of additional disk space will be used.\nGet:1 http://us.arch                                                                                        ive.ubuntu.com/ubuntu xenial/main amd64 libgpm2 amd64 1.20.4-6.1 [16.5 kB]\nGet:                                                                                        2 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 htop amd64 2                                                                                        .0.1-1ubuntu1 [76.4 kB]\nGet:3 http://us.archive.ubuntu.com/ubuntu xenial/main a                                                                                        md64 libvpx3 amd64 1.5.0-2ubuntu1 [732 kB]\nGet:4 http://us.archive.ubuntu.com/u                                                                                        buntu xenial-updates/main amd64 libgd3 amd64 2.1.1-4ubuntu0.16.04.3 [125 kB]\nGe                                                                                        t:5 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5 a                                                                                        md64 3.5.2-2~16.04 [1359 kB]\nGet:6 http://us.archive.ubuntu.com/ubuntu xenial/m                                                                                        ain amd64 libxslt1.1 amd64 1.1.28-2.1 [145 kB]\nGet:7 http://us.archive.ubuntu.c                                                                                        om/ubuntu xenial-updates/main amd64 nginx-common all 1.10.0-0ubuntu0.16.04.3 [26                                                                                        .9 kB]\nGet:8 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ngin                                                                                        x-core amd64 1.10.0-0ubuntu0.16.04.3 [428 kB]\nGet:9 http://us.archive.ubuntu.co                                                                                        m/ubuntu xenial-updates/main amd64 nginx all 1.10.0-0ubuntu0.16.04.3 [3496 B]\nG                                                                                        et:10 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 ssl-cert all 1.0.37                                                                                         [16.9 kB]\nGet:11 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 postfix                                                                                         amd64 3.1.0-3 [1152 kB]\nGet:12 http://us.archive.ubuntu.com/ubuntu xenial/main                                                                                         amd64 screen amd64 4.3.1-2build1 [560 kB]\nGet:13 http://us.archive.ubuntu.com/u                                                                                        buntu xenial-updates/main amd64 vim-runtime all 2:7.4.1689-3ubuntu1.1 [5174 kB]\                                                                                        nGet:14 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 vim amd64                                                                                         2:7.4.1689-3ubuntu1.1 [1036 kB]\nGet:15 http://us.archive.ubuntu.com/ubuntu xeni                                                                                        al/universe amd64 python-meld3 all 1.0.2-2 [30.9 kB]\nGet:16 http://us.archive.u                                                                                        buntu.com/ubuntu xenial/universe amd64 supervisor all 3.2.0-2 [252 kB]\nPreconfi                                                                                        guring packages ...\nFetched 11.1 MB in 53s (209 kB/s)\nSelecting previously uns                                                                                        elected package libgpm2:amd64.\r\n(Reading database ... \r(Reading database ...                                                                                         5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ...                                                                                         20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ...                                                                                         35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ..                                                                                        . 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database .                                                                                        .. 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database                                                                                         ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database                                                                                         ... 95%\r(Reading database ... 100%\r(Reading database ... 75859 files and dire                                                                                        ctories currently installed.)\r\nPreparing to unpack .../libgpm2_1.20.4-6.1_amd6                                                                                        4.deb ...\r\nUnpacking libgpm2:amd64 (1.20.4-6.1) ...\r\nSelecting previously un                                                                                        selected package htop.\r\nPreparing to unpack .../htop_2.0.1-1ubuntu1_amd64.deb                                                                                         ...\r\nUnpacking htop (2.0.1-1ubuntu1) ...\r\nSelecting previously unselected pa                                                                                        ckage libvpx3:amd64.\r\nPreparing to unpack .../libvpx3_1.5.0-2ubuntu1_amd64.deb                                                                                         ...\r\nUnpacking libvpx3:amd64 (1.5.0-2ubuntu1) ...\r\nSelecting previously uns                                                                                        elected package libgd3:amd64.\r\nPreparing to unpack .../libgd3_2.1.1-4ubuntu0.1                                                                                        6.04.3_amd64.deb ...\r\nUnpacking libgd3:amd64 (2.1.1-4ubuntu0.16.04.3) ...\r\nS                                                                                        electing previously unselected package libpython3.5:amd64.\r\nPreparing to unpac                                                                                        k .../libpython3.5_3.5.2-2~16.04_amd64.deb ...\r\nUnpacking libpython3.5:amd64 (                                                                                        3.5.2-2~16.04) ...\r\nSelecting previously unselected package libxslt1.1:amd64.\                                                                                        r\nPreparing to unpack .../libxslt1.1_1.1.28-2.1_amd64.deb ...\r\nUnpacking libx                                                                                        slt1.1:amd64 (1.1.28-2.1) ...\r\nSelecting previously unselected package nginx-c                                                                                        ommon.\r\nPreparing to unpack .../nginx-common_1.10.0-0ubuntu0.16.04.3_all.deb .                                                                                        ..\r\nUnpacking nginx-common (1.10.0-0ubuntu0.16.04.3) ...\r\nSelecting previous                                                                                        ly unselected package nginx-core.\r\nPreparing to unpack .../nginx-core_1.10.0-0                                                                                        ubuntu0.16.04.3_amd64.deb ...\r\nUnpacking nginx-core (1.10.0-0ubuntu0.16.04.3)                                                                                         ...\r\nSelecting previously unselected package nginx.\r\nPreparing to unpack ...                                                                                        /nginx_1.10.0-0ubuntu0.16.04.3_all.deb ...\r\nUnpacking nginx (1.10.0-0ubuntu0.1                                                                                        6.04.3) ...\r\nSelecting previously unselected package ssl-cert.\r\nPreparing to                                                                                         unpack .../ssl-cert_1.0.37_all.deb ...\r\nUnpacking ssl-cert (1.0.37) ...\r\nSe                                                                                        lecting previously unselected package postfix.\r\nPreparing to unpack .../postfi                                                                                        x_3.1.0-3_amd64.deb ...\r\nUnpacking postfix (3.1.0-3) ...\r\nSelecting previous                                                                                        ly unselected package screen.\r\nPreparing to unpack .../screen_4.3.1-2build1_am                                                                                        d64.deb ...\r\nUnpacking screen (4.3.1-2build1) ...\r\nSelecting previously unse                                                                                        lected package vim-runtime.\r\nPreparing to unpack .../vim-runtime_2%3a7.4.1689-                                                                                        3ubuntu1.1_all.deb ...\r\nAdding 'diversion of /usr/share/vim/vim74/doc/help.txt                                                                                         to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'\r\nAdding 'divers                                                                                        ion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny b                                                                                        y vim-runtime'\r\nUnpacking vim-runtime (2:7.4.1689-3ubuntu1.1) ...\r\nSelecting                                                                                         previously unselected package vim.\r\nPreparing to unpack .../vim_2%3a7.4.1689-                                                                                        3ubuntu1.1_amd64.deb ...\r\nUnpacking vim (2:7.4.1689-3ubuntu1.1) ...\r\nSelecti                                                                                        ng previously unselected package python-meld3.\r\nPreparing to unpack .../python                                                                                        -meld3_1.0.2-2_all.deb ...\r\nUnpacking python-meld3 (1.0.2-2) ...\r\nSelecting                                                                                         previously unselected package supervisor.\r\nPreparing to unpack .../supervisor_                                                                                        3.2.0-2_all.deb ...\r\nUnpacking supervisor (3.2.0-2) ...\r\nProcessing triggers                                                                                         for mime-support (3.59ubuntu1) ...\r\nProcessing triggers for man-db (2.7.5-1)                                                                                         ...\r\nProcessing triggers for libc-bin (2.23-0ubuntu4) ...\r\nProcessing trigge                                                                                        rs for systemd (229-4ubuntu11) ...\r\nProcessing triggers for ureadahead (0.100.                                                                                        0-19) ...\r\nProcessing triggers for ufw (0.35-0ubuntu2) ...\r\nProcessing trigg                                                                                        ers for install-info (6.1.0.dfsg.1-5) ...\r\nSetting up libgpm2:amd64 (1.20.4-6.                                                                                        1) ...\r\nSetting up htop (2.0.1-1ubuntu1) ...\r\nSetting up libvpx3:amd64 (1.5.                                                                                        0-2ubuntu1) ...\r\nSetting up libgd3:amd64 (2.1.1-4ubuntu0.16.04.3) ...\r\nSetti                                                                                        ng up libpython3.5:amd64 (3.5.2-2~16.04) ...\r\nSetting up libxslt1.1:amd64 (1.1                                                                                        .28-2.1) ...\r\nSetting up nginx-common (1.10.0-0ubuntu0.16.04.3) ...\r\nSetting                                                                                         up nginx-core (1.10.0-0ubuntu0.16.04.3) ...\r\nSetting up nginx (1.10.0-0ubuntu                                                                                        0.16.04.3) ...\r\nSetting up ssl-cert (1.0.37) ...\r\nSetting up postfix (3.1.0-                                                                                        3) ...\r\nAdding group `postfix' (GID 119) ...\r\nDone.\r\nAdding system user `p                                                                                        ostfix' (UID 111) ...\r\nAdding new user `postfix' (UID 111) with group `postfix                                                                                        ' ...\r\nNot creating home directory `/var/spool/postfix'.\r\nCreating /etc/post                                                                                        fix/dynamicmaps.cf\r\nAdding group `postdrop' (GID 120) ...\r\nDone.\r\nsetting                                                                                         myhostname: erpnext.168.4.123\r\nsetting alias maps\r\nsetting alias database\r\                                                                                        nchanging /etc/mailname to erpnext.168.4.123\r\nsetting myorigin\r\nsetting dest                                                                                        inations: $myhostname, erpnext.168.4.123, localhost.168.4.123, , localhost\r\nse                                                                                        tting relayhost: \r\nsetting mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1                                                                                        ]/128\r\nsetting mailbox_size_limit: 0\r\nsetting recipient_delimiter: +\r\nsett                                                                                        ing inet_interfaces: all\r\nsetting inet_protocols: all\r\n/etc/aliases does not                                                                                         exist, creating it.\r\nWARNING: /etc/aliases exists, but does not have a root a                                                                                        lias.\r\n\r\nPostfix is now set up with a default configuration.  If you need to                                                                                         make \r\nchanges, edit\r\n/etc/postfix/main.cf (and others) as needed.  To view                                                                                         Postfix configuration\r\nvalues, see postconf(1).\r\n\r\nAfter modifying main.c                                                                                        f, be sure to run '/etc/init.d/postfix reload'.\r\n\r\nRunning newaliases\r\nnew                                                                                        aliases: warning: valid_hostname: numeric hostname: 168.4.123\r\nnewaliases: fat                                                                                        al: file /etc/postfix/main.cf: parameter mydomain: bad parameter value: 168.4.12                                                                                        3\r\ndpkg: error processing package postfix (--configure):\r\n subprocess instal                                                                                        led post-installation script returned error exit status 75\r\nSetting up screen                                                                                         (4.3.1-2build1) ...\r\nSetting up vim-runtime (2:7.4.1689-3ubuntu1.1) ...\r\nSet                                                                                        ting up vim (2:7.4.1689-3ubuntu1.1) ...\r\nupdate-alternatives: using /usr/bin/v                                                                                        im.basic to provide /usr/bin/vim (vim) in auto mode\r\nupdate-alternatives: usin                                                                                        g /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode\r\nupdat                                                                                        e-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto                                                                                         mode\r\nupdate-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview                                                                                         (rview) in auto mode\r\nupdate-alternatives: using /usr/bin/vim.basic to provid                                                                                        e /usr/bin/vi (vi) in auto mode\r\nupdate-alternatives: using /usr/bin/vim.basic                                                                                         to provide /usr/bin/view (view) in auto mode\r\nupdate-alternatives: using /usr                                                                                        /bin/vim.basic to provide /usr/bin/ex (ex) in auto mode\r\nSetting up python-mel                                                                                        d3 (1.0.2-2) ...\r\nSetting up supervisor (3.2.0-2) ...\r\nProcessing triggers f                                                                                        or libc-bin (2.23-0ubuntu4) ...\r\nProcessing triggers for systemd (229-4ubuntu1                                                                                        1) ...\r\nProcessing triggers for ureadahead (0.100.0-19) ...\r\nProcessing trig                                                                                        gers for ufw (0.35-0ubuntu2) ...\r\nErrors were encountered while processing:\r\                                                                                        n postfix\r\n", "stdout_lines": ["Reading package lists...", "Building dependenc                                                                                        y tree...", "Reading state information...", "The following additional packages w                                                                                        ill be installed:", "  libgd3 libgpm2 libpython3.5 libvpx3 libxslt1.1 nginx-comm                                                                                        on nginx-core", "  python-meld3 ssl-cert vim-runtime", "Suggested packages:", "                                                                                          libgd-tools gpm fcgiwrap nginx-doc procmail postfix-mysql postfix-pgsql", "  po                                                                                        stfix-ldap postfix-pcre sasl2-bin dovecot-common postfix-cdb mail-reader", "  po                                                                                        stfix-doc iselect | screenie | byobu openssl-blacklist supervisor-doc", "  ctags                                                                                         vim-doc vim-scripts vim-gnome-py2 | vim-gtk-py2 | vim-gtk3-py2", "  | vim-athen                                                                                        a-py2 | vim-nox-py2", "The following NEW packages will be installed:", "  htop l                                                                                        ibgd3 libgpm2 libpython3.5 libvpx3 libxslt1.1 nginx nginx-common", "  nginx-core                                                                                         postfix python-meld3 screen ssl-cert supervisor vim vim-runtime", "0 upgraded,                                                                                         16 newly installed, 0 to remove and 2 not upgraded.", "Need to get 11.1 MB of ar                                                                                        chives.", "After this operation, 45.9 MB of additional disk space will be used."                                                                                        , "Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libgpm2 amd64 1.2                                                                                        0.4-6.1 [16.5 kB]", "Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/un                                                                                        iverse amd64 htop amd64 2.0.1-1ubuntu1 [76.4 kB]", "Get:3 http://us.archive.ubun                                                                                        tu.com/ubuntu xenial/main amd64 libvpx3 amd64 1.5.0-2ubuntu1 [732 kB]", "Get:4 h                                                                                        ttp://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libgd3 amd64 2.1.1-                                                                                        4ubuntu0.16.04.3 [125 kB]", "Get:5 http://us.archive.ubuntu.com/ubuntu xenial-up                                                                                        dates/main amd64 libpython3.5 amd64 3.5.2-2~16.04 [1359 kB]", "Get:6 http://us.a                                                                                        rchive.ubuntu.com/ubuntu xenial/main amd64 libxslt1.1 amd64 1.1.28-2.1 [145 kB]"                                                                                        , "Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 nginx-com                                                                                        mon all 1.10.0-0ubuntu0.16.04.3 [26.9 kB]", "Get:8 http://us.archive.ubuntu.com/                                                                                        ubuntu xenial-updates/main amd64 nginx-core amd64 1.10.0-0ubuntu0.16.04.3 [428 k                                                                                        B]", "Get:9 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 nginx                                                                                         all 1.10.0-0ubuntu0.16.04.3 [3496 B]", "Get:10 http://us.archive.ubuntu.com/ubun                                                                                        tu xenial/main amd64 ssl-cert all 1.0.37 [16.9 kB]", "Get:11 http://us.archive.u                                                                                        buntu.com/ubuntu xenial/main amd64 postfix amd64 3.1.0-3 [1152 kB]", "Get:12 htt                                                                                        p://us.archive.ubuntu.com/ubuntu xenial/main amd64 screen amd64 4.3.1-2build1 [5                                                                                        60 kB]", "Get:13 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 v                                                                                        im-runtime all 2:7.4.1689-3ubuntu1.1 [5174 kB]", "Get:14 http://us.archive.ubunt                                                                                        u.com/ubuntu xenial-updates/main amd64 vim amd64 2:7.4.1689-3ubuntu1.1 [1036 kB]                                                                                        ", "Get:15 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 python-meld                                                                                        3 all 1.0.2-2 [30.9 kB]", "Get:16 http://us.archive.ubuntu.com/ubuntu xenial/uni                                                                                        verse amd64 supervisor all 3.2.0-2 [252 kB]", "Preconfiguring packages ...", "Fe                                                                                        tched 11.1 MB in 53s (209 kB/s)", "Selecting previously unselected package libgp                                                                                        m2:amd64.", "(Reading database ... ", "(Reading database ... 5%", "(Reading data                                                                                        base ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Readi                                                                                        ng database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%",                                                                                         "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ...                                                                                         50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading datab                                                                                        ase ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Readin                                                                                        g database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "                                                                                        (Reading database ... 95%", "(Reading database ... 100%", "(Reading database ...                                                                                         75859 files and directories currently installed.)", "Preparing to unpack .../li                                                                                        bgpm2_1.20.4-6.1_amd64.deb ...", "Unpacking libgpm2:amd64 (1.20.4-6.1) ...", "Se                                                                                        lecting previously unselected package htop.", "Preparing to unpack .../htop_2.0.                                                                                        1-1ubuntu1_amd64.deb ...", "Unpacking htop (2.0.1-1ubuntu1) ...", "Selecting pre                                                                                        viously unselected package libvpx3:amd64.", "Preparing to unpack .../libvpx3_1.5                                                                                        .0-2ubuntu1_amd64.deb ...", "Unpacking libvpx3:amd64 (1.5.0-2ubuntu1) ...", "Sel                                                                                        ecting previously unselected package libgd3:amd64.", "Preparing to unpack .../li                                                                                        bgd3_2.1.1-4ubuntu0.16.04.3_amd64.deb ...", "Unpacking libgd3:amd64 (2.1.1-4ubun                                                                                        tu0.16.04.3) ...", "Selecting previously unselected package libpython3.5:amd64."                                                                                        , "Preparing to unpack .../libpython3.5_3.5.2-2~16.04_amd64.deb ...", "Unpacking                                                                                         libpython3.5:amd64 (3.5.2-2~16.04) ...", "Selecting previously unselected packa                                                                                        ge libxslt1.1:amd64.", "Preparing to unpack .../libxslt1.1_1.1.28-2.1_amd64.deb                                                                                         ...", "Unpacking libxslt1.1:amd64 (1.1.28-2.1) ...", "Selecting previously unsel                                                                                        ected package nginx-common.", "Preparing to unpack .../nginx-common_1.10.0-0ubun                                                                                        tu0.16.04.3_all.deb ...", "Unpacking nginx-common (1.10.0-0ubuntu0.16.04.3) ..."                                                                                        , "Selecting previously unselected package nginx-core.", "Preparing to unpack ..                                                                                        ./nginx-core_1.10.0-0ubuntu0.16.04.3_amd64.deb ...", "Unpacking nginx-core (1.10                                                                                        .0-0ubuntu0.16.04.3) ...", "Selecting previously unselected package nginx.", "Pr                                                                                        eparing to unpack .../nginx_1.10.0-0ubuntu0.16.04.3_all.deb ...", "Unpacking ngi                                                                                        nx (1.10.0-0ubuntu0.16.04.3) ...", "Selecting previously unselected package ssl-                                                                                        cert.", "Preparing to unpack .../ssl-cert_1.0.37_all.deb ...", "Unpacking ssl-ce                                                                                        rt (1.0.37) ...", "Selecting previously unselected package postfix.", "Preparing                                                                                         to unpack .../postfix_3.1.0-3_amd64.deb ...", "Unpacking postfix (3.1.0-3) ..."                                                                                        , "Selecting previously unselected package screen.", "Preparing to unpack .../sc                                                                                        reen_4.3.1-2build1_amd64.deb ...", "Unpacking screen (4.3.1-2build1) ...", "Sele                                                                                        cting previously unselected package vim-runtime.", "Preparing to unpack .../vim-                                                                                        runtime_2%3a7.4.1689-3ubuntu1.1_all.deb ...", "Adding 'diversion of /usr/share/v                                                                                        im/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runti                                                                                        me'", "Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim7                                                                                        4/doc/tags.vim-tiny by vim-runtime'", "Unpacking vim-runtime (2:7.4.1689-3ubuntu                                                                                        1.1) ...", "Selecting previously unselected package vim.", "Preparing to unpack                                                                                         .../vim_2%3a7.4.1689-3ubuntu1.1_amd64.deb ...", "Unpacking vim (2:7.4.1689-3ubun                                                                                        tu1.1) ...", "Selecting previously unselected package python-meld3.", "Preparing                                                                                         to unpack .../python-meld3_1.0.2-2_all.deb ...", "Unpacking python-meld3 (1.0.2                                                                                        -2) ...", "Selecting previously unselected package supervisor.", "Preparing to u                                                                                        npack .../supervisor_3.2.0-2_all.deb ...", "Unpacking supervisor (3.2.0-2) ...",                                                                                         "Processing triggers for mime-support (3.59ubuntu1) ...", "Processing triggers                                                                                         for man-db (2.7.5-1) ...", "Processing triggers for libc-bin (2.23-0ubuntu4) ...                                                                                        ", "Processing triggers for systemd (229-4ubuntu11) ...", "Processing triggers f                                                                                        or ureadahead (0.100.0-19) ...", "Processing triggers for ufw (0.35-0ubuntu2) ..                                                                                        .", "Processing triggers for install-info (6.1.0.dfsg.1-5) ...", "Setting up lib                                                                                        gpm2:amd64 (1.20.4-6.1) ...", "Setting up htop (2.0.1-1ubuntu1) ...", "Setting u                                                                                        p libvpx3:amd64 (1.5.0-2ubuntu1) ...", "Setting up libgd3:amd64 (2.1.1-4ubuntu0.                                                                                        16.04.3) ...", "Setting up libpython3.5:amd64 (3.5.2-2~16.04) ...", "Setting up                                                                                         libxslt1.1:amd64 (1.1.28-2.1) ...", "Setting up nginx-common (1.10.0-0ubuntu0.16                                                                                        .04.3) ...", "Setting up nginx-core (1.10.0-0ubuntu0.16.04.3) ...", "Setting up                                                                                         nginx (1.10.0-0ubuntu0.16.04.3) ...", "Setting up ssl-cert (1.0.37) ...", "Setti                                                                                        ng up postfix (3.1.0-3) ...", "Adding group `postfix' (GID 119) ...", "Done.", "                                                                                        Adding system user `postfix' (UID 111) ...", "Adding new user `postfix' (UID 111                                                                                        ) with group `postfix' ...", "Not creating home directory `/var/spool/postfix'."                                                                                        , "Creating /etc/postfix/dynamicmaps.cf", "Adding group `postdrop' (GID 120) ...                                                                                        ", "Done.", "setting myhostname: erpnext.168.4.123", "setting alias maps", "sett                                                                                        ing alias database", "changing /etc/mailname to erpnext.168.4.123", "setting myo                                                                                        rigin", "setting destinations: $myhostname, erpnext.168.4.123, localhost.168.4.1                                                                                        23, , localhost", "setting relayhost: ", "setting mynetworks: 127.0.0.0/8 [::fff                                                                                        f:127.0.0.0]/104 [::1]/128", "setting mailbox_size_limit: 0", "setting recipient                                                                                        _delimiter: +", "setting inet_interfaces: all", "setting inet_protocols: all", "                                                                                        /etc/aliases does not exist, creating it.", "WARNING: /etc/aliases exists, but d                                                                                        oes not have a root alias.", "", "Postfix is now set up with a default configura                                                                                        tion.  If you need to make ", "changes, edit", "/etc/postfix/main.cf (and others                                                                                        ) as needed.  To view Postfix configuration", "values, see postconf(1).", "", "A                                                                                        fter modifying main.cf, be sure to run '/etc/init.d/postfix reload'.", "", "Runn                                                                                        ing newaliases", "newaliases: warning: valid_hostname: numeric hostname: 168.4.1                                                                                        23", "newaliases: fatal: file /etc/postfix/main.cf: parameter mydomain: bad para                                                                                        meter value: 168.4.123", "dpkg: error processing package postfix (--configure):"                                                                                        , " subprocess installed post-installation script returned error exit status 75"                                                                                        , "Setting up screen (4.3.1-2build1) ...", "Setting up vim-runtime (2:7.4.1689-3                                                                                        ubuntu1.1) ...", "Setting up vim (2:7.4.1689-3ubuntu1.1) ...", "update-alternati                                                                                        ves: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode", "upda                                                                                        te-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff)                                                                                         in auto mode", "update-alternatives: using /usr/bin/vim.basic to provide /usr/bi                                                                                        n/rvim (rvim) in auto mode", "update-alternatives: using /usr/bin/vim.basic to p                                                                                        rovide /usr/bin/rview (rview) in auto mode", "update-alternatives: using /usr/bi                                                                                        n/vim.basic to provide /usr/bin/vi (vi) in auto mode", "update-alternatives: usi                                                                                        ng /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode", "update-alt                                                                                        ernatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode", "                                                                                        Setting up python-meld3 (1.0.2-2) ...", "Setting up supervisor (3.2.0-2) ...", "                                                                                        Processing triggers for libc-bin (2.23-0ubuntu4) ...", "Processing triggers for                                                                                         systemd (229-4ubuntu11) ...", "Processing triggers for ureadahead (0.100.0-19) .                                                                                        ..", "Processing triggers for ufw (0.35-0ubuntu2) ...", "Errors were encountered                                                                                         while processing:", " postfix"]}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=38   changed=21   unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 351, in <module>
    install_bench(args)
  File "install.py", line 111, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 301, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'pro                                                                                        duction/install.yml', '-e', '@/tmp/extra_vars.json', '-vvvv', '--become', '--bec                                                                                        ome-user=frappe']' returned non-zero exit status 2

```

**Comment by sethu07** [comment]
@paul-100  Did you resolved this error??? If done means can you share how to do this??

**Comment by saurabh6790** [comment]
@paul-100  Still facing the issue? Not able to replicate the issue.

**Comment by ahmedshabib** [comment]
Just do a sudo python install.py --production --user frappe --verbose
