### ISSUE TITLE
[Question] Help with install ERPNEXT in MacOS

### ISSUE THREAD

**Issue by marti1125** [frappe/bench#337]
Python 2.7.10
OS X El Capita v10.11.6
$ bench get-app erpnext https://github.com/frappe/erpnext
INFO:bench.app:getting app erpnext
Cloning into 'erpnext'...
remote: Counting objects: 4316, done.
remote: Compressing objects: 100% (3951/3951), done.
remote: Total 4316 (delta 577), reused 2219 (delta 233), pack-reused 0
Receiving objects: 100% (4316/4316), 104.19 MiB | 109.00 KiB/s, done.
Resolving deltas: 100% (577/577), done.
Checking connectivity... done.
Checking out files: 100% (4324/4324), done.
installing erpnext
INFO:bench.app:installing erpnext
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bp/960cy1zd019ccssy2gb5y7xm0000gn/T/pip-build-qjDqek/frappe/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/willyaguirre/Documents/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/Users/willyaguirre/Documents/bench-repo/bench/commands/make.py", line 30, in get_app
    get_app(git_url, branch=branch)
  File "/Users/willyaguirre/Documents/bench-repo/bench/app.py", line 73, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/Users/willyaguirre/Documents/bench-repo/bench/app.py", line 103, in install_app
    find_links=find_links))
  File "/Users/willyaguirre/Documents/bench-repo/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q  -e ./apps/erpnext

**Comment by yashodhank** [comment]
@marti1125 for questions, search for similar threads or open new one if you are unable to find one at https://discuss.erpnext.com
