### ISSUE TITLE
Issue with completing the setup of ERPNEXT on local machine

### ISSUE THREAD

**Issue by osmanahmed2712** [frappe/bench#340]
-Installed ERPNEXT perfectly and got the login page.
-When i initialized the setup of desk for the first time it asked for the country,time,system user,company details,customer,supplier,item etc.
-When i reached to completing the setup i am unable to complete the setup .I received the following error.
-I tried many times still the same error.

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 36, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 27, in setup_complete
    create_sales_tax(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 250, in create_sales_tax
    if len(country_wise_tax)>0:
TypeError: object of type 'NoneType' has no len()
![a](https://cloud.githubusercontent.com/assets/22319481/19881364/7e066010-a01e-11e6-8f4f-5b31d82f8373.png)
![b](https://cloud.githubusercontent.com/assets/22319481/19881363/7e041a3a-a01e-11e6-97b8-806cb1c4d950.png)

**Comment by nabinhait** [comment]
The issue has been fixed in the latest version. Can you check again after updating your instance?

**Comment by osmanahmed2712** [comment]
When i tried to update the bench 
This is the error
[frappe@localhost frappe-bench]$ bench update
INFO:bench.utils:updating bench
Already up-to-date.
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 118 (delta 59), reused 19 (delta 19), pack-reused 2
Receiving objects: 100% (118/118), 59.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), completed with 13 local objects.
From https://github.com/frappe/frappe
   9f93076..d329ee3  master     -> upstream/master
   7c4f40b..9ecfebd  develop    -> upstream/develop
   4f7a737..f68b9ed  hotfix     -> upstream/hotfix
   fe98b32..657aa2d  v7.0.x     -> upstream/v7.0.x
 * [new tag]         v7.1.3     -> v7.1.3
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
Updating 9f93076..d329ee3
error: Your local changes to the following files would be overwritten by merge:
	frappe/__init__.py
	frappe/desk/doctype/bulk_update/bulk_update.js
	frappe/integration_broker/doctype/integration_service/integration_service.js
	frappe/integrations/doctype/dropbox_settings/dropbox_settings.js
	frappe/public/css/form_grid.css
	frappe/public/css/list.css
	frappe/public/less/form_grid.less
	frappe/public/less/list.less
Please, commit your changes or stash them before you can merge.
Aborting
Traceback (most recent call last):
  File "/usr/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/.bench/bench/commands/update.py", line 76, in _update
    pull_all_apps(bench_path=bench_path)
  File "/home/frappe/.bench/bench/app.py", line 140, in pull_all_apps
    remote=remote, branch=get_current_branch(app, bench_path=bench_path)), cwd=app_dir)
  File "/home/frappe/.bench/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git pull  upstream master

**Comment by osmanahmed2712** [comment]
the bench is already updated.

**Comment by nabinhait** [comment]
Your `Bench update` failed, it is giving an error because you have made local changes, which is conflicting with the updated code. Please resolve the conflict and update.

**Comment by osmanahmed2712** [comment]
i installed following -easy install  
-and very next i login to the erpnext page .
- There are no local changes done from my end
-i tried a fresh install and again i am facing the same issue .

**Comment by osmanahmed2712** [comment]
Refered the logs-
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 36, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 27, in setup_complete
    create_sales_tax(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 250, in create_sales_tax
    if len(country_wise_tax)>0:
TypeError: object of type 'NoneType' has no len()
[ERROR] 2016-11-01 17:23:17,632 | /home/frappe/frappe-bench/apps/frappe/frappe/
