### ISSUE TITLE
updating the bench 

### ISSUE THREAD

**Issue by osmanahmed2712** [frappe/bench#341]
I tried to update the bench but was not successful .Any help would be appreciated as in a desperate situation stuck up in the setting up the company can;t proceed.
[frappe@localhost frappe-bench]$ bench update
INFO:bench.utils:updating bench
Already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
Updating 9f93076..c0edd95
error: Your local changes to the following files would be overwritten by merge:
	frappe/__init__.py
	frappe/desk/doctype/bulk_update/bulk_update.js
	frappe/integration_broker/doctype/integration_service/integration_service.js
	frappe/integrations/doctype/dropbox_settings/dropbox_settings.js
	frappe/integrations/doctype/paypal_settings/paypal_settings.py
	frappe/model/db_schema.py
	frappe/public/css/form_grid.css
	frappe/public/css/list.css
	frappe/public/less/form_grid.less
	frappe/public/less/list.less
Please, commit your changes or stash them before you can merge.
Aborting
Traceback (most recent call last):
  File "/usr/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/.bench/bench/commands/update.py", line 76, in _update
    pull_all_apps(bench_path=bench_path)
  File "/home/frappe/.bench/bench/app.py", line 140, in pull_all_apps
    remote=remote, branch=get_current_branch(app, bench_path=bench_path)), cwd=app_dir)
  File "/home/frappe/.bench/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git pull  upstream master
[frappe@localhost frappe-bench]$

**Comment by system19** [comment]
Please ask all questions in the forum not Github.
To solve your problem delete:
frappe/init.py
frappe/desk/doctype/bulk_update/bulk_update.js
frappe/integration_broker/doctype/integration_service/integration_service.js
frappe/integrations/doctype/dropbox_settings/dropbox_settings.js
frappe/integrations/doctype/paypal_settings/paypal_settings.py
frappe/model/db_schema.py
frappe/public/css/form_grid.css
frappe/public/css/list.css
frappe/public/less/form_grid.less
frappe/public/less/list.less

Then cd ../ to frappe-bench then git pull then bench update

**Comment by osmanahmed2712** [comment]
Thank You system19.
I tried to delete all the files .Then i am facing this error.

[frappe@localhost frappe-bench]$ bench update
INFO:bench.utils:updating bench
Already up-to-date.
Traceback (most recent call last):
  File "/usr/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 49, in update
    version_upgrade = is_version_upgrade()
  File "/home/frappe/.bench/bench/app.py", line 155, in is_version_upgrade
    local_version = get_major_version(get_current_version(app, bench_path=bench_path))
  File "/home/frappe/.bench/bench/app.py", line 197, in get_current_version
    with open(os.path.join(repo_dir, os.path.basename(repo_dir), '__init__.py')) as f:
IOError: [Errno 2] No such file or directory: './apps/frappe/frappe/__init__.py'
[frappe@localhost frappe-bench]$

**Comment by system19** [comment]
Ok, Thats a bit weird.. This should cover a few bases. Assuming that your username is frappe, Go to: 
cd /home/frappe/frappe-bench/apps/frappe/
And delete all files within the  /frappe/ folder with:
sudo rm -r frappe
Then
git pull
Then
cd /home/frappe/bench-repo/bench/
sudo rm -r bench
Then
git pull
Then
cd /home/frappe/frappe-bench/
bench update

This will delete all previously downloaded files for bench and frappe and download all the latest files from github.
cd /home/frappe/frappe-bench/
Is where you execute all bench commands. All commands can be seen with bench --help
Any more issues please post at: https://discuss.erpnext.com
HTH

**Comment by system19** [comment]
Please close this issue. Thanks :-)
