### ISSUE TITLE
Setting up New Tenant 

### ISSUE THREAD

**Issue by EnSeal** [frappe/bench#347]
Hello Team 

I am trying to setup a multi tenant system on my installation, but how do i define or know my current site name. I think i am missing out few steps before the instruction on Multitenenat setup. 

Would appreciate a detailed instruction on prerequisites to setting up multitenants

**Comment by EnSeal** [comment]
ubuntu@ip-172-31-54-98:~$ ubuntu@ip-172-31-54-98:~$ bench get-app erpnext https://github.com            /frappe/erpnex            t
INFO:bench.app:getting app erpnext
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/ubuntu/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __ca                        ll__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in inv                        oke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invo                        ke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invo                        ke
    return callback(*args, **kwargs)
  File "/home/ubuntu/bench-repo/bench/commands/make.py", line 30, in get_app
    get_app(git_url, branch=branch)
  File "/home/ubuntu/bench-repo/bench/app.py", line 62, in get_app
    cwd=os.path.join(bench_path, 'apps'))
  File "/home/ubuntu/bench-repo/bench/utils.py", line 119, in exec_cmd
    p = subprocess.Popen(cmd, cwd=cwd, shell=True, stdout=stdout, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: './apps'

**Comment by yashodhank** [comment]
@EnSeal Correct place to seek help and ask questions is https://discuss.erpnext.com
Open new thread and someone will follow up, are you sure your bench is installed correctly?
Use automated installer instead of manual installation method for best results.
