### ISSUE TITLE
Production Installation Failure on Ubuntu Server 16 LTS ( info_egg )

### ISSUE THREAD

**Issue by adam-je** [frappe/bench#355]
I've been trying to setup ERPNext on EC2 for 2 days now, after over 10 attempts, 0 success!
I've tried different PHP versions, PIP addons (setuptools), python-mysqldb setup, etc on Ubuntu 14 and Ubuntu 16.

On https://github.com/frappe/bench
I cant get past the frappe installation. 

1. The easy setup script is getting stuck at with a the error:
- _**no hosts available**_ related to ansible
- Related to issue https://github.com/frappe/bench/issues/336

2. While the manual setup is failing at the error: 
- _**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e8Q0ZW/mysql-python/**_

Terminal:

`frappe@ip-172-31-21-146:~$ bench init frappe-bench && cd frappe-bench
Already using interpreter /usr/bin/python
INFO:bench.app:getting app frappe
Cloning into 'frappe'...
remote: Counting objects: 1979, done.
remote: Compressing objects: 100% (1829/1829), done.
remote: Total 1979 (delta 269), reused 771 (delta 95), pack-reused 0
Receiving objects: 100% (1979/1979), 12.59 MiB | 3.65 MiB/s, done.
Resolving deltas: 100% (269/269), done.
Checking connectivity... done.
installing frappe
INFO:bench.app:installing frappe
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iwmeai/mysql-python/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/home/frappe/bench-repo/bench/utils.py", line 56, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 73, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 103, in install_app
    find_links=find_links))
  File "/home/frappe/bench-repo/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
frappe@ip-172-31-21-146:~$
copying setuptools/msvc.py -> build/lib.linux-x86_64-2.7/setuptoo`

**Comment by jeromecc** [comment]
Try
    pip2 install ansible
(as root)
It seems related to this: https://stackoverflow.com/questions/34803467/unexpected-exception-name-basestring-is-not-defined-when-invoking-ansible2

**Comment by adam-je** [comment]
Thanks @jeromecc. Must have solved it another way using the simple install method.
