### ISSUE TITLE
Fresh setup fails

### ISSUE THREAD

**Issue by ChristopherMeyering** [frappe/bench#364]
Good day,
I freshly installed erpnext via bench.

But while doing the frontend-setup (users, company name etc.) the system breaks with "at least one system-manager is needed".

when i try to create one from cli with bench add-system-manager <email>
i get the following:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 179, in add_system_manager
    frappe.utils.user.add_system_manager(email, first_name, last_name, send_welcome_email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/user.py", line 264, in add_system_manager
    user.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 193, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 770, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 888, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 873, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/employee/employee.py", line 181, in validate_employee_role
    if "Employee" in [d.role for d in doc.get("user_roles")]:
TypeError: 'NoneType' object is not iterable`

Can you help me?

**Comment by rohitwaghchaure** [comment]
Hi @ChristopherMeyering 

It seems that you have pulled the latest code on the frappe application but not on the erpnext. Can you pull the latest code for erpnext application and do the bench migrate

**Comment by rohitwaghchaure** [comment]
Hi @ChristopherMeyering 

Kindly reload the supervisor if you are checking on the production site

**Comment by ChristopherMeyering** [comment]
Hi @rohitwaghchaure
Thanks! This worked fine.

Greetings
Chris
