### ISSUE TITLE
Unable to update to v8

### ISSUE THREAD

**Issue by bghtrbb** [frappe/bench#382]
Tried to use the instructions to install erpNext on a ubuntu server in aws. The instructions for both the easy install and manual install do not work. So I imported the virtual production machine (which is still on version 7). I tried to upgrade and I receive the following error.

```
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2017-03-09 in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'docfield', force=True) #2017-03-03 in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'docperm') #2017-03-03 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.drop_is_custom_from_docperm in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.drop_in_dialog in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.update_published_in_global_search in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'custom_docperm') in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'deleted_document') in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'version') #2017-04-01 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.rename_page_role_to_has_role #2017-03-16 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v7_2.setup_custom_perms #2017-01-19 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.set_user_permission_for_page_and_report #2017-03-20 in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.core.doctype.language.language.update_language_names() # 2017-04-12 in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.db.sql("update tabCommunication set communication_date = creation where time(communication_date) = 0") in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v7_2.fix_email_queue_recipient in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v7_2.update_feedback_request # 2017-02-27 in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.rename_doc('Country', 'Macedonia, Republic of', 'Macedonia', ignore_if_exists=True) in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.rename_doc('Country', 'Iran, Islamic Republic of', 'Iran', ignore_if_exists=True) in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.rename_doc('Country', 'Tanzania, United Republic of', 'Tanzania', ignore_if_exists=True) in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.rename_doc('Country', 'Syrian Arab Republic', 'Syria', ignore_if_exists=True) in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.rename_listsettings_to_usersettings in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v7_2.update_communications in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.deprecate_integration_broker in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.setup_email_inbox #2017-03-29 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.newsletter_childtable_migrate in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.db.sql("delete from `tabDesktop Icon` where module_name='Communication'") in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.db.sql("update `tabDesktop Icon` set type='list' where _doctype='Communication'") in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.fix_non_english_desktop_icons # 2017-04-12 in erpnext.vm (d56cb677eaab3383)
Success
Executing frappe.patches.v8_0.set_doctype_values_in_custom_role in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.stock_uom_in_selling in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.update_assessment_modules in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.delete_fleet_management_module_def in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.contact_address_links in erpnext.vm (d56cb677eaab3383)


Success
Executing erpnext.patches.v7_2.mark_students_active in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.update_guardian_name_in_student_master in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.update_abbr_in_salary_slips in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.rename_evaluation_criteria in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.update_party_type in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.setup_auto_close_settings in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.empty_supplied_items_for_non_subcontracted in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.arrear_leave_encashment_as_salary_component in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.rename_att_date_attendance in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.update_attendance_docstatus in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.move_dates_from_salary_structure_to_employee in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v7_2.make_all_assessment_group in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.manufacturer_childtable_migrate in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.repost_reserved_qty_for_multiple_sales_uom in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.addresses_linked_to_lead in erpnext.vm (d56cb677eaab3383)
Success
Executing execute:frappe.delete_doc('DocType', 'Purchase Common') in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.update_stock_qty_value_in_purchase_invoice in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.update_supplier_address_in_stock_entry in erpnext.vm (d56cb677eaab3383)
Success
Executing erpnext.patches.v8_0.rename_is_sample_item_to_allow_zero_valuation_rate in erpnext.vm (d56cb677eaab3383)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 210, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v8_0/rename_is_sample_item_to_allow_zero_valuation_rate.py", line 12, in execute
    rename_field(doctype, "is_sample_item", "allow_zero_valuation_rate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/rename_field.py", line 33, in rename_field
    (doctype, new_fieldname, old_fieldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'is_sample_item' in 'field list'")
frappe@erpnext:~/frappe-bench$ ec2-34-205-26-200.compute-1.amazonaws.com

```

**Comment by nabinhait** [comment]
Released the fix, please update agian
