### ISSUE TITLE
Having issues installing bench 

### ISSUE THREAD

**Issue by nelsonddon** [frappe/bench#384]
Below is the error i got when i tried to install bench on ubuntu, i need help 

nelsonddon@ubuntu:~$ bench init frappe-bench && cd frappe-bench
Directory frappe-bench already exists!
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/nelsonddon/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nelsonddon/bench-repo/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/home/nelsonddon/bench-repo/bench/utils.py", line 37, in init
    raise Exception("Site directory already exists")
Exception: Site directory already exists

**Comment by manassolanki** [comment]
Hi @nelsonddon ,
There is already a bench with name frappe-bench in your current directory. Either delete that directory or try with different bench name.

**Comment by kalungia** [comment]
This may be late but you can use --ignore-exist after bench init
