### ISSUE TITLE
creating site error

### ISSUE THREAD

**Issue by nelsonddon** [frappe/bench#385]
**This command gave me this error: bench new-site site1.local**

INFO:bench.utils:creating new site site1.local
frappe app is not installed. Run the following command to install frappe
bench get-app https://github.com/frappe/frappe.git
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/nelsonddon/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nelsonddon/bench-repo/bench/commands/make.py", line 56, in new_site
    new_site(site, mariadb_root_password=mariadb_root_password, admin_password=admin_password)
  File "/home/nelsonddon/bench-repo/bench/utils.py", line 149, in new_site
    db_name = hashlib.sha1(site).hexdigest()[:10],
NameError: global name 'hashlib' is not defined

**Comment by manassolanki** [comment]
Hi @nelsonddon ,
Your frappe app isn't installed properly. Run the following command:
`bench get-app https://github.com/frappe/frappe.git`

For any further help and issues, you can join our community
https://discuss.erpnext.com/
