### ISSUE TITLE
install.py --production: nginx does not start the master process as root and cannot bind to port 80

### ISSUE THREAD

**Issue by nicolaevladescu** [frappe/bench#387]
Hello.

I was trying to install ERPNext on a fresh CentOS 7 machine with the following commands in the following sequence:

`wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py`
`sudo python install.py --production` 

After it finished, the `nginx` service could not start due to permissions error because it binds to port `80` and the `nginx` master process does not start as `root`, it starts as user `nginx`, thus a non `root` user cannot bind below port `1024`

I presume it is an issue with the systemd unit file for `nginx` on CentOS 7, it looks exactly like this example from `nginx` wiki: https://www.nginx.com/resources/wiki/start/topics/examples/systemd/

I edited the unit file and added `User=root` then did a `systemctl daemon-reload` and restarted `nginx` but nothing changed, still could not bind `80`.

Anybody else having this issue?

Meanwhile this can fix this manually using `bench` to change the `nginx` port for the site.

**Comment by saurabh6790** [comment]
Are you still facing this issue?

**Comment by nicolaevladescu** [comment]
Didn't get that far this time:

`CentOS 7.4 amd64`, same two commands from above, i always download the script from `master`.

```
TASK [nginx : Copy nginx configuration in place.] **********************************************************************************************************************************
changed: [localhost]

TASK [nginx : Setup www redirect] **************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Ensure nginx is started and enabled to start at boot.] ***************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [mariadb : restart mysql] ******************************************************************************************************************************************

RUNNING HANDLER [nginx : restart nginx] ********************************************************************************************************************************************
	to retry, use: --limit @/tmp/.bench/playbooks/production/install.retry

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=46   changed=34   unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 388, in <module>
    install_bench(args)
  File "install.py", line 114, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 326, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```

```
-- Unit nginx.service has begun starting up.
Nov 10 19:40:29 centos-512mb-fra1-01 nginx[19260]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Nov 10 19:40:29 centos-512mb-fra1-01 nginx[19260]: nginx: [emerg] chown("/var/cache/nginx", 994) failed (13: Permission denied)
Nov 10 19:40:29 centos-512mb-fra1-01 nginx[19260]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 10 19:40:29 centos-512mb-fra1-01 systemd[1]: nginx.service: control process exited, code=exited status=1
Nov 10 19:40:29 centos-512mb-fra1-01 systemd[1]: Failed to start nginx - high performance web server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has failed.
--
-- The result is failed.
```

**Comment by nicolaevladescu** [comment]
You can easily reproduce this, i just took online a machine from DigitalOcean with CentOS 7, ssh into it and then run this three commands:

```
yum install -y wget
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
sudo python install.py --production
```

**Comment by saurabh6790** [comment]
Fixed! Please feel free to reopen the issue if the issue persists.
