### ISSUE TITLE
Unable to install the master branch of frappe-bench

### ISSUE THREAD

**Issue by Arsyad** [frappe/bench#389]
Hi,

I am trying to setup frappe bench on Mac OS Sierra. I am always getting an error as below:

`Arsyads-iMac-2:frappe-bench arsyad$ bench init frappe-bench --frappe-branch master
INFO:bench.utils:virtualenv -q env -p /usr/local/opt/python/bin/python2.7
Already using interpreter /usr/local/opt/python/bin/python2.7
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch master  --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 125747, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 125747 (delta 22), reused 0 (delta 0), pack-reused 125674
Receiving objects: 100% (125747/125747), 95.69 MiB | 3.94 MiB/s, done.
Resolving deltas: 100% (94458/94458), done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Command "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/frappe-bench/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/p6/yyn74c_d3cb3yppcz1cv_85w0000gn/T/pip-build-P6kJgY/mysql-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/p6/yyn74c_d3cb3yppcz1cv_85w0000gn/T/pip-hBlm6Q-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arsyad/Documents/Arsyad/work/python/frappe-bench/frappe-bench/env/bin/../include/site/python2.7/mysql-python" failed with error code 1 in /private/var/folders/p6/yyn74c_d3cb3yppcz1cv_85w0000gn/T/pip-build-P6kJgY/mysql-python/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/commands/make.py", line 20, in init
    verbose=verbose, clone_from=clone_from)
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/utils.py", line 56, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/app.py", line 76, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/app.py", line 107, in install_app
    find_links=find_links))
  File "/Users/arsyad/Documents/Arsyad/work/python/frappe-bench/bench-repo/bench/utils.py", line 130, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
`

Where did I go wrong?

**Comment by arsyad** [comment]
By the way, I was following this Wiki to get it setup - https://github.com/frappe/bench/wiki/Turning-a-Mac-into-a-Frappe-Framework-Developer-Machine

Got stuck after I run command bench init frappe-bench --frappe-branch master

**Comment by DRogue1337** [comment]
Do you still got the problem?

Could you wrap your console output in 3 backticks each, like this "```"?
Would make it more readable.

So

`dweipert@MacBook-Pro:~ » vagrant status
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
dweipert@MacBook-Pro:~ »                                                                                  1 ↵`

becomes

```
dweipert@MacBook-Pro:~ » vagrant status
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
dweipert@MacBook-Pro:~ »                                                                                  1 ↵
```

**Comment by ginotria** [comment]
I have the same issue in Mac OS Sierra 10.12.5

```gino at MacBook-Pro-2 in ~/Projects
○ bench init frappe-bench && cd frappe-bench
INFO:bench.utils:virtualenv -q env -p /usr/local/opt/python/bin/python2.7
Already using interpreter /usr/local/opt/python/bin/python2.7
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install six
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 132922, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 132922 (delta 60), reused 65 (delta 26), pack-reused 132778
Receiving objects: 100% (132922/132922), 102.37 MiB | 3.22 MiB/s, done.
Resolving deltas: 100% (100478/100478), done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Command "/Users/gino/Projects/frappe-bench/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kb/bnfxq84d6slf5b3glvr1smf80000gp/T/pip-build-ALwCBL/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/kb/bnfxq84d6slf5b3glvr1smf80000gp/T/pip-EXDxIZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gino/Projects/frappe-bench/env/bin/../include/site/python2.7/mysqlclient" failed with error code 1 in /private/var/folders/kb/bnfxq84d6slf5b3glvr1smf80000gp/T/pip-build-ALwCBL/mysqlclient/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/gino/Projects/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/gino/Projects/bench-repo/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/Users/gino/Projects/bench-repo/bench/utils.py", line 56, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/Users/gino/Projects/bench-repo/bench/app.py", line 76, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/Users/gino/Projects/bench-repo/bench/app.py", line 107, in install_app
    find_links=find_links))
  File "/Users/gino/Projects/bench-repo/bench/utils.py", line 130, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir```

**Comment by deresegetachew** [comment]
Any Solution ?

**Comment by itssuyog96** [comment]
Same issue with me on MacOS Sierra v10.12.5

Log ->
```
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hm/jbqvwv_n1sb46q_v9wvb3fh80000gp/T/pip-build-gPJsMA/mysqlclient/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==4.1.0', 'console_scripts', 'bench')()
  File "/Users/admin/Documents/erp/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/Documents/erp/bench-repo/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/Users/admin/Documents/erp/bench-repo/bench/utils.py", line 56, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/Users/admin/Documents/erp/bench-repo/bench/app.py", line 76, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/Users/admin/Documents/erp/bench-repo/bench/app.py", line 107, in install_app
    find_links=find_links))
  File "/Users/admin/Documents/erp/bench-repo/bench/utils.py", line 130, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
```

**Comment by itssuyog96** [comment]
Any Update??

**Comment by saurabh6790** [comment]
Install dependancies `openssl-devel` for centos and `libssl-dev` for ubuntu.
