### ISSUE TITLE
Error setting lets-encrypt - IOError: Please specify user or filename to write.

### ISSUE THREAD

**Issue by revant** [frappe/bench#404]
forum post here : https://discuss.erpnext.com/t/i-have-found-some-error-after-using-ssl/23234
```
INFO:bench.utils:sudo systemctl start nginx
Traceback (most recent call last):
File "/usr/local/bin/bench", line 11, in 
load_entry_point('bench', 'console_scripts', 'bench')()
File "/home/frappe/.bench/bench/cli.py", line 40, in cli
bench_command()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/home/frappe/.bench/bench/commands/setup.py", line 104, in setup_letsencrypt
setup_letsencrypt(site, custom_domain, bench_path='.')
File "/home/frappe/.bench/bench/config/lets_encrypt.py", line 42, in setup_letsencrypt
setup_crontab()
File "/home/frappe/.bench/bench/config/lets_encrypt.py", line 89, in setup_crontab
user_crontab.write()
File "/usr/local/lib/python2.7/dist-packages/crontab.py", line 311, in write
raise IOError("Please specify user or filename to write.")
IOError: Please specify user or filename to write.
```

This _seems_ to fix it: https://github.com/frappe/bench/compare/master...revant:letsencrypt-fix
but `user_crontab.crons` returns None. So the crontab won't auto update the certificate.

@vjFaLk any idea?

**Comment by vjFaLk** [comment]
Hm, I wonder if there was a change in the python-crontab package that has caused this. Make a PR from that.

**Comment by revant** [comment]
https://pypi.python.org/pypi/python-crontab documentation says

```
from crontab import CronTab
empty_cron    = CronTab()
my_user_cron  = CronTab(user=True)
users_cron    = CronTab(user='username')
system_cron = CronTab(tabfile='/etc/crontab', user=False)
```
which cronfile should be used?

**Comment by vjFaLk** [comment]
System cron.
