### ISSUE TITLE
Session Start Failed on OS X

### ISSUE THREAD

**Issue by cetra3** [frappe/bench#456]
Following the tutorial from [here](https://frappe.github.io/frappe/user/en/tutorial/start)

### System Specs

I've used homebrew to install most things (mysql, node, etc..)

* Mac OS X `10.11.4`
* NPM `5.3.0`
* NodeJS `v8.2.1`
* Python `2.7.12`
* pip `9.0.1`
* Redis server v=`3.2.8`
* mysql  `Ver 14.14 Distrib 5.7.18`

### Steps to Reproduce

* Ran the following commands:

```
bench new-site library
bench use library
bench --site library install-app library_management
bench start
```

* Navigated to http://localhost:8000
* Logged in with provided credentials
* Received the following error:

![whack](https://user-images.githubusercontent.com/6415435/28551246-14caae56-7126-11e7-807a-b5a120f1f1de.png)

* Command line has the following:

```
10:38:00 web.1            | Traceback (most recent call last):
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/www/desk.py", line 22, in get_context
10:38:00 web.1            |     boot = frappe.sessions.get()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/sessions.py", line 150, in get
10:38:00 web.1            |     bootinfo = get_bootinfo()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/boot.py", line 29, in get_bootinfo
10:38:00 web.1            |     get_user(bootinfo)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/boot.py", line 205, in get_user
10:38:00 web.1            |     bootinfo.user = frappe.get_user().load_user()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/utils/user.py", line 200, in load_user
10:38:00 web.1            |     self.build_permissions()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/utils/user.py", line 94, in build_permissions
10:38:00 web.1            |     active_modules = frappe.get_active_modules() or []
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/__init__.py", line 1379, in get_active_modules
10:38:00 web.1            |     domains = get_active_domains()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/__init__.py", line 1367, in get_active_domains
10:38:00 web.1            |     fields=["domain"], distinct=True)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/__init__.py", line 1155, in get_all
10:38:00 web.1            |     return get_list(doctype, *args, **kwargs)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/__init__.py", line 1128, in get_list
10:38:00 web.1            |     return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/model/db_query.py", line 88, in execute
10:38:00 web.1            |     result = self.build_and_run()
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/model/db_query.py", line 112, in build_and_run
10:38:00 web.1            |     return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/apps/frappe/frappe/database.py", line 165, in sql
10:38:00 web.1            |     self._cursor.execute(query)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
10:38:00 web.1            |     self.errorhandler(self, exc, value)
10:38:00 web.1            |   File "/<install_dir>/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
10:38:00 web.1            |     raise errorvalue
10:38:00 web.1            | InterfaceError: (-1, 'error totally whack')
10:38:00 web.1            | 
```

**Comment by saurabh6790** [comment]
Not able to replicate. If replicate again please open at https://github.com/frappe/erpnext/issues
