### ISSUE TITLE
How to use dependencies (ala Maria DB and Redis etc) as docker containers?

### ISSUE THREAD

**Issue by dmitry-saritasa** [frappe/bench#461]
```
bench init frappe-bench && cd frappe-bench
...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN frappe@ No description

added 548 packages in 26.651s
Wrote css/frappe-web.css - 64.45 KB
Wrote js/frappe-web.min.js - 137.98 KB
Wrote js/dialog.min.js - 104.1 KB
Wrote css/desk.min.css - 291.3 KB
Wrote css/frappe-rtl.css - 32.37 KB
Wrote js/libs.min.js - 815.22 KB
Wrote js/desk.min.js - 505.74 KB
Wrote js/d3.min.js - 380.17 KB
Wrote css/module.min.css - 2.08 KB
Wrote css/form.min.css - 4.47 KB
Wrote js/form.min.js - 191.84 KB
Wrote css/list.min.css - 14.04 KB
Wrote js/list.min.js - 138.56 KB
Wrote css/report.min.css - 7.81 KB
Wrote js/report.min.js - 255.75 KB
Wrote js/web_form.min.js - 247.22 KB
Wrote css/web_form.css - 24.42 KB
Wrote js/print_format_v3.min.js - 23.39 KB
/bin/sh: redis-server: command not found
Traceback (most recent call last):
  File "/home/dmitry/.pyenv/versions/erp/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/dmitry/Projects/experiments/erpnext/bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/home/dmitry/.pyenv/versions/2.7.11/envs/erp/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dmitry/.pyenv/versions/2.7.11/envs/erp/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dmitry/.pyenv/versions/2.7.11/envs/erp/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dmitry/.pyenv/versions/2.7.11/envs/erp/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dmitry/.pyenv/versions/2.7.11/envs/erp/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dmitry/Projects/experiments/erpnext/bench/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/home/dmitry/Projects/experiments/erpnext/bench/bench/utils.py", line 68, in init
    redis.generate_config(path)
  File "/home/dmitry/Projects/experiments/erpnext/bench/bench/config/redis.py", line 39, in generate_config
    "redis_version": get_redis_version(),
  File "/home/dmitry/Projects/experiments/erpnext/bench/bench/config/redis.py", line 59, in get_redis_version
    version_string = subprocess.check_output('redis-server --version', shell=True).strip()
  File "/home/dmitry/.pyenv/versions/2.7.11/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'redis-server --version' returned non-zero exit status 127

```
**So is there a way to provision configuration somehow?**

**Comment by vishalseshagiri** [comment]
Working on this , should have a solution within a couple of days. Have been able create an run the 3 redis servers on the redis container, only thing is that the frappe container ports are unable to bind with the redis ports. If that gets figured out I think we are good to go.. Will post this once done.

**Comment by emcniece** [comment]
@dmitry-saritasa https://github.com/frappe/frappe_docker

**Comment by vishalseshagiri** [comment]
@emcniece this is sorted now. Please got have a look at the repo [frappe_docker](https://github.com/frappe/frappe_docker). Use the --skip-bench-mkdir and --skip-redis-config-generation flags while doing bench init.

**Comment by vishalseshagiri** [comment]
I think this issue can be close now.
