### ISSUE TITLE
frape-bench init failed centos7

### ISSUE THREAD

**Issue by vijai1996** [frappe/bench#485]
I'm trying to install erpnext on centos 7 server and it fails on `frape-bench` init. I have installed all the dependencies as far as I know.
```bench init frappe-bench

INFO:bench.utils:virtualenv -q env -p /usr/bin/python2

Already using interpreter /usr/bin/python2

INFO:bench.utils:./env/bin/pip -q install --upgrade pip

INFO:bench.utils:./env/bin/pip -q install wheel

INFO:bench.utils:./env/bin/pip -q install six

INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit

INFO:bench.app:getting app frappe

INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream

Cloning into 'frappe'...

remote: Counting objects: 140735, done.

remote: Compressing objects: 100% (21/21), done.

remote: Total 140735 (delta 9), reused 20 (delta 7), pack-reused 140707

Receiving objects: 100% (140735/140735), 114.21 MiB | 11.09 MiB/s, done.

Resolving deltas: 100% (106958/106958), done.

('installing', u'frappe')

INFO:bench.app:installing frappe

INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Command "/home/admin/domains/erp.chennaielectrikkals.com/frappe-bench/env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-MVWn32/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Z7rA0G-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/admin/domains/erp.chennaielectrikkals.com/frappe-bench/env/include/site/python2.7/mysqlclient" failed with error code 1 in /tmp/pip-build-MVWn32/mysqlclient/

Traceback (most recent call last):

  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench==4.1.0', 'console_scripts', 'bench')()

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/cli.py", line 40, in cli
    bench_command()

  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)

  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)

  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/commands/make.py", line 21, in init

    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/utils.py", line 64, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/app.py", line 76, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/app.py", line 107, in install_app
    find_links=find_links))

  File "/home/admin/domains/erp.chennaielectrikkals.com/bench-repo/bench/utils.py", line 140, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
```

I'm clueless now. Can someone help me out?

**Comment by saurabh6790** [comment]
Try with installing openssl via `yum install openssl-devel` then run the script.

**Comment by vijai1996** [comment]
@saurabh6790 Openssl-devel is installed and latest.

**Comment by saurabh6790** [comment]
@vijai1996 Which version you are using 7.2 or 7.3?

**Comment by vijai1996** [comment]
@saurabh6790 CentOS 7.4

**Comment by achillesrasquinha** [comment]
MariaDB version, please?

**Comment by vijai1996** [comment]
@achillesrasquinha its 10.1.26

**Comment by achillesrasquinha** [comment]
Did this fix with @saurabh6790's suggestion?
Or could you try this again? We just seemed to patch a fix.

**Comment by vijai1996** [comment]
@achillesrasquinha of course yes! I tried and it is already installed and the latest.
I do notice a commit to disable mysqlclient version check. let me try to install tonight and get back.

**Comment by achillesrasquinha** [comment]
Great! Kindly close the issue. We'd patched an updated `mysqlclient` that should fix the issue. For other reasons, this could be a system error.

**Comment by achillesrasquinha** [comment]
Closing due to inactivity.
