### ISSUE TITLE
frappe-bench from pip error when bench init

### ISSUE THREAD

**Issue by jodeq** [frappe/bench#507]
After installing frappe-bench from pip on fresh install Debian 9 
```
pip install --user frappe-bench
```
When trying to create new bench with 
```
bench init frappe-bench
```
I've got this error
```
IOError: [Errno 2] No such file or directory: '/home/frappe/.local/lib/python2.7/site-packages/bench/patches/patches.txt'
```

**Comment by jodeq** [comment]
Full log
```
INFO:bench.utils:virtualenv -q env -p /usr/bin/python
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install six
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 145989, done.
remote: Total 145989 (delta 0), reused 0 (delta 0), pack-reused 145989
Receiving objects: 100% (145989/145989), 120.93 MiB | 22.95 MiB/s, done.
Resolving deltas: 100% (111228/111228), done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Updating node libraries...
INFO:bench.utils:npm install

> uws@0.14.5 install /home/frappe/frappe-bench/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> chromedriver@2.33.2 install /home/frappe/frappe-bench/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 3995K total.
Extracting zip contents
Copying to target path /home/frappe/frappe-bench/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/frappe/frappe-bench/node_modules/chromedriver/lib/chromedriver/chromedriver
frappe@ /home/frappe/frappe-bench
├─┬ babel-core@6.26.0 
│ ├─┬ babel-code-frame@6.26.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@3.0.2 
│ ├─┬ babel-generator@6.26.0 
│ │ ├─┬ detect-indent@4.0.0 
│ │ │ └─┬ repeating@2.0.1 
│ │ │   └─┬ is-finite@1.0.2 
│ │ │     └── number-is-nan@1.0.1 
│ │ ├── jsesc@1.3.0 
│ │ └── trim-right@1.0.1 
│ ├── babel-helpers@6.24.1 
│ ├── babel-messages@6.23.0 
│ ├─┬ babel-register@6.26.0 
│ │ ├── core-js@2.5.1 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ ├── os-homedir@1.0.2 
│ │ │ └── os-tmpdir@1.0.2 
│ │ └── source-map-support@0.4.18 
│ ├─┬ babel-runtime@6.26.0 
│ │ └── regenerator-runtime@0.11.0 
│ ├── babel-template@6.26.0 
│ ├─┬ babel-traverse@6.26.0 
│ │ └── globals@9.18.0 
│ ├─┬ babel-types@6.26.0 
│ │ └── to-fast-properties@1.0.3 
│ ├── babylon@6.18.0 
│ ├── convert-source-map@1.5.1 
│ ├─┬ debug@2.6.9 
│ │ └── ms@2.0.0 
│ ├── json5@0.5.1 
│ ├── lodash@4.17.4 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.8 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├── path-is-absolute@1.0.1 
│ ├── private@0.1.8 
│ ├── slash@1.0.0 
│ └── source-map@0.5.7 
├─┬ babel-preset-env@1.6.1 
│ ├── babel-plugin-check-es2015-constants@6.22.0 
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0 
│ ├─┬ babel-plugin-transform-async-to-generator@6.24.1 
│ │ ├── babel-helper-remap-async-to-generator@6.24.1 
│ │ └── babel-plugin-syntax-async-functions@6.13.0 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 
│ ├── babel-plugin-transform-es2015-block-scoping@6.26.0 
│ ├─┬ babel-plugin-transform-es2015-classes@6.24.1 
│ │ ├── babel-helper-define-map@6.26.0 
│ │ ├── babel-helper-function-name@6.24.1 
│ │ ├── babel-helper-optimise-call-expression@6.24.1 
│ │ └── babel-helper-replace-supers@6.24.1 
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 
│ ├── babel-plugin-transform-es2015-for-of@6.23.0 
│ ├── babel-plugin-transform-es2015-function-name@6.24.1 
│ ├── babel-plugin-transform-es2015-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.26.0 
│ │ └── babel-plugin-transform-strict-mode@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.24.1 
│ │ └── babel-helper-hoist-variables@6.24.1 
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.1 
│ ├── babel-plugin-transform-es2015-object-super@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1 
│ │ ├── babel-helper-call-delegate@6.24.1 
│ │ └── babel-helper-get-function-arity@6.24.1 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-spread@6.22.0 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1 
│ │ └── babel-helper-regex@6.26.0 
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.24.1 
│ │ └─┬ regexpu-core@2.0.0 
│ │   ├── regenerate@1.3.3 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ ├─┬ babel-plugin-transform-exponentiation-operator@6.24.1 
│ │ ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.24.1 
│ │ │ └── babel-helper-explode-assignable-expression@6.24.1 
│ │ └── babel-plugin-syntax-exponentiation-operator@6.13.0 
│ ├─┬ babel-plugin-transform-regenerator@6.26.0 
│ │ └── regenerator-transform@0.10.1 
│ ├─┬ browserslist@2.9.1 
│ │ ├── caniuse-lite@1.0.30000770 
│ │ └── electron-to-chromium@1.3.27 
│ ├─┬ invariant@2.2.2 
│ │ └── loose-envify@1.3.1 
│ └── semver@5.4.1 
├─┬ babel-preset-minify@0.2.0 
│ ├─┬ babel-plugin-minify-builtins@0.2.0 
│ │ └── babel-helper-evaluate-path@0.2.0 
│ ├── babel-plugin-minify-constant-folding@0.2.0 
│ ├─┬ babel-plugin-minify-dead-code-elimination@0.2.0 
│ │ ├── babel-helper-mark-eval-scopes@0.2.0 
│ │ ├── babel-helper-remove-or-void@0.2.0 
│ │ └── lodash.some@4.6.0 
│ ├─┬ babel-plugin-minify-flip-comparisons@0.2.0 
│ │ └── babel-helper-is-void-0@0.2.0 
│ ├─┬ babel-plugin-minify-guarded-expressions@0.2.0 
│ │ └── babel-helper-flip-expressions@0.2.0 
│ ├── babel-plugin-minify-infinity@0.2.0 
│ ├── babel-plugin-minify-mangle-names@0.2.0 
│ ├── babel-plugin-minify-numeric-literals@0.2.0 
│ ├── babel-plugin-minify-replace@0.2.0 
│ ├─┬ babel-plugin-minify-simplify@0.2.0 
│ │ ├── babel-helper-is-nodes-equiv@0.0.1 
│ │ └── babel-helper-to-multiple-sequence-expressions@0.2.0 
│ ├── babel-plugin-minify-type-constructors@0.2.0 
│ ├── babel-plugin-transform-inline-consecutive-adds@0.2.0 
│ ├── babel-plugin-transform-member-expression-literals@6.8.5 
│ ├── babel-plugin-transform-merge-sibling-variables@6.8.6 
│ ├── babel-plugin-transform-minify-booleans@6.8.3 
│ ├── babel-plugin-transform-property-literals@6.8.5 
│ ├── babel-plugin-transform-regexp-constructors@0.2.0 
│ ├── babel-plugin-transform-remove-console@6.8.5 
│ ├── babel-plugin-transform-remove-debugger@6.8.5 
│ ├── babel-plugin-transform-remove-undefined@0.2.0 
│ ├── babel-plugin-transform-simplify-comparison-operators@6.8.5 
│ ├── babel-plugin-transform-undefined-to-void@6.8.3 
│ └── lodash.isplainobject@4.0.6 
├─┬ chokidar@1.7.0 
│ ├─┬ anymatch@1.3.2 
│ │ ├─┬ micromatch@2.3.11 
│ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ └── arr-flatten@1.1.0 
│ │ │ ├── array-unique@0.2.1 
│ │ │ ├─┬ braces@1.8.5 
│ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │   ├─┬ randomatic@1.1.7 
│ │ │ │ │   │ ├─┬ is-number@3.0.0 
│ │ │ │ │   │ │ └── kind-of@3.2.2 
│ │ │ │ │   │ └── kind-of@4.0.0 
│ │ │ │ │   └── repeat-string@1.6.1 
│ │ │ │ ├── preserve@0.2.0 
│ │ │ │ └── repeat-element@1.1.2 
│ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ ├── extglob@0.3.2 
│ │ │ ├── filename-regex@2.0.1 
│ │ │ ├─┬ kind-of@3.2.2 
│ │ │ │ └── is-buffer@1.1.6 
│ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ ├─┬ for-own@0.1.5 
│ │ │ │ │ └── for-in@1.0.2 
│ │ │ │ └── is-extendable@0.1.1 
│ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ ├── glob-base@0.3.0 
│ │ │ │ └── is-dotfile@1.0.3 
│ │ │ └─┬ regex-cache@0.4.4 
│ │ │   └─┬ is-equal-shallow@0.1.3 
│ │ │     └── is-primitive@2.0.0 
│ │ └─┬ normalize-path@2.1.1 
│ │   └── remove-trailing-separator@1.1.0 
│ ├── async-each@1.0.1 
│ ├── glob-parent@2.0.0 
│ ├── inherits@2.0.3 
│ ├─┬ is-binary-path@1.0.1 
│ │ └── binary-extensions@1.11.0 
│ ├─┬ is-glob@2.0.1 
│ │ └── is-extglob@1.0.0 
│ └─┬ readdirp@2.1.0 
│   └── set-immediate-shim@1.0.1 
├─┬ chromedriver@2.33.2 
│ ├─┬ del@3.0.0 
│ │ ├─┬ globby@6.1.0 
│ │ │ ├─┬ array-union@1.0.2 
│ │ │ │ └── array-uniq@1.0.3 
│ │ │ ├── glob@7.1.2 
│ │ │ ├── object-assign@4.1.1 
│ │ │ ├── pify@2.3.0 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├── is-path-cwd@1.0.0 
│ │ ├─┬ is-path-in-cwd@1.0.0 
│ │ │ └─┬ is-path-inside@1.0.0 
│ │ │   └── path-is-inside@1.0.2 
│ │ ├── p-map@1.2.0 
│ │ ├── pify@3.0.0 
│ │ └── rimraf@2.6.2 
│ ├─┬ extract-zip@1.6.6 
│ │ ├─┬ concat-stream@1.6.0 
│ │ │ └── typedarray@0.0.6 
│ │ ├── mkdirp@0.5.0 
│ │ └─┬ yauzl@2.4.1 
│ │   └─┬ fd-slicer@1.0.1 
│ │     └── pend@1.2.0 
│ ├── kew@0.7.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └─┬ request@2.83.0 
│   ├── aws-sign2@0.7.0 
│   ├── aws4@1.6.0 
│   ├── caseless@0.12.0 
│   ├─┬ combined-stream@1.0.5 
│   │ └── delayed-stream@1.0.0 
│   ├── forever-agent@0.6.1 
│   ├─┬ har-validator@5.0.3 
│   │ ├─┬ ajv@5.4.0 
│   │ │ ├── co@4.6.0 
│   │ │ ├── fast-deep-equal@1.0.0 
│   │ │ ├── fast-json-stable-stringify@2.0.0 
│   │ │ └── json-schema-traverse@0.3.1 
│   │ └── har-schema@2.0.0 
│   ├─┬ hawk@6.0.2 
│   │ ├── boom@4.3.1 
│   │ ├─┬ cryptiles@3.1.2 
│   │ │ └── boom@5.2.0 
│   │ ├── hoek@4.2.0 
│   │ └── sntp@2.1.0 
│   ├─┬ http-signature@1.2.0 
│   │ ├── assert-plus@1.0.0 
│   │ ├─┬ jsprim@1.4.1 
│   │ │ ├── extsprintf@1.3.0 
│   │ │ ├── json-schema@0.2.3 
│   │ │ └── verror@1.10.0 
│   │ └─┬ sshpk@1.13.1 
│   │   ├── asn1@0.2.3 
│   │   ├── bcrypt-pbkdf@1.0.1 
│   │   ├── dashdash@1.14.1 
│   │   ├── ecc-jsbn@0.1.1 
│   │   ├── getpass@0.1.7 
│   │   ├── jsbn@0.1.1 
│   │   └── tweetnacl@0.14.5 
│   ├── is-typedarray@1.0.0 
│   ├── isstream@0.1.2 
│   ├── json-stringify-safe@5.0.1 
│   ├─┬ mime-types@2.1.17 
│   │ └── mime-db@1.30.0 
│   ├── oauth-sign@0.8.2 
│   ├── performance-now@2.1.0 
│   ├── stringstream@0.0.5 
│   ├─┬ tough-cookie@2.3.3 
│   │ └── punycode@1.4.1 
│   ├── tunnel-agent@0.6.0 
│   └── uuid@3.1.0 
├── cookie@0.3.1 
├─┬ express@4.16.2 
│ ├─┬ accepts@1.3.4 
│ │ └── negotiator@0.6.1 
│ ├── array-flatten@1.1.1 
│ ├─┬ body-parser@1.18.2 
│ │ ├── bytes@3.0.0 
│ │ ├─┬ http-errors@1.6.2 
│ │ │ └── setprototypeof@1.0.3 
│ │ ├── iconv-lite@0.4.19 
│ │ └── raw-body@2.3.2 
│ ├── content-disposition@0.5.2 
│ ├── content-type@1.0.4 
│ ├── cookie-signature@1.0.6 
│ ├── depd@1.1.1 
│ ├── encodeurl@1.0.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.8.1 
│ ├─┬ finalhandler@1.1.0 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.5.2 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.2 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@2.0.2 
│ │ ├── forwarded@0.1.2 
│ │ └── ipaddr.js@1.5.2 
│ ├── qs@6.5.1 
│ ├── range-parser@1.2.0 
│ ├── safe-buffer@5.1.1 
│ ├─┬ send@0.16.1 
│ │ └── destroy@1.0.4 
│ ├── serve-static@1.13.1 
│ ├── setprototypeof@1.1.0 
│ ├── statuses@1.3.1 
│ ├─┬ type-is@1.6.15 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.1 
│ └── vary@1.1.2 
├─┬ less@2.7.3 
│ ├─┬ errno@0.1.4 
│ │ └── prr@0.0.0 
│ ├── graceful-fs@4.1.11 
│ ├── image-size@0.5.5 
│ ├── mime@1.4.1 
│ ├─┬ promise@7.3.1 
│ │ └── asap@2.0.6 
│ └─┬ request@2.81.0 
│   ├── aws-sign2@0.6.0 
│   ├── form-data@2.1.4 
│   ├─┬ har-validator@4.2.1 
│   │ ├─┬ ajv@4.11.8 
│   │ │ └─┬ json-stable-stringify@1.0.1 
│   │ │   └── jsonify@0.0.0 
│   │ └── har-schema@1.0.5 
│   ├─┬ hawk@3.1.3 
│   │ ├── boom@2.10.1 
│   │ ├── cryptiles@2.0.5 
│   │ ├── hoek@2.16.3 
│   │ └── sntp@1.0.9 
│   ├─┬ http-signature@1.1.1 
│   │ └── assert-plus@0.2.0 
│   ├── performance-now@0.2.0 
│   └── qs@6.4.0 
├─┬ nightwatch@0.9.16 
│ ├─┬ chai-nightwatch@0.1.1 
│ │ ├── assertion-error@1.0.0 
│ │ └─┬ deep-eql@0.1.3 
│ │   └── type-detect@0.1.1 
│ ├── ejs@0.8.3 
│ ├─┬ lodash.clone@3.0.3 
│ │ ├─┬ lodash._baseclone@3.3.0 
│ │ │ ├── lodash._arraycopy@3.0.0 
│ │ │ ├── lodash._arrayeach@3.0.0 
│ │ │ ├─┬ lodash._baseassign@3.2.0 
│ │ │ │ └── lodash._basecopy@3.0.1 
│ │ │ ├── lodash._basefor@3.0.3 
│ │ │ ├── lodash.isarray@3.0.4 
│ │ │ └─┬ lodash.keys@3.1.2 
│ │ │   ├── lodash._getnative@3.9.1 
│ │ │   └── lodash.isarguments@3.1.0 
│ │ ├── lodash._bindcallback@3.0.1 
│ │ └── lodash._isiterateecall@3.0.9 
│ ├─┬ lodash.defaultsdeep@4.3.2 
│ │ ├── lodash._baseclone@4.5.7 
│ │ ├── lodash._stack@4.1.3 
│ │ ├── lodash.keysin@4.2.0 
│ │ ├── lodash.mergewith@4.6.0 
│ │ └── lodash.rest@4.0.5 
│ ├── minimatch@3.0.3 
│ ├── mkpath@1.0.0 
│ ├─┬ mocha-nightwatch@3.2.2 
│ │ ├── browser-stdout@1.3.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├── diff@1.4.0 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ glob@7.0.5 
│ │ │ ├── fs.realpath@1.0.0 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ └── once@1.4.0 
│ │ ├── growl@1.9.2 
│ │ ├── json3@3.3.2 
│ │ ├─┬ lodash.create@3.1.1 
│ │ │ └── lodash._basecreate@3.0.3 
│ │ └─┬ supports-color@3.1.2 
│ │   └── has-flag@1.0.0 
│ ├─┬ optimist@0.6.1 
│ │ └── wordwrap@0.0.3 
│ ├─┬ proxy-agent@2.0.0 
│ │ ├─┬ agent-base@2.1.1 
│ │ │ └── semver@5.0.3 
│ │ ├── http-proxy-agent@1.0.0 
│ │ ├── https-proxy-agent@1.0.0 
│ │ ├── lru-cache@2.6.5 
│ │ ├─┬ pac-proxy-agent@1.1.0 
│ │ │ ├─┬ get-uri@2.0.1 
│ │ │ │ ├── data-uri-to-buffer@1.2.0 
│ │ │ │ ├── file-uri-to-path@1.0.0 
│ │ │ │ └─┬ ftp@0.3.10 
│ │ │ │   ├─┬ readable-stream@1.1.14 
│ │ │ │   │ ├── isarray@0.0.1 
│ │ │ │   │ └── string_decoder@0.10.31 
│ │ │ │   └── xregexp@2.0.0 
│ │ │ └─┬ pac-resolver@2.0.0 
│ │ │   ├── co@3.0.6 
│ │ │   ├─┬ degenerator@1.0.4 
│ │ │   │ ├── ast-types@0.10.1 
│ │ │   │ ├─┬ escodegen@1.9.0 
│ │ │   │ │ ├── estraverse@4.2.0 
│ │ │   │ │ └─┬ optionator@0.8.2 
│ │ │   │ │   ├── deep-is@0.1.3 
│ │ │   │ │   ├── fast-levenshtein@2.0.6 
│ │ │   │ │   ├── levn@0.3.0 
│ │ │   │ │   ├── prelude-ls@1.1.2 
│ │ │   │ │   ├── type-check@0.3.2 
│ │ │   │ │   └── wordwrap@1.0.0 
│ │ │   │ └── esprima@3.1.3 
│ │ │   ├── ip@1.0.1 
│ │ │   ├── netmask@1.0.6 
│ │ │   └── thunkify@2.1.2 
│ │ └─┬ socks-proxy-agent@2.1.1 
│ │   └─┬ socks@1.1.10 
│ │     ├── ip@1.1.5 
│ │     └── smart-buffer@1.1.15 
│ └── q@1.4.1 
├─┬ redis@2.8.0 
│ ├── double-ended-queue@2.1.0-0 
│ ├── redis-commands@1.3.1 
│ └── redis-parser@2.6.0 
├─┬ socket.io@2.0.4 
│ ├─┬ engine.io@3.1.4 
│ │ ├── accepts@1.3.3 
│ │ ├── base64id@1.0.0 
│ │ ├─┬ engine.io-parser@2.1.1 
│ │ │ ├── after@0.8.2 
│ │ │ ├── arraybuffer.slice@0.0.6 
│ │ │ └── blob@0.0.4 
│ │ ├── uws@0.14.5 
│ │ └─┬ ws@3.3.2 
│ │   ├── async-limiter@1.0.0 
│ │   └── ultron@1.1.1 
│ ├── socket.io-adapter@1.1.1 
│ ├─┬ socket.io-client@2.0.4 
│ │ ├── backo2@1.0.2 
│ │ ├── base64-arraybuffer@0.1.5 
│ │ ├── component-bind@1.0.0 
│ │ ├─┬ engine.io-client@3.1.4 
│ │ │ ├── component-inherit@0.0.3 
│ │ │ ├── xmlhttprequest-ssl@1.5.4 
│ │ │ └── yeast@0.1.2 
│ │ ├── has-cors@1.1.0 
│ │ ├── indexof@0.0.1 
│ │ ├── object-component@0.0.3 
│ │ ├─┬ parseqs@0.0.5 
│ │ │ └─┬ better-assert@1.0.2 
│ │ │   └── callsite@1.0.0 
│ │ ├── parseuri@0.0.5 
│ │ └── to-array@0.1.4 
│ └─┬ socket.io-parser@3.1.2 
│   ├── has-binary2@1.0.2 
│   └── isarray@2.0.1 
├─┬ superagent@3.8.1 
│ ├── component-emitter@1.2.1 
│ ├── cookiejar@2.1.1 
│ ├── debug@3.1.0 
│ ├── extend@3.0.1 
│ ├─┬ form-data@2.3.1 
│ │ └── asynckit@0.4.0 
│ ├── formidable@1.1.1 
│ └─┬ readable-stream@2.3.3 
│   ├── core-util-is@1.0.2 
│   ├── isarray@1.0.0 
│   ├── process-nextick-args@1.0.7 
│   ├── string_decoder@1.0.3 
│   └── util-deprecate@1.0.2 
└─┬ touch@3.1.0 
  └─┬ nopt@1.0.10 
    └── abbrev@1.1.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN frappe@ No description
Traceback (most recent call last):
  File ".local/bin/bench", line 11, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/cli.py", line 40, in cli
    bench_command()
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/commands/make.py", line 21, in init
    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/utils.py", line 74, in init
    set_all_patches_executed(bench_path=path)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/patches/__init__.py", line 38, in set_all_patches_executed
    with open(source_patch_file, 'r') as sf:
IOError: [Errno 2] No such file or directory: '/home/frappe/.local/lib/python2.7/site-packages/bench/patches/patches.txt'
```

**Comment by jodeq** [comment]
Same beahavior in ubuntu 16.04
```Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 11, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/cli.py", line 40, in cli
    bench_command()
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/commands/make.py", line 21, in init
    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/utils.py", line 74, in init
    set_all_patches_executed(bench_path=path)
  File "/home/frappe/.local/lib/python2.7/site-packages/bench/patches/__init__.py", line 38, in set_all_patches_executed
    with open(source_patch_file, 'r') as sf:
IOError: [Errno 2] No such file or directory: '/home/frappe/.local/lib/python2.7/site-packages/bench/patches/patches.txt'
```

**Comment by achillesrasquinha** [comment]
Hi, will get back on this within the week. Meanwhile, use the prior issues. I've diagnosed the same #518

**Comment by lsantyago** [comment]
Hi, do you have an ETA to resolve this issue ? I am trying to install the bench in Mac OS High Sierra, any other workaround to fix the bench init ??

**Comment by codingCoffee** [comment]
Try installing bench using the method below:
```
git clone https://github.com/frappe/bench
pip install --user ./bench
bench init frappe-bench
```

**Comment by gavindsouza** [comment]
Currently, the only supported way of setting up bench is via the easy install script or manually installing it. Both of which rely on cloning the repository and installing it via `pip`. Unless someone's up to take up the task for packaging everything, this will be the only supported way now onwards.

**Comment by haexhub** [comment]
When I follow the instruction from @codingCoffee I get the following error message:

> ERROR: frappe-bench/apps/frappe is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+)
