### ISSUE TITLE
[frappe-bench] Update Mac OS X Wiki

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/bench#519]
**OS Version** - Mac OS X (High Sierra) - 10.13 +
**Dependencies** - 
* gdbm: stable 1.13 (bottled)
* mariadb: stable 10.2.11 (bottled), devel 10.3.2
* redis: stable 4.0.6 (bottled), HEAD
* python: stable 2.7.14 (bottled)

**Error Log**

```Kenneths-MacBook-Pro:~ kenneth$ cd Work
Kenneths-MacBook-Pro:Work kenneth$ ls
erpnext         frappe-bench
Kenneths-MacBook-Pro:Work kenneth$ cd frappe-bench
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
Aborting!

Cleaning up...
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ rm -rf /tmp/mysql.sock
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
Aborting!

Cleaning up...
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Enter current password for root (enter for none): 
Aborting!

Cleaning up...
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ 
Kenneths-MacBook-Pro:frappe-bench kenneth$ brew services resta
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
Kenneths-MacBook-Pro:frappe-bench kenneth$ bre
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Kenneths-MacBook-Pro:frappe-bench kenneth$ rm -rf /tmp/mysql.sock
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Kenneths-MacBook-Pro:frappe-bench kenneth$ brew services restart mariadb
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 14 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Tapped 0 formulae (43 files, 55.4KB)
==> Successfully started `mariadb` (label: homebrew.mxcl.mariadb)
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.2.11-MariaDB Homebrew

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql_secure_installation
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 936, in connect
    self._request_authentication()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1156, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Enter current password for root (enter for none): 
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] Y   
New password: 
Re-enter new password: 
Password updated successfully!
Reloading privilege tables..
 ... Success!


By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] 
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] 
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] 
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
innodb-file-format=barracuda
configured to use the Barracuda storage engine. 
Please add the settings below to MariaDB's my.cnf, restart MariaDB then 
run `bench new-site foo.bar` again.


[mysqld]
innodb-file-format=barracuda
innodb-file-per-table=1
innodb-large-prefix=1
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4

================================================================================
Kenneths-MacBook-Pro:frappe-bench kenneth$ touch ~/.my.cnf
Kenneths-MacBook-Pro:frappe-bench kenneth$ vim ~/.my.cnf
Kenneths-MacBook-Pro:frappe-bench kenneth$ brew services restart mariadb
Stopping `mariadb`... (might take a while)
==> Successfully stopped `mariadb` (label: homebrew.mxcl.mariadb)
==> Successfully started `mariadb` (label: homebrew.mxcl.mariadb)
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
[mysqld]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root 
error: Found option without preceding group in config file: /Users/kenneth/.my.cnf at line: 1
Fatal error in defaults handling. Program aborted
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root -p 
Kenneths-MacBook-Pro:frappe-bench kenneth$ vim ~/.my.cnf
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Kenneths-MacBook-Pro:frappe-bench kenneth$ mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 9
Server version: 10.2.11-MariaDB Homebrew

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
Kenneths-MacBook-Pro:frappe-bench kenneth$ brew services restart mariadb
Stopping `mariadb`... (might take a while)
==> Successfully stopped `mariadb` (label: homebrew.mxcl.mariadb)
==> Successfully started `mariadb` (label: homebrew.mxcl.mariadb)
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 34, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/commands/site.py", line 65, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 549, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/apps/frappe/frappe/database.py", line 86, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/kenneth/Work/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 61] Connection refused)")
Kenneths-MacBook-Pro:frappe-bench kenneth$ bench new-site foo.bar --force
MySQL root password: 

Installing frappe...```


**Improvements**

* change mariadb password
* do mysql_secure_installation
* had to force create new site

**Comment by gavindsouza** [comment]
This doesn't replicate currently. Closing this issue.
