### ISSUE TITLE
bench set-default-site error frappe command not found

### ISSUE THREAD

**Issue by carlos22** [frappe/bench#559]
```

frappe@erpnext:~$ bench set-default-site erpnext.example.com
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/utils.py", line 71, in set_default_site
    set_default_site(site)
  File "/home/frappe/.bench/bench/utils.py", line 408, in set_default_site
    if not site in get_sites(bench_path=bench_path):
  File "/home/frappe/.bench/bench/utils.py", line 219, in get_sites
    sites = [site for site in os.listdir(sites_dir)
OSError: [Errno 2] No such file or directory: './sites'
frappe@erpnext:~$ 
```

Clean install using easy install method on Ubuntu 16.04.
bench version: 4.1.0

**Comment by raghukamath** [comment]
you are not running the commands inside the frappe-bench folder , please check by changing to the appropriate folder

**Comment by carlos22** [comment]
Ok thanks. That helps.
