### ISSUE TITLE
EasyInstall broken

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#575]
**EayyInstall currently doesn't work.** 
Tested on DigitalOcean: 1 GB Memory / 25 GB Disk / LON1 - Ubuntu 16.04.3 x64

For details see latest post below.

**Comment by skanel** [comment]
I have succeed for this installation.
1. make sure you run this `sudo python install.py --develop --user frappe` with other ubuntu user not a `frappe` user
2. your `frappe`user is normal user not administrator user 

Hope this help.

**Comment by dottenbr** [comment]
I can not confirm this works. As root on a digitalocean droplet:

### Commands:

sudo apt-get update -y
sudo apt-get upgrade -y
apt-get install python-minimal -y
apt-get install build-essential python-setuptools -y

python install.py --develop --user frappe

### Output:

```
TASK [init bench] ***********************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "init", "/home/frappe/frappe-bench", "--frappe-branch", "develop"], "delta": "0:04:12.882400", "end": "2018-02-21 08:29:39.495030", "failed": true, "rc": 1, "start": "2018-02-21 08:25:26.612630", "stderr": "INFO:bench.utils:virtualenv -q env -p /usr/bin/python\nINFO:bench.utils:./env/bin/pip -q install --upgrade pip\nINFO:bench.utils:./env/bin/pip -q install wheel\nINFO:bench.utils:./env/bin/pip -q install six\nINFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit\nINFO:bench.app:getting app frappe\nINFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch develop  --origin upstream\nCloning into 'frappe'...\nINFO:bench.app:installing frappe\nINFO:bench.utils:/home/frappe/frappe-bench/env/bin/pip install -q  -e /home/frappe/frappe-bench/apps/frappe --no-cache-dir\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 94, in <module>\n    main()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 697, in main\n    rv = self.invoke(ctx)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 535, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py\", line 23, in build\n    frappe.build.bundle(no_compress, make_copy=make_copy, restore = restore, verbose=verbose)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/build.py\", line 35, in bundle\n    subprocess.call(command.split(\" \"), cwd=frappe_app_path)\n  File \"/usr/lib/python2.7/subprocess.py\", line 523, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/usr/lib/python2.7/subprocess.py\", line 711, in __init__\n    errread, errwrite)\n  File \"/usr/lib/python2.7/subprocess.py\", line 1343, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory", "stderr_lines": ["INFO:bench.utils:virtualenv -q env -p /usr/bin/python", "INFO:bench.utils:./env/bin/pip -q install --upgrade pip", "INFO:bench.utils:./env/bin/pip -q install wheel", "INFO:bench.utils:./env/bin/pip -q install six", "INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit", "INFO:bench.app:getting app frappe", "INFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch develop  --origin upstream", "Cloning into 'frappe'...", "INFO:bench.app:installing frappe", "INFO:bench.utils:/home/frappe/frappe-bench/env/bin/pip install -q  -e /home/frappe/frappe-bench/apps/frappe --no-cache-dir", "Traceback (most recent call last):", "  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main", "    \"__main__\", fname, loader, pkg_name)", "  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code", "    exec code in run_globals", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 94, in <module>", "    main()", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main", "    click.Group(commands=commands)(prog_name='bench')", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 722, in __call__", "    return self.main(*args, **kwargs)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 697, in main", "    rv = self.invoke(ctx)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 895, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 535, in invoke", "    return callback(*args, **kwargs)", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py\", line 23, in build", "    frappe.build.bundle(no_compress, make_copy=make_copy, restore = restore, verbose=verbose)", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/build.py\", line 35, in bundle", "    subprocess.call(command.split(\" \"), cwd=frappe_app_path)", "  File \"/usr/lib/python2.7/subprocess.py\", line 523, in call", "    return Popen(*popenargs, **kwargs).wait()", "  File \"/usr/lib/python2.7/subprocess.py\", line 711, in __init__", "    errread, errwrite)", "  File \"/usr/lib/python2.7/subprocess.py\", line 1343, in _execute_child", "    raise child_exception", "OSError: [Errno 2] No such file or directory"], "stdout": "Already using interpreter /usr/bin/python\n('installing', u'frappe')\nUpdating node libraries...\nPlease install yarn using below command and try again.\n`npm install -g yarn`", "stdout_lines": ["Already using interpreter /usr/bin/python", "('installing', u'frappe')", "Updating node libraries...", "Please install yarn using below command and try again.", "`npm install -g yarn`"]}
	to retry, use: --limit @/tmp/.bench/playbooks/develop/install.retry

PLAY RECAP ******************************************************************************************
localhost                  : ok=40   changed=26   unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 386, in <module>
    install_bench(args)
  File "install.py", line 109, in install_bench
    run_playbook('develop/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 324, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'develop/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```

**Comment by skanel** [comment]
could you try this step and see which one is error happen?
https://discuss.erpnext.com/t/guide-manual-install-erpnext-on-ubuntu-16-xx-debian-v8-9/22596

**Comment by rmehta** [comment]
@codingCoffee @netchampfaris

**Comment by codingCoffee** [comment]
@dottenbr can you test again

**Comment by dottenbr** [comment]
I will try in 30 minutes and I willlet you know. Did you test it successfully?

**Comment by codingCoffee** [comment]
Yup, it was successful when I tested it

**Comment by dottenbr** [comment]
**You have fixed it, thank you** @codingCoffee 
Successfully tested 14:37 CET.

These are the steps on a clean DigitalOcean Droplet (1 GB Memory / 25 GB Disk / LON1 - Ubuntu 16.04.3 x64)

```
# SSH into the machine
ssh root@machineip

# Prerequisites
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install python-minimal -y
sudo apt-get install build-essential python-setuptools -y

# Adding Frappe User as sudoer and switching into it
sudo adduser frappe
usermod -aG sudo frappe
su frappe
cd /home/frappe/

# Easyinstaller
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
sudo python install.py --develop
```

**Comment by dottenbr** [comment]
As far as I see it if you `bench start` right after installing it with easy installer it won't work.

<img width="1552" alt="screen shot 2018-02-21 at 2 42 19 pm" src="https://user-images.githubusercontent.com/9136094/36483432-63d32e60-1716-11e8-9119-8a1ad81c078a.png">

After a `bench update` and then `bench start` all seems good.

**Comment by skanel** [comment]
for my case I can install and make erpnext up running , 
but when I am going to use `bench new-app meeting ` command for example it raise error.

could you please check this command from your env?

**Comment by dottenbr** [comment]
@codingCoffee while EasyInstall works it doesn't get you a working erpnext setup. Please check it out, it breaks and I think this is still yarn-related. At the moment it doesn't seem possible to set up a working environment with easy install. I tried all day and failed.

I will now try a manual setup.

**Comment by dottenbr** [comment]
Do we need to add installing yarn as a prerequisite?

https://yarnpkg.com/lang/en/docs/install/

**Comment by codingCoffee** [comment]
@dottenbr I'll take a look into. Could you just help me replicate the issue.. Did you you use the `develop` flag or the `production` one ? 
Yes yarn should be a prereq now.

**Comment by dottenbr** [comment]
@netchampfaris I can confirm that EasyInstaller with --production works and sets up a functioning frappe with erpnext.

```
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install python-minimal -y
sudo apt-get install build-essential python-setuptools -y
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
python install.py --production --user frappe
```
