### ISSUE TITLE
Dependency issue with transform-object-rest-spread

### ISSUE THREAD

**Issue by lasalesi** [frappe/bench#576]
### Actual behaviour
Installation on a vanilla Debian 8.7 / Ubuntu 16.04 using the Easy Install script for --production succeeds but fails to correctly build sites/assets/js files 
bench build fails with the error 

    Cannot babelify /home/frappe/frappe-bench/apps/erpnext/erpnext/stock/dashboard/item_dashboard.js
    ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/home/frappe/frappe-bench/sites"
        at /home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
        at Array.map (native)
        at Function.normalisePlugins (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
        at OptionManager.mergeOptions (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
        at OptionManager.init (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/home/frappe/frappe-bench/apps/frappe/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at babelify (/home/frappe/frappe-bench/apps/frappe/frappe/build.js:161:16)
        at get_compiled_file (/home/frappe/frappe-bench/apps/frappe/frappe/build.js:148:18)

This can be resolved by manually installing

    sudo npm install babel-plugin-transform-object-rest-spread
    sudo npm install babel-preset-env

### Expected behaviour
Installation script ends up with a correctly installed system including all dependecies.

### Observed in
b77434b (Frappe 10.0.25/ERPNext 10.0.23)

**Comment by tenninjas** [comment]
On install right now I am duplicating this error. Please investigate more fully.
