### ISSUE TITLE
[urgent] bench error when run create new-app command

### ISSUE THREAD

**Issue by skanel** [frappe/bench#577]
Hi , 

I get an error when I ran this command , please check the snapshot
```
frappe@kanel-VirtualBox:~/frappe-bench$ bench new-app meeting
INFO:bench.app:creating new app meeting
App Title (default: Meeting): 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 457, in make_app
    make_boilerplate(destination, app_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/boilerplate.py", line 28, in make_boilerplate
    hook_val = cstr(input(key + ": "))
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by dottenbr** [comment]
@skanel use "```" before the code and after the code to format it as such. Makes it much more readable.

**Comment by achillesrasquinha** [comment]
Hi there, fixed! Sorry about that. :) Please update to latest.
