### ISSUE TITLE
Fails during mgiration

### ISSUE THREAD

**Issue by achillesrasquinha** [frappe/bench#591]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/lib64/python3.6/base64.py", line 9, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by achillesrasquinha** [comment]
`migrate-env` must handle bench port as well

**Comment by gavindsouza** [comment]
Need more information to replicate this. Closing this issue. Open a new one if it still persists.
