### ISSUE TITLE
install.py fails because npm dependency unmet

### ISSUE THREAD

**Issue by oxwivi** [frappe/bench#610]
```
TASK [nodejs : Install yarn] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "npm install -g yarn", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

RUNNING HANDLER [mariadb : restart mysql] **************************************
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=48   changed=33   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 387, in <module>
    install_bench(args)
  File "install.py", line 109, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 325, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```
It should be one of the dependencies automatically installed by the script before this step.

**Comment by oxwivi** [comment]
Okay, `nodejs` should've installed `npm`, but this is what the script outputs before the `npm` step:
```
TASK [nodejs : Add apt key for node repo] **************************************
changed: [localhost]

TASK [nodejs : Add repo] *******************************************************
changed: [localhost]

TASK [nodejs : Install nodejs 6.x] *********************************************
changed: [localhost]

TASK [nodejs : Install yarn] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "npm install -g yarn", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
After facing this error and manually installing `npm`, the script outputs:
```
TASK [nodejs : Add apt key for node repo] **************************************
ok: [localhost]

TASK [nodejs : Add repo] *******************************************************
ok: [localhost]

TASK [nodejs : Install nodejs 6.x] *********************************************
ok: [localhost]
```
Maybe it didn't do `apt update` before installing `nodejs`?

**Comment by oxwivi** [comment]
I've found another `node` related issue on `TASK [bench : python2 bench init for production]`, it runs `bench init /home/frappe/frappe-bench --frappe-branch master`, and here's a clean output from manually running the command after script failed:
```
frappe@ubuntu:~$ bench init /home/frappe/frappe-bench --frappe-branch master
INFO:bench.utils:virtualenv -q env -p /usr/bin/python
Already using interpreter /usr/bin/python
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install six
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch master  --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 143316, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 143316 (delta 56), reused 93 (delta 45), pack-reused 143194
Receiving objects: 100% (143316/143316), 140.74 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (108007/108007), done.
Checking connectivity... done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:/home/frappe/frappe-bench/env/bin/pip install -q  -e /home/frappe/frappe-bench/apps/frappe --no-cache-dir
Updating node packages...
INFO:bench.utils:npm install
loadDep:uuid → resolveWit ▐ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","npnpm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> uws@9.14.0 install /home/frappe/frappe-bench/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> chromedriver@2.37.0 install /home/frappe/frappe-bench/node_modules/chromedriver
> node install.js

sh: 1: node: not found
frappe@ /home/frappe/frappe-bench
├─┬ babel-core@6.26.0 
│ ├─┬ babel-code-frame@6.26.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@3.0.2 
│ ├─┬ babel-generator@6.26.1 
│ │ ├─┬ detect-indent@4.0.0 
│ │ │ └─┬ repeating@2.0.1 
│ │ │   └─┬ is-finite@1.0.2 
│ │ │     └── number-is-nan@1.0.1 
│ │ ├── jsesc@1.3.0 
│ │ └── trim-right@1.0.1 
│ ├── babel-helpers@6.24.1 
│ ├── babel-messages@6.23.0 
│ ├─┬ babel-register@6.26.0 
│ │ ├── core-js@2.5.3 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ ├── os-homedir@1.0.2 
│ │ │ └── os-tmpdir@1.0.2 
│ │ └── source-map-support@0.4.18 
│ ├─┬ babel-runtime@6.26.0 
│ │ └── regenerator-runtime@0.11.1 
│ ├── babel-template@6.26.0 
│ ├─┬ babel-traverse@6.26.0 
│ │ └── globals@9.18.0 
│ ├─┬ babel-types@6.26.0 
│ │ └── to-fast-properties@1.0.3 
│ ├── babylon@6.18.0 
│ ├── convert-source-map@1.5.1 
│ ├─┬ debug@2.6.9 
│ │ └── ms@2.0.0 
│ ├── json5@0.5.1 
│ ├── lodash@4.17.5 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.11 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├── path-is-absolute@1.0.1 
│ ├── private@0.1.8 
│ ├── slash@1.0.0 
│ └── source-map@0.5.7 
├─┬ babel-plugin-transform-object-rest-spread@6.26.0 
│ └── babel-plugin-syntax-object-rest-spread@6.13.0 
├─┬ babel-preset-env@1.6.1 
│ ├── babel-plugin-check-es2015-constants@6.22.0 
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0 
│ ├─┬ babel-plugin-transform-async-to-generator@6.24.1 
│ │ ├── babel-helper-remap-async-to-generator@6.24.1 
│ │ └── babel-plugin-syntax-async-functions@6.13.0 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 
│ ├── babel-plugin-transform-es2015-block-scoping@6.26.0 
│ ├─┬ babel-plugin-transform-es2015-classes@6.24.1 
│ │ ├── babel-helper-define-map@6.26.0 
│ │ ├── babel-helper-function-name@6.24.1 
│ │ ├── babel-helper-optimise-call-expression@6.24.1 
│ │ └── babel-helper-replace-supers@6.24.1 
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 
│ ├── babel-plugin-transform-es2015-for-of@6.23.0 
│ ├── babel-plugin-transform-es2015-function-name@6.24.1 
│ ├── babel-plugin-transform-es2015-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.26.0 
│ │ └── babel-plugin-transform-strict-mode@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.24.1 
│ │ └── babel-helper-hoist-variables@6.24.1 
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.1 
│ ├── babel-plugin-transform-es2015-object-super@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1 
│ │ ├── babel-helper-call-delegate@6.24.1 
│ │ └── babel-helper-get-function-arity@6.24.1 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-spread@6.22.0 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1 
│ │ └── babel-helper-regex@6.26.0 
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.24.1 
│ │ └─┬ regexpu-core@2.0.0 
│ │   ├── regenerate@1.3.3 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ ├─┬ babel-plugin-transform-exponentiation-operator@6.24.1 
│ │ ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.24.1 
│ │ │ └── babel-helper-explode-assignable-expression@6.24.1 
│ │ └── babel-plugin-syntax-exponentiation-operator@6.13.0 
│ ├─┬ babel-plugin-transform-regenerator@6.26.0 
│ │ └── regenerator-transform@0.10.1 
│ ├─┬ browserslist@2.11.3 
│ │ ├── caniuse-lite@1.0.30000820 
│ │ └── electron-to-chromium@1.3.40 
│ ├─┬ invariant@2.2.4 
│ │ └── loose-envify@1.3.1 
│ └── semver@5.5.0 
├─┬ babel-preset-minify@0.2.0 
│ ├─┬ babel-plugin-minify-builtins@0.2.0 
│ │ └── babel-helper-evaluate-path@0.2.0 
│ ├── babel-plugin-minify-constant-folding@0.2.0 
│ ├─┬ babel-plugin-minify-dead-code-elimination@0.2.0 
│ │ ├── babel-helper-mark-eval-scopes@0.2.0 
│ │ ├── babel-helper-remove-or-void@0.2.0 
│ │ └── lodash.some@4.6.0 
│ ├─┬ babel-plugin-minify-flip-comparisons@0.2.0 
│ │ └── babel-helper-is-void-0@0.2.0 
│ ├─┬ babel-plugin-minify-guarded-expressions@0.2.0 
│ │ └── babel-helper-flip-expressions@0.2.0 
│ ├── babel-plugin-minify-infinity@0.2.0 
│ ├── babel-plugin-minify-mangle-names@0.2.0 
│ ├── babel-plugin-minify-numeric-literals@0.2.0 
│ ├── babel-plugin-minify-replace@0.2.0 
│ ├─┬ babel-plugin-minify-simplify@0.2.0 
│ │ ├── babel-helper-is-nodes-equiv@0.0.1 
│ │ └── babel-helper-to-multiple-sequence-expressions@0.2.0 
│ ├── babel-plugin-minify-type-constructors@0.2.0 
│ ├── babel-plugin-transform-inline-consecutive-adds@0.2.0 
│ ├── babel-plugin-transform-member-expression-literals@6.9.0 
│ ├── babel-plugin-transform-merge-sibling-variables@6.9.0 
│ ├── babel-plugin-transform-minify-booleans@6.9.0 
│ ├── babel-plugin-transform-property-literals@6.9.0 
│ ├── babel-plugin-transform-regexp-constructors@0.2.0 
│ ├── babel-plugin-transform-remove-console@6.9.0 
│ ├── babel-plugin-transform-remove-debugger@6.9.0 
│ ├── babel-plugin-transform-remove-undefined@0.2.0 
│ ├── babel-plugin-transform-simplify-comparison-operators@6.9.0 
│ ├── babel-plugin-transform-undefined-to-void@6.9.0 
│ └── lodash.isplainobject@4.0.6 
├─┬ chokidar@1.7.0 
│ ├─┬ anymatch@1.3.2 
│ │ ├─┬ micromatch@2.3.11 
│ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ └── arr-flatten@1.1.0 
│ │ │ ├── array-unique@0.2.1 
│ │ │ ├─┬ braces@1.8.5 
│ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │   ├─┬ randomatic@1.1.7 
│ │ │ │ │   │ ├─┬ is-number@3.0.0 
│ │ │ │ │   │ │ └── kind-of@3.2.2 
│ │ │ │ │   │ └── kind-of@4.0.0 
│ │ │ │ │   └── repeat-string@1.6.1 
│ │ │ │ ├── preserve@0.2.0 
│ │ │ │ └── repeat-element@1.1.2 
│ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ ├── extglob@0.3.2 
│ │ │ ├── filename-regex@2.0.1 
│ │ │ ├─┬ kind-of@3.2.2 
│ │ │ │ └── is-buffer@1.1.6 
│ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ ├─┬ for-own@0.1.5 
│ │ │ │ │ └── for-in@1.0.2 
│ │ │ │ └── is-extendable@0.1.1 
│ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ ├── glob-base@0.3.0 
│ │ │ │ └── is-dotfile@1.0.3 
│ │ │ └─┬ regex-cache@0.4.4 
│ │ │   └─┬ is-equal-shallow@0.1.3 
│ │ │     └── is-primitive@2.0.0 
│ │ └─┬ normalize-path@2.1.1 
│ │   └── remove-trailing-separator@1.1.0 
│ ├── async-each@1.0.1 
│ ├── glob-parent@2.0.0 
│ ├── inherits@2.0.3 
│ ├─┬ is-binary-path@1.0.1 
│ │ └── binary-extensions@1.11.0 
│ ├─┬ is-glob@2.0.1 
│ │ └── is-extglob@1.0.0 
│ └─┬ readdirp@2.1.0 
│   └── set-immediate-shim@1.0.1 
├── cookie@0.3.1 
├─┬ express@4.16.3 
│ ├─┬ accepts@1.3.5 
│ │ ├─┬ mime-types@2.1.18 
│ │ │ └── mime-db@1.33.0 
│ │ └── negotiator@0.6.1 
│ ├── array-flatten@1.1.1 
│ ├─┬ body-parser@1.18.2 
│ │ ├── bytes@3.0.0 
│ │ ├─┬ http-errors@1.6.2 
│ │ │ ├── depd@1.1.1 
│ │ │ └── setprototypeof@1.0.3 
│ │ ├── iconv-lite@0.4.19 
│ │ └── raw-body@2.3.2 
│ ├── content-disposition@0.5.2 
│ ├── content-type@1.0.4 
│ ├── cookie-signature@1.0.6 
│ ├── depd@1.1.2 
│ ├── encodeurl@1.0.2 
│ ├── escape-html@1.0.3 
│ ├── etag@1.8.1 
│ ├─┬ finalhandler@1.1.1 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.5.2 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.2 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@2.0.3 
│ │ ├── forwarded@0.1.2 
│ │ └── ipaddr.js@1.6.0 
│ ├── qs@6.5.1 
│ ├── range-parser@1.2.0 
│ ├── safe-buffer@5.1.1 
│ ├─┬ send@0.16.2 
│ │ └── destroy@1.0.4 
│ ├── serve-static@1.13.2 
│ ├── setprototypeof@1.1.0 
│ ├── statuses@1.4.0 
│ ├─┬ type-is@1.6.16 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.1 
│ └── vary@1.1.2 
├─┬ less@2.7.3 
│ ├─┬ errno@0.1.7 
│ │ └── prr@1.0.1 
│ ├── graceful-fs@4.1.11 
│ ├── image-size@0.5.5 
│ ├── mime@1.4.1 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ promise@7.3.1 
│ │ └── asap@2.0.6 
│ └─┬ request@2.81.0 
│   ├── aws-sign2@0.6.0 
│   ├── aws4@1.6.0 
│   ├── caseless@0.12.0 
│   ├─┬ combined-stream@1.0.6 
│   │ └── delayed-stream@1.0.0 
│   ├── forever-agent@0.6.1 
│   ├── form-data@2.1.4 
│   ├─┬ har-validator@4.2.1 
│   │ ├─┬ ajv@4.11.8 
│   │ │ ├── co@4.6.0 
│   │ │ └─┬ json-stable-stringify@1.0.1 
│   │ │   └── jsonify@0.0.0 
│   │ └── har-schema@1.0.5 
│   ├─┬ hawk@3.1.3 
│   │ ├── boom@2.10.1 
│   │ ├── cryptiles@2.0.5 
│   │ ├── hoek@2.16.3 
│   │ └── sntp@1.0.9 
│   ├─┬ http-signature@1.1.1 
│   │ ├── assert-plus@0.2.0 
│   │ ├─┬ jsprim@1.4.1 
│   │ │ ├── assert-plus@1.0.0 
│   │ │ ├── extsprintf@1.3.0 
│   │ │ ├── json-schema@0.2.3 
│   │ │ └── verror@1.10.0 
│   │ └─┬ sshpk@1.14.1 
│   │   ├── asn1@0.2.3 
│   │   ├── bcrypt-pbkdf@1.0.1 
│   │   ├── dashdash@1.14.1 
│   │   ├── ecc-jsbn@0.1.1 
│   │   ├── getpass@0.1.7 
│   │   ├── jsbn@0.1.1 
│   │   └── tweetnacl@0.14.5 
│   ├── is-typedarray@1.0.0 
│   ├── isstream@0.1.2 
│   ├── json-stringify-safe@5.0.1 
│   ├── oauth-sign@0.8.2 
│   ├── performance-now@0.2.0 
│   ├── qs@6.4.0 
│   ├── stringstream@0.0.5 
│   ├─┬ tough-cookie@2.3.4 
│   │ └── punycode@1.4.1 
│   ├── tunnel-agent@0.6.0 
│   └── uuid@3.2.1 
├─┬ nightwatch@0.9.20 
│ ├─┬ chai-nightwatch@0.1.1 
│ │ ├── assertion-error@1.0.0 
│ │ └─┬ deep-eql@0.1.3 
│ │   └── type-detect@0.1.1 
│ ├── ejs@2.5.7 
│ ├─┬ lodash.clone@3.0.3 
│ │ ├─┬ lodash._baseclone@3.3.0 
│ │ │ ├── lodash._arraycopy@3.0.0 
│ │ │ ├── lodash._arrayeach@3.0.0 
│ │ │ ├─┬ lodash._baseassign@3.2.0 
│ │ │ │ └── lodash._basecopy@3.0.1 
│ │ │ ├── lodash._basefor@3.0.3 
│ │ │ ├── lodash.isarray@3.0.4 
│ │ │ └─┬ lodash.keys@3.1.2 
│ │ │   ├── lodash._getnative@3.9.1 
│ │ │   └── lodash.isarguments@3.1.0 
│ │ ├── lodash._bindcallback@3.0.1 
│ │ └── lodash._isiterateecall@3.0.9 
│ ├─┬ lodash.defaultsdeep@4.3.2 
│ │ ├── lodash._baseclone@4.5.7 
│ │ ├── lodash._stack@4.1.3 
│ │ ├── lodash.keysin@4.2.0 
│ │ ├── lodash.mergewith@4.6.1 
│ │ └── lodash.rest@4.0.5 
│ ├── minimatch@3.0.3 
│ ├── mkpath@1.0.0 
│ ├─┬ mocha-nightwatch@3.2.2 
│ │ ├── browser-stdout@1.3.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├── diff@1.4.0 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ glob@7.0.5 
│ │ │ ├── fs.realpath@1.0.0 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ └── once@1.4.0 
│ │ ├── growl@1.9.2 
│ │ ├── json3@3.3.2 
│ │ ├─┬ lodash.create@3.1.1 
│ │ │ └── lodash._basecreate@3.0.3 
│ │ └─┬ supports-color@3.1.2 
│ │   └── has-flag@1.0.0 
│ ├─┬ optimist@0.6.1 
│ │ └── wordwrap@0.0.3 
│ ├─┬ proxy-agent@2.0.0 
│ │ ├─┬ agent-base@2.1.1 
│ │ │ └── semver@5.0.3 
│ │ ├── http-proxy-agent@1.0.0 
│ │ ├── https-proxy-agent@1.0.0 
│ │ ├── lru-cache@2.6.5 
│ │ ├─┬ pac-proxy-agent@1.1.0 
│ │ │ ├─┬ get-uri@2.0.1 
│ │ │ │ ├── data-uri-to-buffer@1.2.0 
│ │ │ │ ├── file-uri-to-path@1.0.0 
│ │ │ │ └─┬ ftp@0.3.10 
│ │ │ │   ├─┬ readable-stream@1.1.14 
│ │ │ │   │ ├── isarray@0.0.1 
│ │ │ │   │ └── string_decoder@0.10.31 
│ │ │ │   └── xregexp@2.0.0 
│ │ │ └─┬ pac-resolver@2.0.0 
│ │ │   ├── co@3.0.6 
│ │ │   ├─┬ degenerator@1.0.4 
│ │ │   │ ├── ast-types@0.11.3 
│ │ │   │ ├─┬ escodegen@1.9.1 
│ │ │   │ │ ├── estraverse@4.2.0 
│ │ │   │ │ ├─┬ optionator@0.8.2 
│ │ │   │ │ │ ├── deep-is@0.1.3 
│ │ │   │ │ │ ├── fast-levenshtein@2.0.6 
│ │ │   │ │ │ ├── levn@0.3.0 
│ │ │   │ │ │ ├── prelude-ls@1.1.2 
│ │ │   │ │ │ ├── type-check@0.3.2 
│ │ │   │ │ │ └── wordwrap@1.0.0 
│ │ │   │ │ └── source-map@0.6.1 
│ │ │   │ └── esprima@3.1.3 
│ │ │   ├── ip@1.0.1 
│ │ │   ├── netmask@1.0.6 
│ │ │   └── thunkify@2.1.2 
│ │ └─┬ socks-proxy-agent@2.1.1 
│ │   └─┬ socks@1.1.10 
│ │     ├── ip@1.1.5 
│ │     └── smart-buffer@1.1.15 
│ └── q@1.4.1 
├─┬ redis@2.8.0 
│ ├── double-ended-queue@2.1.0-0 
│ ├── redis-commands@1.3.5 
│ └── redis-parser@2.6.0 
├─┬ socket.io@2.0.4 
│ ├─┬ engine.io@3.1.5 
│ │ ├── base64id@1.0.0 
│ │ ├── debug@3.1.0 
│ │ ├─┬ engine.io-parser@2.1.2 
│ │ │ ├── after@0.8.2 
│ │ │ ├── arraybuffer.slice@0.0.7 
│ │ │ └── blob@0.0.4 
│ │ ├── uws@9.14.0 
│ │ └─┬ ws@3.3.3 
│ │   ├── async-limiter@1.0.0 
│ │   └── ultron@1.1.1 
│ ├── socket.io-adapter@1.1.1 
│ ├─┬ socket.io-client@2.0.4 
│ │ ├── backo2@1.0.2 
│ │ ├── base64-arraybuffer@0.1.5 
│ │ ├── component-bind@1.0.0 
│ │ ├─┬ engine.io-client@3.1.6 
│ │ │ ├── component-inherit@0.0.3 
│ │ │ ├── debug@3.1.0 
│ │ │ ├── xmlhttprequest-ssl@1.5.5 
│ │ │ └── yeast@0.1.2 
│ │ ├── has-cors@1.1.0 
│ │ ├── indexof@0.0.1 
│ │ ├── object-component@0.0.3 
│ │ ├─┬ parseqs@0.0.5 
│ │ │ └─┬ better-assert@1.0.2 
│ │ │   └── callsite@1.0.0 
│ │ ├── parseuri@0.0.5 
│ │ └── to-array@0.1.4 
│ └─┬ socket.io-parser@3.1.3 
│   ├── debug@3.1.0 
│   ├── has-binary2@1.0.2 
│   └── isarray@2.0.1 
├─┬ superagent@3.8.2 
│ ├── component-emitter@1.2.1 
│ ├── cookiejar@2.1.1 
│ ├── debug@3.1.0 
│ ├── extend@3.0.1 
│ ├─┬ form-data@2.3.2 
│ │ └── asynckit@0.4.0 
│ ├── formidable@1.2.1 
│ └─┬ readable-stream@2.3.5 
│   ├── core-util-is@1.0.2 
│   ├── isarray@1.0.0 
│   ├── process-nextick-args@2.0.0 
│   ├── string_decoder@1.0.3 
│   └── util-deprecate@1.0.2 
└─┬ touch@3.1.0 
  └─┬ nopt@1.0.10 
    └── abbrev@1.1.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN frappe@ No description
npm ERR! Linux 4.4.0-1085-raspi2
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! chromedriver@2.37.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the chromedriver@2.37.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/frappe/frappe-bench/npm-debug.log
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/make.py", line 28, in init
    python 		 = python)
  File "/home/frappe/.bench/bench/utils.py", line 82, in init
    update_node_packages(bench_path=path)
  File "/home/frappe/.bench/bench/utils.py", line 452, in update_node_packages
    update_npm_packages(bench_path)
  File "/home/frappe/.bench/bench/utils.py", line 499, in update_npm_packages
    exec_cmd('npm install', cwd=bench_path)
  File "/home/frappe/.bench/bench/utils.py", line 152, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: npm install
```
To highlight some errors of note:
```
npm ERR! chromedriver@2.37.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the chromedriver@2.37.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
```
It says it can't run `node install.js`, so I tried to find `node` command:
```
$ node
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

**Comment by codingCoffee** [comment]
Fixed. Feel free to reopen if issue persists

**Comment by oxwivi** [comment]
@codingCoffee, on which branch was this fix applied? And was the fix removal of  dependency on `chromedriver`? `bench init --frappe-bench master`s still retrieves it:
```
$  bench init --frappe-branch master bench
INFO:bench.utils:virtualenv -q env -p /usr/bin/python
INFO:bench.utils:env/bin/pip -q install --upgrade pip
INFO:bench.utils:env/bin/pip -q install wheel
INFO:bench.utils:env/bin/pip -q install six
INFO:bench.utils:env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch master  --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 161446 (delta 21), reused 15 (delta 6), pack-reused 161379
Receiving objects: 100% (161446/161446), 191.78 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (122740/122740), done.
Checking out files: 100% (2416/2416), done.
installing frappe
INFO:bench.app:installing frappe
INFO:bench.utils:bench/env/bin/pip install -q  -e bench/apps/frappe 
  Failed building wheel for openpyxl
INFO:bench.app:getting app frappe_io
INFO:bench.utils:git clone https://github.com/frappe/frappe_io --branch master  --origin upstream
Cloning into 'frappe_io'...
remote: Enumerating objects: 455, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (363/363), done.
remote: Total 6650 (delta 104), reused 269 (delta 89), pack-reused 6195
Receiving objects: 100% (6650/6650), 36.68 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (4692/4692), done.
Checking out files: 100% (713/713), done.
installing frappe_io
INFO:bench.app:installing frappe_io
INFO:bench.utils:bench/env/bin/pip install -q  -e bench/apps/frappe_io 
Updating node packages...
INFO:bench.utils:npm install

> chromedriver@2.45.0 install /home/frappe/bench/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
Saving to file: /tmp/chromedriver/chromedriver_linux64.zip
Received 782K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3918K...
Received 4702K...
Received 5264K total.
Extracting zip contents
Copying to target path /home/frappe/bench/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/frappe/bench/node_modules/chromedriver/lib/chromedriver/chromedriver
[...]
```
