### ISSUE TITLE
Error on npm when  run bench init

### ISSUE THREAD

**Issue by fellipeh** [frappe/bench#622]
I start to get these error:

```
INFO:bench.utils:virtualenv -q env -p /usr/bin/python
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install six
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 144599, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 144599 (delta 2), reused 3 (delta 1), pack-reused 144589
Receiving objects: 100% (144599/144599), 145.70 MiB | 115.00 KiB/s, done.
Resolving deltas: 100% (109061/109061), done.
Checking out files: 100% (2568/2568), done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:../frappe-bench/env/bin/pip install -q  -e ../frappe-bench/apps/frappe --no-cache-dir
Updating node packages...
Please install yarn using below command and try again.
`npm install -g yarn`
Please install yarn using below command and try again.
npm install -g yarn

> frappe@ production /Users/fellipeh/Developer/frappe-bench/apps/frappe
> FRAPPE_ENV=production node rollup/build.js

module.js:559
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/fellipeh/Developer/frappe-bench/apps/frappe/rollup/build.js:3:15)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frappe@ production: `FRAPPE_ENV=production node rollup/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frappe@ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 5.8.0    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fellipeh/.npm/_logs/2018-04-04T12_25_33_662Z-debug.log
INFO:bench.utils:setting up backups
INFO:bench.utils:setting up auto update
Bench ../frappe-bench initialized
```

I have the latest version of bench on my system.

**Comment by maxfu9** [comment]
You need to install yarn on your system

**Comment by codingCoffee** [comment]
Run the following:
`bench setup requirements`

**Comment by codingCoffee** [comment]
Closing, feel free if to open if needed
