### ISSUE TITLE
Bench easy install failing

### ISSUE THREAD

**Issue by laughsuggestion** [frappe/bench#633]
The easy install (https://github.com/frappe/bench#easy-install) seems not to be working: 

```
    default:         "Traceback (most recent call last):",
    default:         "  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main",
    default:         "    \"__main__\", mod_spec)",
    default:         "  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code",
    default:         "    exec(code, run_globals)",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>",
    default:         "    main()",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main",
    default:         "    click.Group(commands=commands)(prog_name='bench')",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 722, in __call__",
    default:         "    return self.main(*args, **kwargs)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 697, in main",
    default:         "    rv = self.invoke(ctx)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1066, in invoke",
    default:         "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1066, in invoke",
    default:         "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 895, in invoke",
    default:         "    return ctx.invoke(self.callback, **ctx.params)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 535, in invoke",
    default:         "    return callback(*args, **kwargs)",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/commands/site.py\", line 34, in new_site",
    default:         "    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/commands/site.py\", line 65, in _new_site",
    default:         "    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/installer.py\", line 38, in install_db",
    default:         "    create_database_and_user(force, verbose)",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/installer.py\", line 62, in create_database_and_user",
    default:         "    if force or (db_name not in dbman.get_database_list()):",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/model/db_schema.py\", line 549, in get_database_list",
    default:         "    return [d[0] for d in self.db.sql(\"SHOW DATABASES\")]",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/database.py\", line 165, in sql",
    default:         "    self.connect()",
    default:         "  File \"/home/vagrant/frappe-bench/apps/frappe/frappe/database.py\", line 115, in connect",
    default:         "    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/__init__.py\", line 90, in Connect",
    default:         "    return Connection(*args, **kwargs)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py\", line 699, in __init__",
    default:         "    self.connect()",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py\", line 936, in connect",
    default:         "    self._request_authentication()",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py\", line 1156, in _request_authentication",
    default:         "    auth_packet = self._read_packet()",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py\", line 1018, in _read_packet",
    default:         "    packet.check_error()",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py\", line 384, in check_error",
    default:         "    err.raise_mysql_exception(self._data)",
    default:         "  File \"/home/vagrant/frappe-bench/env/lib/python3.5/site-packages/pymysql/err.py\", line 107, in raise_mysql_exception",
    default:         "    raise errorclass(errno, errval)",
    default:         "pymysql.err.OperationalError: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"
    default:     ],
    default:     "stdout": "",
    default:     "stdout_lines": []
    default: }
    default:    to retry, use: --limit @/tmp/.bench/playbooks/site.retry
```

I have a passwords.txt file with custom passwords that have worked previously.

**Comment by codingCoffee** [comment]
Can you post all the commands you executed, and in which sequence. Also give some details about the server.

**Comment by laughsuggestion** [comment]
Sure, here's a smaller Vagrant file to illustrate how the Easy Install is broken:
https://pastebin.com/K6WYJrRC

Here is the corresponding error:
default: /usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
default:   passwd = fallback_getpass(prompt, stream)
default: Warning: Password input may be echoed.
default: Please enter mysql root password:
default: Warning: Password input may be echoed.
default: Re-enter mysql root password:
default: Traceback (most recent call last):
default:   File "install.py", line 400, in <module>
default:     install_bench(args)
default:   File "install.py", line 106, in install_bench
default:     extra_vars.update(get_passwords(args))
default:   File "install.py", line 272, in get_passwords
default:     conf_mysql_passwd = getpass.unix_getpass(prompt='Re-enter mysql root password: ')
default:   File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
default:
default: passwd = fallback_getpass(prompt, stream)
default:   File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
default:     return _raw_input(prompt, stream)
default:   File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
default:     raise EOFError
default: EOFError
