### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: Procfile

### ISSUE THREAD

**Issue by zodman** [frappe/bench#635]
i install bench from pip

`pip install  https://github.com/frappe/bench/archive/master.zip`

```
Traceback (most recent call last):
  File "/home/zodman/.virtualenvs/erpnext/bin/bench", line 11, in <module>
    load_entry_point('bench==4.1.0', 'console_scripts', 'bench')()
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/bench/cli.py", line 40, in cli
    bench_command()
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/bench/commands/make.py", line 28, in init
    python 		 = python)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/bench/utils.py", line 91, in init
    setup_procfile(path)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/bench/config/procfile.py", line 13, in setup_procfile
    procfile = bench.env.get_template('Procfile').render(
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/zodman/.virtualenvs/erpnext/local/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Procfile

```

the file in bench/templates/Procfile  didnt had extension that because setuptools dont identified as data from package

**Comment by codingCoffee** [comment]
Try:
```
git clone https://github.com/frappe/bench
cd bench
pip install -e .
```
This should help you install for now. We'll look into the issue till then

**Comment by zodman** [comment]
it works because you install from develop mode!
