### ISSUE TITLE
Error when start.. using Enterprise Linux 7

### ISSUE THREAD

**Issue by fellipeh** [frappe/bench#646]
I'm using EL7 and after a make all instalation without problem, I try to start, go to Browser and try to localhost:8000 and receive these error:

```
12:48:44 socketio.1       | listening on *: 9000
12:49:02 web.1            |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
12:49:03 web.1            |  * Restarting with inotify reloader
12:49:04 watch.1          | 
12:49:04 watch.1          | > frappe@ watch /home/fellipeh/developer/frappe/frappe-bench/apps/frappe
12:49:04 watch.1          | > node rollup/watch.js
12:49:04 watch.1          | 
12:49:06 watch.1          | 
12:49:06 watch.1          | Rollup Watcher Started
12:49:06 watch.1          | 
12:49:06 watch.1          | Watching...
12:49:06 web.1            |  * Debugger is active!
12:49:06 web.1            |  * Debugger PIN: 239-931-722
12:49:07 watch.1          | Rebuilding frappe-web.css
12:49:07 watch.1          | Rebuilding frappe-web.min.js
12:49:09 watch.1          | Error in: undefined
12:49:09 watch.1          | Error: watch /home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/public/js/frappe/class.js ENOSPC
12:50:13 web.1            | localhost does not exist
12:50:13 web.1            | ----------------------------------------
12:50:13 web.1            | Exception happened during processing of request from ('127.0.0.1', 41124)
12:50:13 web.1            | Traceback (most recent call last):
12:50:13 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
12:50:13 web.1            |     self.finish_request(request, client_address)
12:50:13 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
12:50:13 web.1            |     self.RequestHandlerClass(request, client_address, self)
12:50:13 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
12:50:13 web.1            |     self.handle()
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
12:50:13 web.1            |     rv = BaseHTTPRequestHandler.handle(self)
12:50:13 web.1            |   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
12:50:13 web.1            |     self.handle_one_request()
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
12:50:13 web.1            |     return self.run_wsgi()
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
12:50:13 web.1            |     execute(self.server.app)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 260, in execute
12:50:13 web.1            |     for data in application_iter:
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 288, in debug_application
12:50:13 web.1            |     app_iter = self.app(environ, start_response)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/middlewares.py", line 15, in __call__
12:50:13 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
12:50:13 web.1            |     return self.app(environ, start_response)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
12:50:13 web.1            |     return self.app(environ, start_response)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
12:50:13 web.1            |     return ClosingIterator(app(environ, start_response), self.cleanup)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 308, in application
12:50:13 web.1            |     resp = f(*args[:-2] + (request,))
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/app.py", line 59, in application
12:50:13 web.1            |     init_request(request)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/app.py", line 110, in init_request
12:50:13 web.1            |     frappe.init(site=site, sites_path=_sites_path)
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 138, in init
12:50:13 web.1            |     local.conf = _dict(get_site_config())
12:50:13 web.1            |   File "/home/fellipeh/developer/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 195, in get_site_config
12:50:13 web.1            |     sys.exit(1)
12:50:13 web.1            | SystemExit: 1
```

**Comment by codingCoffee** [comment]
Did you create a site?
Is your site in `frappe-bench/sites/currentsite.txt` ?
Please post the contents of your `frappe-bench/sites/currentsite.txt` and `/etc/hosts` files

**Comment by fellipeh** [comment]
works now...

The problem is on npm, try to install on "global" so, I force to use root, and when I try to execute as normal user doesn't work.. so aI need to config npm to use user folders for instalations..

Closing...

Thanks!
