### ISSUE TITLE
error in start the bench

### ISSUE THREAD

**Issue by agrameshprasath** [frappe/bench#655]
hi 
i am new to the erpnext
i installed the bench and try to start, but the localhost is not connected
i am installing it in ubuntu 16.04 LTS.
 the following is the error 
```
18:03:50 web.1            | ----------------------------------------
18:03:50 web.1            | localhost does not exist
18:03:50 web.1            | ----------------------------------------
18:03:50 web.1            | Exception happened during processing of request from ('127.0.0.1', 50872)
18:03:50 web.1            | Traceback (most recent call last):
18:03:50 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
18:03:50 web.1            |     self.finish_request(request, client_address)
18:03:50 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
18:03:50 web.1            |     self.RequestHandlerClass(request, client_address, self)
18:03:50 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
18:03:50 web.1            |     self.handle()
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
18:03:50 web.1            |     rv = BaseHTTPRequestHandler.handle(self)
18:03:50 web.1            |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
18:03:50 web.1            |     self.handle_one_request()
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
18:03:50 web.1            |     return self.run_wsgi()
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
18:03:50 web.1            |     execute(self.server.app)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 260, in execute
18:03:50 web.1            |     for data in application_iter:
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 288, in debug_application
18:03:50 web.1            |     app_iter = self.app(environ, start_response)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/middlewares.py", line 15, in __call__
18:03:50 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
18:03:50 web.1            |     return self.app(environ, start_response)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
18:03:50 web.1            |     return self.app(environ, start_response)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
18:03:50 web.1            |     return ClosingIterator(app(environ, start_response), self.cleanup)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 308, in application
18:03:50 web.1            |     resp = f(*args[:-2] + (request,))
18:03:50 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 59, in application
18:03:50 web.1            |     init_request(request)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 110, in init_request
18:03:50 web.1            |     frappe.init(site=site, sites_path=_sites_path)
18:03:50 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 138, in init
18:03:50 web.1            |     local.conf = _dict(get_site_config())
18:03:50 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 195, in get_site_config
18:03:50 web.1            |     sys.exit(1)
18:03:50 web.1            | SystemExit: 1
```

**Comment by codingCoffee** [comment]
Hi, either you don't have an entry for `localhost` in `/etc/hosts`. Or you have not created a `site` yet. It's most likely the latter. Create a new site by using the following command:
`bench new-site site.local`

**Comment by agrameshprasath** [comment]
yes i created the site and enter it in /etc/hosts. but it not run in server

**Comment by codingCoffee** [comment]
Are you still facing the issue? Please post the output of the following commands after going into `frappe-bench` folder:

```
cat /etc/hosts
ls sites
cat sites/currentsite.txt
```

**Comment by agrameshprasath** [comment]
please look the following:

user/user:~/frappe-bench$ **cat /etc/hosts**
127.0.0.1	localhost
127.0.0.1	site1.local
127.0.0.1	site2.local

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters


user/user::~/frappe-bench$ **ls sites**
apps.txt  assets  common_site_config.json  site1.local  site2.local

user/user::~/frappe-bench$ **cat sites/currentsite.txt**
cat: sites/currentsite.txt: No such file or directory

**Comment by codingCoffee** [comment]
You'll have to add an entry for every site you use in `/etc/hosts`. So in this case, since you have 2 sites `site1.local` and `site2.local`, this is what you'll need to do.
Use your text editor of choice to edit the `/etc/hosts` file and add the following line to it. Remember you'll need `sudo` access for the same!
```
127.0.0.1 site1.local site2.local
```
Now, you'll be able to access your sites separately using your browser on the URL http://site1.local:8000 and http://site2.local:8000 

Also please post such queries on the [discuss forum](https://discuss.erpnext.com). Thanks and regards! Closing issue.
