### ISSUE TITLE
Error on erpnext configuration

### ISSUE THREAD

**Issue by agrameshprasath** [frappe/bench#656]
hi 
i tried to run 
$ bench get-app erpnext

This goes ahead and fetches the complete source code and places it within your MY_BENCH/apps/MY_APP_NAME folder. In this case - frappe-bench/apps/erpnext

but i recieved error like followings:
```
~/ErpNext/frappe-bench$ bench get-app erpnext
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/frappe/erpnext HTTP/1.1" 200 None
INFO:bench.app:getting app erpnext
INFO:bench.utils:git clone https://github.com/frappe/erpnext  --depth 1 --origin upstream
fatal: destination path 'erpnext' already exists and is not an empty directory.
Traceback (most recent call last):
  File "/home/ramesh/.local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/usr/local/lib/python2.7/dist-packages/bench-4.1.0-py2.7.egg/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bench-4.1.0-py2.7.egg/bench/commands/make.py", line 40, in get_app
    get_app(git_url, branch=branch)
  File "/usr/local/lib/python2.7/dist-packages/bench-4.1.0-py2.7.egg/bench/app.py", line 123, in get_app
    cwd=os.path.join(bench_path, 'apps'))
  File "/usr/local/lib/python2.7/dist-packages/bench-4.1.0-py2.7.egg/bench/utils.py", line 153, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git clone https://github.com/frappe/erpnext  --depth 1 --origin upstream
```

**Comment by codingCoffee** [comment]
As the error log states you already have the app downloaded. 
```
fatal: destination path 'erpnext' already exists and is not an empty directory.
```

**Please post such queries on the [discuss forum](https://discuss.erpnext.com). Closing issue.**
