### ISSUE TITLE
Passwords cannot have spaces

### ISSUE THREAD

**Issue by SoulEst** [frappe/bench#657]
When initially installing ERPNext using Frappe Bench I used password containing spaces for the root MySQL user and Administrator user. When running Bench to install ERPNext, I got this error:  
  
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "new-site", "site1.local", "--admin-password", "m4ri4", "4dmin", "--mariadb-root-password", "m4ri4", "r007"], "delta": "0:00:05.702306", "end": "2018-05-05 18:44:01.947502", "msg": "non-zero return code", "rc": 2, "start": "2018-05-05 18:43:56.245196", "stderr": "Usage: bench  new-site [OPTIONS] SITE\n\nError: Got unexpected extra arguments (4dmin r007)", "stderr_lines": ["Usage: bench  new-site [OPTIONS] SITE", "", "Error: Got unexpected extra arguments (4dmin r007)"], "stdout": "", "stdout_lines": []}                                                                                                                                        
        to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=53   changed=9    unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```

After going back and replacing the spaces in the passwords.txt file, the install goes smoothly.

**Comment by codingCoffee** [comment]
Hey! thanks for reporting the issue. We'll look into it and fix it!

**Comment by cgpurbaugh** [comment]
Can this issue be closed since it has been merged?

**Comment by SoulEst** [comment]
@cgpurbaugh 
You certainly can. Thank you.

**Comment by cgpurbaugh** [comment]
@adityahase Can you close this?
