### ISSUE TITLE
Error on [Set home folder perms]

### ISSUE THREAD

**Issue by LenardValdez** [frappe/bench#658]
```
TASK [Set home folder perms] ***************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/usr/bin/hhvm'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ayphY9/ansible_module_file.py\", line 473, in <module>\n    main()\n  File \"/tmp/ansible_ayphY9/ansible_module_file.py\", line 350, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_ayphY9/ansible_module_file.py\", line 169, in recursive_set_attributes\n    changed |= recursive_set_attributes(module, b_fsname, follow, file_args)\n  File \"/tmp/ansible_ayphY9/ansible_module_file.py\", line 172, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed, expand=False)\n  File \"/tmp/ansible_ayphY9/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1507, in set_fs_attributes_if_different\n  File \"/tmp/ansible_ayphY9/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1164, in set_owner_if_different\n  File \"/tmp/ansible_ayphY9/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1059, in user_and_group\nOSError: [Errno 2] No such file or directory: '/usr/bin/hhvm'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/tmp/.bench/playbooks/create_user.retry
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
Traceback (most recent call last):
  File "/home/travis/build/frappe/bench/playbooks/install.py", line 417, in <module>
    install_bench(args)
  File "/home/travis/build/frappe/bench/playbooks/install.py", line 100, in install_bench
    run_playbook('create_user.yml', extra_vars=extra_vars)
  File "/home/travis/build/frappe/bench/playbooks/install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'create_user.yml', '-e', '@/tmp/extra_vars
```
I snipped this from travis build:error log since I was checking if im not the one who's causing the problem, and sure enough I'm having the same problem

Ubuntu 16.04
Ram: 8gb
Intel xeon

**Comment by codingCoffee** [comment]
Which hosting provider are you using?

**Comment by shokoylele** [comment]
I tried to install it on my local machine. fresh system.

**Comment by codingCoffee** [comment]
It's recommended to install manually on your local system. You may refer the following guide for the same:
https://github.com/frappe/frappe/wiki/The-Hitchhiker's-Guide-to-Installing-Frapp%C3%A9-on-Linux-OS

However, if you still want to use the easy install scripts you can use this command. It helped mitigate the error in travis
```
sudo apt-get install hhvm && rm -rf /home/travis/.kiex/
```
In the above command instead of using the `travis` user, use your username. 

Closing this issue.

**Comment by shokoylele** [comment]
`TASK [Set home folder perms] ***********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/home/.ecryptfs/botecentral/.Private/ECRYPTFS_FNEK_ENCRYPTED.FYYXh1emItTmekRT3sK2MXopa7yX4fA3koTtIos4dmEMi6rfe5VuEtmGd-6hjXNYTHu7MyWuWY9ND6UCVMFZwA85l..e4.Rmmy4m'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_WHA9AN/ansible_module_file.py\", line 473, in <module>\n    main()\n  File \"/tmp/ansible_WHA9AN/ansible_module_file.py\", line 350, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_WHA9AN/ansible_module_file.py\", line 169, in recursive_set_attributes\n    changed |= recursive_set_attributes(module, b_fsname, follow, file_args)\n  File \"/tmp/ansible_WHA9AN/ansible_module_file.py\", line 172, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed, expand=False)\n  File \"/tmp/ansible_WHA9AN/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1507, in set_fs_attributes_if_different\n  File \"/tmp/ansible_WHA9AN/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1164, in set_owner_if_different\n  File \"/tmp/ansible_WHA9AN/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1059, in user_and_group\nOSError: [Errno 2] No such file or directory: '/home/.ecryptfs/botecentral/.Private/ECRYPTFS_FNEK_ENCRYPTED.FYYXh1emItTmekRT3sK2MXopa7yX4fA3koTtIos4dmEMi6rfe5VuEtmGd-6hjXNYTHu7MyWuWY9ND6UCVMFZwA85l..e4.Rmmy4m'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/tmp/.bench/playbooks/create_user.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 100, in install_bench
    run_playbook('create_user.yml', extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'create_user.yml', '-e', '@/tmp/extra_vars.json']' returned non-zero exit status 2
botecentral@erp-server:~$`

still getting errors

**Comment by shokoylele** [comment]
`frappe@ubuntu:~$ sudo pip install -e git+https://github.com/frappe/bench#egg=frappe-bench
The directory '/home/frappe/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/frappe/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining frappe-bench from git+https://github.com/frappe/bench#egg=frappe-bench
  Cloning https://github.com/frappe/bench to ./src/frappe-bench
  Running setup.py (path:/home/frappe/src/frappe-bench/setup.py) egg_info for package frappe-bench produced metadata for project name bench. Fix your #egg=frappe-bench fragments.
Collecting Click (from bench)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 255kB/s
Collecting jinja2 (from bench)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 414kB/s
Collecting virtualenv (from bench)
  Downloading https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 476kB/s
Collecting requests (from bench)
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.3MB/s
Collecting honcho (from bench)
  Downloading https://files.pythonhosted.org/packages/12/c2/95faf9e062e37f50fb685972692395bef019a554c08447282a81e35bf031/honcho-1.0.1-py2.py3-none-any.whl
Collecting psutil (from bench)
  Downloading https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 1.6MB/s
Collecting python-crontab (from bench)
  Downloading https://files.pythonhosted.org/packages/12/02/42acd56201b75959641ef7074dce3e2a5d4ca8febbf4c66a9a1dd5bbd296/python-crontab-2.3.0.tar.gz (44kB)
    100% |████████████████████████████████| 51kB 2.0MB/s
Collecting semantic_version (from bench)
  Downloading https://files.pythonhosted.org/packages/72/83/f76958017f3094b072d8e3a72d25c3ed65f754cc607fdb6a7b33d84ab1d5/semantic_version-2.6.0.tar.gz
Collecting GitPython==0.3.2.1 (from bench)
  Downloading https://files.pythonhosted.org/packages/76/23/57eb38e3a88b7d950501dee66d4a6986f0c49916143ec3631000bc47a33b/GitPython-0.3.2.1.tar.gz (316kB)
    100% |████████████████████████████████| 317kB 1.7MB/s
Collecting MarkupSafe>=0.23 (from jinja2->bench)
  Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Collecting certifi>=2017.4.17 (from requests->bench)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 2.5MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->bench)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.8MB/s
Collecting idna<2.7,>=2.5 (from requests->bench)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 4.2MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests->bench)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.6MB/s
Collecting python-dateutil (from python-crontab->bench)
  Downloading https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |████████████████████████████████| 215kB 1.7MB/s
Collecting gitdb>=0.6.0 (from GitPython==0.3.2.1->bench)
  Downloading https://files.pythonhosted.org/packages/e3/95/7e5d7261feb46c0539ac5e451be340ddd64d78c5118f2d893b052c76fe8c/gitdb-0.6.4.tar.gz (400kB)
    100% |████████████████████████████████| 409kB 1.9MB/s
Collecting six>=1.5 (from python-dateutil->python-crontab->bench)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting smmap>=0.8.5 (from gitdb>=0.6.0->GitPython==0.3.2.1->bench)
  Downloading https://files.pythonhosted.org/packages/bc/aa/b744b3761fff1b10579df996a2d2e87f124ae07b8336e37edc89cc502f86/smmap-0.9.0.tar.gz
Installing collected packages: Click, MarkupSafe, jinja2, virtualenv, certifi, chardet, idna, urllib3, requests, honcho, psutil, six, python-dateutil, python-crontab, semantic-version, smmap, gitdb, GitPython, bench
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-M1nOEi/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-OiDU0w-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_exceptions.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    creating build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=545 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-M1nOEi/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-OiDU0w-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-M1nOEi/psutil/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
frappe@ubuntu:~$ sudo -H pip install -e git+https://github.com/frappe/bench#egg=frappe-bench
Obtaining frappe-bench from git+https://github.com/frappe/bench#egg=frappe-bench
  Updating ./src/frappe-bench clone
  Running setup.py (path:/home/frappe/src/frappe-bench/setup.py) egg_info for package frappe-bench produced metadata for project name bench. Fix your #egg=frappe-bench fragments.
Requirement already satisfied: Click in /usr/local/lib/python2.7/dist-packages (from bench)
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from bench)
Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages (from bench)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from bench)
Requirement already satisfied: honcho in /usr/local/lib/python2.7/dist-packages (from bench)
Collecting psutil (from bench)
  Downloading https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 1.2MB/s
Collecting python-crontab (from bench)
  Downloading https://files.pythonhosted.org/packages/12/02/42acd56201b75959641ef7074dce3e2a5d4ca8febbf4c66a9a1dd5bbd296/python-crontab-2.3.0.tar.gz (44kB)
    100% |████████████████████████████████| 51kB 3.4MB/s
Collecting semantic_version (from bench)
  Downloading https://files.pythonhosted.org/packages/72/83/f76958017f3094b072d8e3a72d25c3ed65f754cc607fdb6a7b33d84ab1d5/semantic_version-2.6.0.tar.gz
Collecting GitPython==0.3.2.1 (from bench)
  Downloading https://files.pythonhosted.org/packages/76/23/57eb38e3a88b7d950501dee66d4a6986f0c49916143ec3631000bc47a33b/GitPython-0.3.2.1.tar.gz (316kB)
    100% |████████████████████████████████| 317kB 1.6MB/s
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->bench)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->bench)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->bench)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->bench)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->bench)
Collecting python-dateutil (from python-crontab->bench)
  Downloading https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |████████████████████████████████| 215kB 1.3MB/s
Collecting gitdb>=0.6.0 (from GitPython==0.3.2.1->bench)
  Downloading https://files.pythonhosted.org/packages/e3/95/7e5d7261feb46c0539ac5e451be340ddd64d78c5118f2d893b052c76fe8c/gitdb-0.6.4.tar.gz (400kB)
    100% |████████████████████████████████| 409kB 1.4MB/s
Collecting six>=1.5 (from python-dateutil->python-crontab->bench)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting smmap>=0.8.5 (from gitdb>=0.6.0->GitPython==0.3.2.1->bench)
  Downloading https://files.pythonhosted.org/packages/bc/aa/b744b3761fff1b10579df996a2d2e87f124ae07b8336e37edc89cc502f86/smmap-0.9.0.tar.gz
Building wheels for collected packages: psutil, python-crontab, semantic-version, GitPython, gitdb, smmap
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-clHQ0V/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp21SZ8Wpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_exceptions.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
  creating build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/psutil
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=545 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
  Running setup.py bdist_wheel for python-crontab ... done
  Stored in directory: /root/.cache/pip/wheels/26/41/21/3e899b95736da60fb8fa6b662a5eec2e82e2f13fdd097f543b
  Running setup.py bdist_wheel for semantic-version ... done
  Stored in directory: /root/.cache/pip/wheels/60/bb/50/215d669d31f992767f5dd8d3c974e79261707ee7f898f0dc10
  Running setup.py bdist_wheel for GitPython ... done
  Stored in directory: /root/.cache/pip/wheels/0e/bf/e2/9794c03124e55ded00e1b1595037c2a0479e430cb8bfb796aa
  Running setup.py bdist_wheel for gitdb ... done
  Stored in directory: /root/.cache/pip/wheels/d1/7e/c5/1093bc36622d7d06ed6520a50280771ebff8c190d92bd402b6
  Running setup.py bdist_wheel for smmap ... done
  Stored in directory: /root/.cache/pip/wheels/d6/a5/09/cb584a95ad332da2bf0265a8b0423c562a99553a3edf148d12
Successfully built python-crontab semantic-version GitPython gitdb smmap
Failed to build psutil
Installing collected packages: psutil, six, python-dateutil, python-crontab, semantic-version, smmap, gitdb, GitPython, bench
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-clHQ0V/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xVBZUn-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_exceptions.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    creating build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=545 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-clHQ0V/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xVBZUn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-clHQ0V/psutil/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

runned on a fresh install of ubuntu 16.04 after running 
`sudo pip install -e git+https://github.com/frappe/bench#egg=frappe-bench`

I followed step by step from top to bottom

>

**Comment by codingCoffee** [comment]
Okay, this seems like a valid error. Will get this patched up. In the meantime use this:

```
git clone https://github.com/frappe/bench
pip install ./bench
```

**Comment by codingCoffee** [comment]
ToDo:
- [ ] Fix pip install
- [ ] FIx Hitchiker's guide

**Comment by yashodhank** [comment]
@shokoylele https://discuss.erpnext.com/t/pip-error-command-x86-64-linux-gnu-gcc-failed-with-exit-status-1/40884

**Comment by yashodhank** [comment]
This mainly happens because of apt package priority, when we add MariaDB repo to the Debian/Ubuntu machine. `libmysqlclient-dev` does not have MariaDB compatible version of libmysqlclient18 in newly added repo and Ubuntu apt cant install older version of `libmysqlclient18` unless you force manually.

**Comment by yashodhank** [comment]
`install.py` can handle advance use cases very well do `python install.py --help` to know more options available. Ref: https://discuss.erpnext.com/t/install-script-and-v11/40939/15?u=yashodhan

Those who wish to do custom install (only frappe, without site, from custom repo etc.), it is possible with `install.py` (easy method) as long as your base OS distribution and version is supported by bench.

**Comment by gavindsouza** [comment]
Closing issue due to inactivity.
