### ISSUE TITLE
Receiving following error during production setup

### ISSUE THREAD

**Issue by sohamnavadiya** [frappe/bench#662]
I am trying yo setup erpnext on EC2 instance in production mode, but receiving following error on 
*sudo python install.py --production* command.
```
TASK [bench : Install ERPNext to default site] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "--site", "site1.local", "install-app", "erpnext"], "delta": "0:00:01.769010", "end": "2018-05-23 11:01:31.226160", "msg": "non-zero return code", "rc": 1, "start": "2018-05-23 11:01:29.457150", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 94, in <module>\n    main()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 697, in main\n    rv = self.invoke(ctx)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 535, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py\", line 24, in _func\n    ret = f(frappe._dict(ctx.obj), *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 162, in install_app\n    frappe.init(site=site)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 158, in init\n    setup_module_map()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 864, in setup_module_map\n    local.app_modules = _cache.get_value(\"app_modules\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 68, in get_value\n    val = pickle.loads(val)\nValueError: unsupported pickle protocol: 3", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main", "    \"__main__\", fname, loader, pkg_name)", "  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code", "    exec code in run_globals", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 94, in <module>", "    main()", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main", "    click.Group(commands=commands)(prog_name='bench')", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 722, in __call__", "    return self.main(*args, **kwargs)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 697, in main", "    rv = self.invoke(ctx)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 1066, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 895, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py\", line 535, in invoke", "    return callback(*args, **kwargs)", "  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func", "    return f(get_current_context(), *args, **kwargs)", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py\", line 24, in _func", "    ret = f(frappe._dict(ctx.obj), *args, **kwargs)", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 162, in install_app", "    frappe.init(site=site)", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 158, in init", "    setup_module_map()", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 864, in setup_module_map", "    local.app_modules = _cache.get_value(\"app_modules\")", "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 68, in get_value", "    val = pickle.loads(val)", "ValueError: unsupported pickle protocol: 3"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=76   changed=13   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

```

**Comment by gavindsouza** [comment]
Closing issue due to inactivity...Open a new one if issue persists.
