### ISSUE TITLE
error when trying to create virtual image

### ISSUE THREAD

**Issue by elba7r** [frappe/bench#665]
when i go to the already installed erpnext latest version bench/vm folder and i run sudo python build.py to create my own virtual image i'm getting this error : 

Traceback (most recent call last):
  File "build.py", line 128, in <module>
    main()
  File "build.py", line 24, in main
    build_vm()
  File "build.py", line 62, in build_vm
    check_output(["/opt/packer", "build", "vm-production.json"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/opt/packer', 'build', 'vm-production.json']' returned non-zero exit status 1

**Comment by codingCoffee** [comment]
Can you please check if you you have the `packer` binary in `/opt` directory. Paste the output of `ls /opt` here. If there is, can you please `rm /opt/packer` and try again. Maybe it was incorrectly downloaded.

**Comment by elba7r** [comment]
where should i find this directory and how i can download the packer binary, can you please explain !

**Comment by codingCoffee** [comment]
Please post the output of 
```
ls /opt
```
The build.py script takes care of downloading it for you. If the output of the above command prints `packer` it means you have the packer binary installed in the `/opt` folder. And if there is a packer binary present there maybe delete it using the following command
```
rm /opt/packer
```
Also is there any specific reason you're trying to build and ERPNext VM image yourself ?? You can download it from https://erpnext.org/get-started.html

**Comment by elba7r** [comment]
i follow what did u said but the same error:
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: Could not match supplied host pattern, ignoring: all
 [WARNING]: provided hosts list is empty, only localhost is available
 [WARNING]: Consider using get_url or uri module rather than running wget
 [WARNING]: Consider using unarchive module rather than running unzip
Traceback (most recent call last):
  File "build.py", line 128, in <module>
    main()
  File "build.py", line 24, in main
    build_vm()
  File "build.py", line 62, in build_vm
    check_output(["/opt/packer", "build", "vm-production.json"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/opt/packer', 'build', 'vm-production.json']' returned non-zero exit status 1

**Comment by gavindsouza** [comment]
Closing issue due to inactivity...Open a new one if issue persists.
