### ISSUE TITLE
Report Builder Error

### ISSUE THREAD

**Issue by shokoylele** [frappe/bench#682]
When Building your own Email report using report builder then using "send now" throws this error

```
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 167, in send_now
    auto_email_report.send()
  File "/opt/bench/erpnext/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 122, in send
    data = self.get_report_content()
  File "/opt/bench/erpnext/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 61, in get_report_content
    filters = self.filters, as_dict=True)
  File "/opt/bench/erpnext/apps/frappe/frappe/core/doctype/report/report.py", line 138, in get_data
    order_by = _format(params.get('sort_by').split('.')) + ' ' + params.get('sort_order')
AttributeError: 'NoneType' object has no attribute 'split'
```

I'm on the master branch on local machine(Ubuntu 18.04)
when I try to force email it via opening the report and show print view this shows up
[Daily.pdf](https://github.com/frappe/bench/files/2122432/Daily.pdf)
I wanted to creat daily sales report wich is only possible via report builder

**Comment by codingCoffee** [comment]
Please open the issue in the [frappe repository](https://github.com/frappe/frappe/issues/new/choose) 

Closing issue here
