### ISSUE TITLE
error with new installation

### ISSUE THREAD

**Issue by elba7r** [frappe/bench#683]
Issue: Bug report

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

**Do the checklist before filing an issue:**
 - [ ] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [ ] Can you replicate the issue? 
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [yes ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [yes ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [ ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin: 
i'm using ubuntu server 16.04 lts and this a brand new installation
i have the following response at  TASK [bench : Create a new site]

"  File \"/home/revalue/frappe-bench/apps/frappe/frappe/model/delete_doc.py\", line 68, in delete_doc", "    delete_from_table(doctype, name, ignore_doctypes, None)", "  File \"/home/revalue/frappe-bench/apps/frappe/frappe/model/delete_doc.py\", line 136, in delete_from_table", "    frappe.db.sql(\"delete from `tab%s` where name=%s\" % (frappe.db.escape(doctype), \"%s\"), (name,))", "  File \"/home/revalue/frappe-bench/apps/frappe/frappe/database.py\", line 892, in escape", "    s = text_type(pymysql.escape_string(s), \"utf-8\").replace(\"`\", \"\\\\`\")", "  File \"/home/revalue/frappe-bench/env/lib/python3.5/site-packages/pymysql/converters.py\", line 73, in _escape_unicode", "    return value.translate(_escape_table)", "TypeError: a bytes-like object is required, not 'list'"], "stdout": "\nInstalling frappe...", "stdout_lines": ["", "Installing frappe..."]}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=55   changed=33   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=revalue']' returned non-zero exit status 2

**Comment by elba7r** [comment]
i'm very sorry as it looks like i forget to add --production flag to the sudo python install.py command

so the installer is working just fine and you can close this issue

Best Regards
