### ISSUE TITLE
The 'jinja2' distribution was not found and is required by bench

### ISSUE THREAD

**Issue by nomi-gee** [frappe/bench#702]
frappe@muhammad-nouman:~$ bench install erp
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jinja2' distribution was not found and is required by bench

**Comment by nomi-gee** [comment]
TASK [bench : python3 bench init for develop] **********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "init", "/home/frappe/frappe-bench", "--frappe-path", "https://github.com/frappe/frappe", "--frappe-branch", "develop", "--python", "python3"], "delta": "0:00:00.131647", "end": "2018-07-11 17:26:19.165715", "msg": "non-zero return code", "rc": 1, "start": "2018-07-11 17:26:19.034068", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/bench\", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3088, in <module>\n    @_call_aside\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 574, in _build_master\n    ws.require(__requires__)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The 'jinja2' distribution was not found and is required by bench", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/bin/bench\", line 6, in <module>", "    from pkg_resources import load_entry_point", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3088, in <module>", "    @_call_aside", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3072, in _call_aside", "    f(*args, **kwargs)", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3101, in _initialize_master_working_set", "    working_set = WorkingSet._build_master()", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 574, in _build_master", "    ws.require(__requires__)", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 892, in require", "    needed = self.resolve(parse_requirements(requirements))", "  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 778, in resolve", "    raise DistributionNotFound(req, requirers)", "pkg_resources.DistributionNotFound: The 'jinja2' distribution was not found and is required by bench"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=37   changed=9    unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 420, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by nomi-gee** [comment]
issue resolved : 
bench is not installed on frappe user due to some reason
