### ISSUE TITLE
It Give this error when i save email Account 

### ISSUE THREAD

**Issue by Mughira** [frappe/bench#704]
Issue: Bug report

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

**Do the checklist before filing an issue:**
 - [x] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [x] Can you replicate the issue? 
 - [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [ ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin:

**Comment by Mughira** [comment]
I am having this issue while Saving E-mail Account... Can you hel me out.


Cannot connect: b'[AUTHENTICATIONFAILED] Authentication failed.'

Server Error: Please check your server logs or contact tech support.

Traceback (most recent call last):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 163, in get_incoming_server
    email_server.connect()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 43, in connect
    return self.connect_imap()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 54, in connect_imap
    self.imap.login(self.settings.username, self.settings.password)
  File "/usr/lib/python3.5/imaplib.py", line 582, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Authentication failed.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 66, in validate
    self.get_incoming_server()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 165, in get_incoming_server
    message = e.message.lower().replace(" ","")
AttributeError: 'error' object has no attribute 'message'

Traceback (most recent call last):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 163, in get_incoming_server
    email_server.connect()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 43, in connect
    return self.connect_imap()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 54, in connect_imap
    self.imap.login(self.settings.username, self.settings.password)
  File "/usr/lib/python3.5/imaplib.py", line 582, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Authentication failed.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 66, in validate
    self.get_incoming_server()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 165, in get_incoming_server
    message = e.message.lower().replace(" ","")
AttributeError: 'error' object has no attribute 'message'

**Comment by codingCoffee** [comment]
Can you please open the issue in [here](https://github.com/frappe/frappe/issues/new)
