### ISSUE TITLE
bench_helper.py ValueError: Expecting , delimiter: line 5 column 12 (char 95)

### ISSUE THREAD

**Issue by bin4ryio** [frappe/bench#716]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend: 

```Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 121, in doctor
    return _doctor(site=site)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/doctor.py", line 108, in doctor
    frappe.init(s)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 138, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 204, in get_site_config
    config.update(get_file_json(site_config))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 975, in get_file_json
    return json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 5 column 12 (char 95)
```

**To Reproduce** :page_with_curl:
1. Setup bench using official wget script on fresh Ubuntu 16.04 image in DigitalOcean
2. bench switch-to-master
3. bench update --patch

**Screenshots** :crystal_ball:
![image](https://user-images.githubusercontent.com/21124691/44995088-17154e80-afd4-11e8-9834-670979691deb.png)

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [X] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [X] `master` :star2: 
    - [ X] `develop` :fire:
- Frappe Version: latest
- ERPNext Version: latest

**Comment by bin4ryio** [comment]
Sorry, realize it's error in site_config.json
