### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' | backward compatibility issue

### ISSUE THREAD

**Issue by yashodhank** [frappe/bench#722]
Issue: Bug report

```bash
~/frappe-bench$ bench update --requirements --force --no-backup
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages (5.2.0)
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages (18.0)
INFO:bench.utils:./env/bin/pip install -q -r /home/frappe/.bench/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/foundation/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe_io/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe/requirements.txt
Updating node packages...
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, restart_systemd, requirements, no_backup, force=force, reset=reset)
  File "/home/frappe/.bench/bench/commands/update.py", line 77, in _update
    update_node_packages(bench_path=bench_path)
  File "/home/frappe/.bench/bench/utils.py", line 441, in update_node_packages
    v = LooseVersion(get_develop_version('frappe', bench_path = bench_path))
  File "/home/frappe/.bench/bench/app.py", line 327, in get_develop_version
    return get_version_from_string(f.read(), field='develop_version')
  File "/home/frappe/.bench/bench/app.py", line 411, in get_version_from_string
    return match.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Version Information**
- Which branch are you on?
    - [x] `master` :star2: 
    - [ ] `develop` :fire:
- Frappe Version: 7.x.x
- ERPNext Version: 7.x.x

**Additional context** :page_facing_up:
- Bench Version: 4.1.0 is installed on fresh Ubuntu 14.04
- frappe-bench and frappe-bench-new are without with one test site in each

https://github.com/frappe/bench/blob/b5657c160c3d8d5424411121ab70c808db598741/bench/utils.py#L441

https://github.com/frappe/bench/blob/b5657c160c3d8d5424411121ab70c808db598741/bench/app.py#L411

https://github.com/frappe/frappe/blob/ecd61baf0ab211c1b26c7e27e8614bd149784c0d/frappe/hooks.py#L14

**Possible Solution** :bookmark_tabs:
Check values before returning it

**Comment by gavindsouza** [comment]
Closing this issue due to inactivity. Open a fresh issue if this persists.
