### ISSUE TITLE
bench init fails on macOS with Python3

### ISSUE THREAD

**Issue by theopen-institute** [frappe/bench#741]
Issue: Bug report

At present, `bench init` is failing on my setup with the following error:

```
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t9/7z0p020138s20gj3ymh069f00000gp/T/pip-install-_j5x0ki8/MySQL-python/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/xxxxxxxxx/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/Users/xxxxxxxxx/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxxxxxxxx/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/xxxxxxxxx/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxxxxxxxx/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxxxxxxxx/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxxxxxxxx/bench-repo/bench/commands/make.py", line 30, in init
    python 		 = python)
  File "/Users/xxxxxxxxx/bench-repo/bench/utils.py", line 75, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/Users/xxxxxxxxx/bench-repo/bench/app.py", line 141, in get_app
    branch= 'master', postprocess = False)
  File "/Users/xxxxxxxxx/bench-repo/bench/app.py", line 135, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/Users/xxxxxxxxx/bench-repo/bench/app.py", line 179, in install_app
    find_links=find_links))
  File "/Users/xxxxxxxxx/bench-repo/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe_io --no-cache-dir
```

As discussed in [this thread](https://discuss.erpnext.com/t/python3-and-mysql-python/41965/5), I believe the issue is due to a combination of macOS and Python3. `bench-repo/playbooks/macosx.yml` indicates a requirement for mysql-python, but mysql-python is not compatible with Python3.

**Comment by theopen-institute** [comment]
Thanks for your reply. Here's what I get:

```
Obtaining file:///Users/xxxxxxxxx/frappe-bench/apps/frappe_io
Collecting frappe (from frappe-io==0.0.1)
  Downloading https://files.pythonhosted.org/packages/4c/d3/73da0e17271031bacd2c585588026701ae5934329264db575ad989cc9ce3/frappe-2.1.4.tar.gz (217kB)
    100% |████████████████████████████████| 225kB 377kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/t9/7z0p020138s20gj3ymh069f00000gp/T/pip-install-flc_sklv/frappe/setup.py", line 8, in <module>
        import testfm
    ModuleNotFoundError: No module named 'testfm'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t9/7z0p020138s20gj3ymh069f00000gp/T/pip-install-flc_sklv/frappe/setup.py", line 10, in <module>
        raise LookupError("You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)")
    LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)
```

**Comment by theopen-institute** [comment]
Looking closer, the problem here seems to be that frappe_io is trying to pull frappe as `https://github.com/grafos-ml/frappe`, but I haven't been able to figure out why. I don't have it installed anywhere that I can tell, and I don't know enough about pip to understand why it's looking there instead of in the proper location.

Any suggestions?

**Comment by theopen-institute** [comment]
I still can't quite figure out why frappe_io is pulling from https://github.com/grafos-ml/frappe. Any thoughts on a fix?

**Comment by Thunderbottom** [comment]
One solution to this is that you create and use a virtualenv to install frappe.

**Comment by gavindsouza** [comment]
Closing due to inactivity. Open a new one if issue persists.
