### ISSUE TITLE
throwing error in new-site command

### ISSUE THREAD

**Issue by hbakhtiyor** [frappe/bench#768]
```
bench new-site erp.example.com --force
```
```
TypeError: int() argument must be a string or a number, not 'list
```

full
```
MySQL root password: 

Installing frappe...
Updating DocTypes for frappe        : [=========================               ]Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/commands/site.py", line 33, in new_site
    db_type = db_type)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/commands/site.py", line 70, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/installer.py", line 85, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 133, in import_doc
    doc.insert()
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/model/document.py", line 248, in insert
    self.run_post_save_methods()
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/model/document.py", line 928, in run_post_save_methods
    self.clear_cache()
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/model/document.py", line 942, in clear_cache
    frappe.clear_document_cache(self.doctype, self.name)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/__init__.py", line 686, in clear_document_cache
    cache().hdel("last_modified", doctype)
  File "/srv/users/serverpilot/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 194, in hdel
    super(RedisWrapper, self).hdel(_name, key)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/redis/client.py", line 1955, in hdel
    return self.execute_command('HDEL', name, *keys)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/redis/client.py", line 674, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/srv/users/serverpilot/frappe-bench/env/local/lib/python2.7/site-packages/redis/client.py", line 682, in parse_response
    return self.response_callbacks[command_name](response, **options)
TypeError: int() argument must be a string or a number, not 'list
```

bench version: 4.1.0
redis version: 4.0.11
os: ubuntu 16.04

**Comment by gavindsouza** [comment]
Can you still replicate the issue with the latest Frappe/ERPNext versions? Closing this issue now, re-open if it still persists.
