### ISSUE TITLE
 bench new-site site-name.local command give: RuntimeError: no object bound to db

### ISSUE THREAD

**Issue by msh2050** [frappe/bench#806]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [no] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [yes] Can you replicate the issue? 
 - [no] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 

I tried to install erpnext on ubuntu 18 server ...
I use production/development -- easy - manual all end up with same issue...

**To Reproduce** :page_with_curl:
1. 'follow any guide to install erpnext on ubuntu  '
2.  bench new-site site-name.local
3. enter mysql password
4. See error:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1396, "Operation DROP USER failed for '_490e0c0373a648b1'@'localhost'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 33, in new_site
    db_type = db_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 66, in _new_site
    source_sql=source_sql,force=force, reinstall=reinstall, db_type=db_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 35, in install_db
    setup_database(force, source_sql, verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 16, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(force, source_sql, verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 40, in setup_database
    dbman.delete_user(db_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 31, in delete_user
    self.db.sql("DROP USER '%s'@'%s';" % (target, host))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 181, in sql
    if(frappe.db.db_type == 'postgres'):
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to db
```

 - OS:
    - [* ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [ *] Chrome
    - [* ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [* ] `master` :star2: 
    - [* ] `develop` :fire:
- Frappe Version: latest
- ERPNext Version: latest

**Comment by chintanbanugaria** [comment]
Facing the same issue. Exactly same configuration.

**Comment by msh2050** [comment]
the guide should be updated to include required versions of apps to be installed and the version ti be cloned to over come the compatibility...

**Comment by msh2050** [comment]
@chintanbanugaria try docker:
https://pipech.github.io/erpnext-docker-debian/trial_setup/

**Comment by chintanbanugaria** [comment]
@msh2050 Sure. Let me try that.

**Comment by gavindsouza** [comment]
Closing issue due to inactivity...Open a new one if issue persists.
