### ISSUE TITLE
Very hard to install on OSX

### ISSUE THREAD

**Issue by voordev** [frappe/bench#807]
Its very hard to install this application. 
Im following the exact steps but unable for more than hour to find any solution on how to resolve.

Last part of my stack trace:

`
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/ddd/Applications/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ddd/Applications/bench-repo/bench/commands/make.py", line 30, in init
    python 		 = python)
  File "/Users/ddd/Applications/bench-repo/bench/utils.py", line 83, in init
    update_node_packages(bench_path=path)
  File "/Users/ddd/Applications/bench-repo/bench/utils.py", line 452, in update_node_packages
    update_yarn_packages(bench_path)
  File "/Users/ddd/Applications/bench-repo/bench/utils.py", line 465, in update_yarn_packages
    exec_cmd('yarn install', cwd=app_path)
  File "/Users/ddd/Applications/bench-repo/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: yarn install
`

How can this be resolved?
Manual install not a VM disk.

**Comment by sagar-bhogayata** [comment]
**Same Issue Same Error**


`2 warnings and 5 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sagar/frappe-bench/apps/frappe/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/Users/sagar/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/sagar/frappe-bench/apps/frappe/node_modules/node-sass
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1`

**Python Traceback**
`Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/Users/sagar/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sagar/bench-repo/bench/commands/make.py", line 30, in init
    python 		 = python)
  File "/Users/sagar/bench-repo/bench/utils.py", line 83, in init
    update_node_packages(bench_path=path)
  File "/Users/sagar/bench-repo/bench/utils.py", line 452, in update_node_packages
    update_yarn_packages(bench_path)
  File "/Users/sagar/bench-repo/bench/utils.py", line 465, in update_yarn_packages
    exec_cmd('yarn install', cwd=app_path)
  File "/Users/sagar/bench-repo/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: yarn install`

how to solve this ??
MacOS Mojave 10.14.5

**Comment by voordev** [comment]
Actually spend already 4 hours on this now.
I love what the software can do but the installation is the worst and uttermost worst experience I ever had. The installation is totally unaccaptable getting error after error.

It seems like you guys want to force anyone into using the online platform?

How can you rely on a software for your business if any update could break it seriously.

Shame for erpnext I guess I have to look for a software that is solid enough to run a business,
seems like erpnext is not there yet for some years. Also many open issues in the issue tracker, they are just never fixed. Keep everything breaking so people keep buying your services. good strategy

**Comment by clarkejj** [comment]
Yes various reports confirm that direct installs on MacOS can be a problem.

So maybe then try the VM install route.

**Comment by sagar-bhogayata** [comment]
The issue has been resolved 

**I downgrade node version to node@10**

```
brew uninstall node
brew install node@10
brew link --force --overwrite node@10
```

and than

**`bench init frappe-bench`**
