### ISSUE TITLE
Bench Easy Install Failed on mac

### ISSUE THREAD

**Issue by sagar-bhogayata** [frappe/bench#808]
Trying to install frappe using bench easy install on mac using below command

> sudo python install.py --production --user sagar

but it failed at [Set home folder perms] 

```
TASK [Set home folder perms] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/sagar as requested: [Errno 45] Operation not supported: '/home/sagar'", "path": "/home/sagar"}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Traceback (most recent call last):
  File "install.py", line 432, in <module>
    install_bench(args)
  File "install.py", line 106, in install_bench
    run_playbook('create_user.yml', extra_vars=extra_vars)
  File "install.py", line 344, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'create_user.yml', '-e', '@/tmp/extra_vars.json']' returned non-zero exit status 2`
```

**Comment by chemeng** [comment]
After 3 hours of trying to install this on OSX with python3 I gave up..

**Comment by lasalesi** [comment]
Refer to this: https://discuss.erpnext.com/t/install-script-fails-on-debian-9-2019-07-29/51252/3

    $ sudo apt install dirmngr -y
