### ISSUE TITLE
Easy install failed - No such command "new-site"

### ISSUE THREAD

**Issue by ljelinek-cznic** [frappe/bench#812]
Issue: Bug report

The easy install failed with the following:

`Error: No such command "new-site"`

Here is the full report:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "new-site", "site1.local", "--admin-password", "somepassword", "--mariadb-root-password", "somepassword"], "delta": "0:00:00.358315", "end": "2019-06-11 07:31:38.492565", "msg": "non-zero return code", "rc": 2, "start": "2019-06-11 07:31:38.134250", "stderr": "Usage: bench [OPTIONS] COMMAND [ARGS]...\nTry \"bench --help\" for help.\n\nError: No such command \"new-site\".", "stderr_lines": ["Usage: bench [OPTIONS] COMMAND [ARGS]...", "Try \"bench --help\" for help.", "", "Error: No such command \"new-site\"."], "stdout": "", "stdout_lines": []}

**To Reproduce** 
1. Download the install script: wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
2. Prepare an user as described in the "Easy Install" guide.
3. Run the installation command: sudo python install.py --production --user [frappe-user]

**Expected behavior**
The installation succeeds.

**Desktop:**
 - OS: Linux (Kubuntu 19.04)
 - Browser: not applicable

**Version Information**
- Which branch are you on?
  - master
- Frappe Version: master
- ERPNext Version: master

**Comment by henrynewman** [comment]
Make sure you are on the ~/frappe-bench directory
Test and give feedback.

**Comment by ljelinek-cznic** [comment]
> Make sure you are on the ~/frappe-bench directory
> Test and give feedback.
>
It currently fails before it creates the mentioned directory. Here is
the error log:

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "init",
        "/home/frappe-user/frappe-bench",
        "--frappe-path",
        "https://github.com/frappe/frappe",
        "--frappe-branch",
        "version-12",
        "--python",
        "python3"
    ],
    "delta": "0:00:00.487578",
    "end": "2019-08-07 12:20:48.073462",
    "invocation": {
        "module_args": {
            "_raw_params": "bench init /home/frappe-user/frappe-bench
--frappe-path https://github.com/frappe/frappe --frappe-branch
version-12 --python
python3",                                                                                                                         

            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/home/frappe-user/frappe-bench",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2019-08-07 12:20:47.585884",
    "stderr": "Traceback (most recent call last):\n  File
\"/usr/local/bin/bench\", line 11, in <module>\n   
load_entry_point('bench', 'console_scripts', 'bench')()\n  File
\"/home/frappe-user/.bench/bench/cli.py\", line 40, in cli\n   
bench_command()\n  File
\"/usr/local/lib/python3.5/dist-packages/click/core.py\", line 764, in
__call__\n    return self.main(*args, **kwargs)\n  File
\"/usr/local/lib/python3.5/dist-packages/click/core.py\", line 696, in
main\n    _verify_python3_env()\n  File
\"/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py\", line
124, in _verify_python3_env\n    ' mitigation steps.' +
extra\nRuntimeError: Click will abort further execution because Python 3
was configured to use ASCII as encoding for the environment. Consult
https://click.palletsprojects.com/en/7.x/python3/ for mitigation
steps.\n\nThis system supports the C.UTF-8 locale which is
recommended.\nYou might be able to resolve your issue by exporting
the\nfollowing environment variables:\n\n    export LC_ALL=C.UTF-8\n   
export LANG=C.UTF-8",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/local/bin/bench\", line 11, in <module>",
        "    load_entry_point('bench', 'console_scripts', 'bench')()",
        "  File \"/home/frappe-user/.bench/bench/cli.py\", line 40, in cli",
        "    bench_command()",
        "  File
\"/usr/local/lib/python3.5/dist-packages/click/core.py\", line 764, in
__call__",
        "    return self.main(*args, **kwargs)",
        "  File
\"/usr/local/lib/python3.5/dist-packages/click/core.py\", line 696, in
main",
        "    _verify_python3_env()",
        "  File
\"/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py\", line
124, in _verify_python3_env",
        "    ' mitigation steps.' + extra",
        "RuntimeError: Click will abort further execution because Python
3 was configured to use ASCII as encoding for the environment. Consult
https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.",
        "",
        "This system supports the C.UTF-8 locale which is recommended.",
        "You might be able to resolve your issue by exporting the",
        "following environment variables:",
        "",
        "    export LC_ALL=C.UTF-8",
        "    export LANG=C.UTF-8"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP
***********************************************************************************************************************************
localhost                  : ok=63   changed=10   unreachable=0   
failed=1    skipped=61   rescued=0    ignored=0  

Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_bench(args)
  File "install.py", line 135, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 327, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd,
'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c',
'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become',
'--become-user=frappe-user']' returned non-zero exit status 2

**Comment by mohamedyasser** [comment]
same error

/usr/local/Cellar/python/3.7.4/bin/python3.7: Error while finding module specification for 'frappe.utils.bench_helper' (ModuleNotFoundError: No module named 'frappe')

Usage: bench [OPTIONS] COMMAND [ARGS]...
Try "bench --help" for help.

Error: No such command "new-site".

**Comment by gavindsouza** [comment]
Seems like an issue involving Click setup

>          "This system supports the C.UTF-8 locale which is recommended.",
>          "You might be able to resolve your issue by exporting the",         
>          "following environment variables:",         
>          "",         
>          "    export LC_ALL=C.UTF-8",         
>          "    export LANG=C.UTF-8"     
>          ],     "stdout": "",

exporting those environment variables should help

**Comment by gavindsouza** [comment]
Closing this issue due to inactivity.

**Comment by cegomezpy** [comment]
Why to close this if not solved??
