### ISSUE TITLE
Error executing: bench --site site1.local install-app erpnext

### ISSUE THREAD

**Issue by JeetKhatri** [frappe/bench#817]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend: 
I am trying to install ERPNext frappe using full installation, but facing the following issue while executing `bench --site site1.local install-app erpnext`

```python-traceback
Installing erpnext...
Updating DocTypes for erpnext       : [                                        ]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/commands/site.py", line 168, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/installer.py", line 145, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 100, in import_doc
    doc = frappe.get_doc(docdict)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/__init__.py", line 730, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/document.py", line 113, in __init__
    super(Document, self).__init__(kwargs)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/base_document.py", line 54, in __init__
    self.update(d)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/base_document.py", line 77, in update
    self.set(key, value)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/base_document.py", line 124, in set
    self.extend(key, value)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/base_document.py", line 161, in extend
    self.append(key, v)
  File "/home/jeet/ERPNEXT-SETUP/frappe-bench/apps/frappe/frappe/model/base_document.py", line 155, in append
    self.name, str(type(value))[1:-1], value)
ValueError: Document for field "field_order" attached to child table of "Accounts Settings" must be a dict or BaseDocument, not type 'unicode' (auto_accounting_for_stock)
```
Note:
- I am using ubuntu-19.04 OS
- I am using master branch.

![Screenshot-1](https://user-images.githubusercontent.com/28839850/59964172-ab787f80-951a-11e9-88af-2a2010d78975.png)
![Screenshot-2](https://user-images.githubusercontent.com/28839850/59964173-ac111600-951a-11e9-9956-2493bfdcae63.png)

**Comment by gavindsouza** [comment]
this seems like a [Frappe Framework](https://github.com/frappe/frappe) issue. However, it seems to have been fixed. Update your branch and try again.
