### ISSUE TITLE
Setup let's encrypt on centos7

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#829]
```
➜ frappe-bench sudo bench setup lets-encrypt my-erp.alyf.de
Running this will stop the nginx service temporarily causing your sites to go offline
Do you want to continue? [y/N]: y
INFO:bench.utils:sudo systemctl stop nginx
INFO:bench.utils:/opt/certbot-auto  --config /etc/letsencrypt/configs/my-erp.erp.alyf.de.cfg certonly
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /bin/yum
yum is hashed (/bin/yum)
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.alpha-labs.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirror.fra10.de.leaseweb.net
 * updates: mirror.fra10.de.leaseweb.net
digitalocean-agent                                                                | 3.3 kB  00:00:00     
Package gcc-4.8.5-36.el7_6.2.x86_64 already installed and latest version
Package augeas-libs-1.4.0-6.el7_6.1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-87.el7.centos.noarch already installed and latest version
Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version
Package python-devel-2.7.5-80.el7_6.x86_64 already installed and latest version
Package python-virtualenv-15.1.0-2.el7.noarch already installed and latest version
Package python-tools-2.7.5-80.el7_6.x86_64 already installed and latest version
Package python2-pip-8.1.2-8.el7.noarch already installed and latest version
Nothing to do
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pip wheel failed with error code 1
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1
INFO:bench.utils:sudo systemctl start nginx
There was a problem trying to setup SSL for your site
```

Trying the failed command manually:

```
➜  frappe-bench sudo virtualenv --no-site-packages --python /bin/python2.7 /opt/eff.org/certbot/venv
Running virtualenv with interpreter /bin/python2.7
New python executable in /opt/eff.org/certbot/venv/bin/python2.7
Not overwriting existing python script /opt/eff.org/certbot/venv/bin/python (you must use /opt/eff.org/certbot/venv/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/usr/lib64/python2.7/pkgutil.py", line 581, in get_data
    mod = sys.modules.get(package) or loader.load_module(package)
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 94, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 20, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/download.py", line 15, in <module>
ImportError: cannot import name requests
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pip wheel failed with error code 1

➜  frappe-bench pip show requests                                                      
Name: requests
Version: 2.22.0
```

While this works:

```
sudo certbot renew
```

**Comment by gavindsouza** [comment]
does this still replicate after https://github.com/frappe/bench/pull/868?

**Comment by gavindsouza** [comment]
Closing issue due to inactivity...Open a new one if issue persists.
