### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by OnlineAlone** [frappe/bench#848]
Below is the returned error message while installing fresh erpnext stack on fresh VPS Ubuntu 18.04,

```
PLAY RECAP ****************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_bench(args)
  File "install.py", line 135, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 327, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
```
The below commands were used for production setup after installing perquisites.
```
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
sudo python install.py --production --user frappe
``` 
Please advice, Thanks

**Comment by OnlineAlone** [comment]
just moved to different platform
