### ISSUE TITLE
bug: name 'unicode' is not defined

### ISSUE THREAD

**Issue by barredterra** [frappe/bench#873]
No idea how this happened, I just played around with TLS / Nginx setup and the only files I manually modified were `site_config.json` (domains) and `nginx.conf` (rewrite 80 to https). 

```
frappe-bench bench setup nginx

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/setup.py", line 22, in setup_nginx
    make_nginx_conf(bench_path=".", yes=yes)
  File "/home/frappe/.bench/bench/config/nginx.py", line 13, in make_nginx_conf
    sites = prepare_sites(config, bench_path)
  File "/home/frappe/.bench/bench/config/nginx.py", line 100, in prepare_sites
    sites_configs = get_sites_with_config(bench_path=bench_path)
  File "/home/frappe/.bench/bench/config/nginx.py", line 217, in get_sites_with_config
    if isinstance(domain, str) or isinstance(domain, unicode):
NameError: name 'unicode' is not defined
```

### Versions

* Ubuntu 18.04.3 LTS
* bench 4.1.0
* erpnext 12.2.2
* frappe 12.0.20

**Comment by Thunderbottom** [comment]
that is because python3 does not have `unicode` as a keyword, and instead just uses `str` with `utf-8` encoding.

**Comment by Thunderbottom** [comment]
should be fixed with the above PR.
