### ISSUE TITLE
Easy Install script fails in a debian 10 Linux Container

### ISSUE THREAD

**Issue by vrms** [frappe/bench#890]
**Describe the bug**
The easy install script fails on debian 10, eventhough [debian 10 support was added recently](https://github.com/frappe/bench/pull/872) by a PR from @marcogabriel 

I am running in a LXD container and am getting 
```
:~# sudo python install.py --production --user [frappe-user] --container --version 12 --mysql-root-password [mypassword] --admin-password [admin-password]
Logs are saved under /tmp/logs/install_bench.log
Checking System Compatibility...
Install on debian 9 instead
Traceback (most recent call last):
  File "install.py", line 425, in <module>
    check_system_package_managers()
  File "install.py", line 58, in check_system_package_managers
    if not any([shutil.which(x) for x in ['apt-get', 'yum']]):
AttributeError: 'module' object has no attribute 'which'
```
the referneced logfile (`/tmp/logs/install_bench.log`) is empty

**To Reproduce** :page_with_curl:
1. create an LXD container `lxc launch images:debian/buter [container-name]
1. follow the Easy Install instructions in the bench README
1. run the script (with the `--container` flag)

**Expected behavior** :chart_with_upwards_trend:
ERPNext is being installed

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [x ] Linux (debian 10 Container on an ubuntu 18.04 host)

**Comment by Thunderbottom** [comment]
seems like you're using python2 to run the script, as `[shutil.which()](https://docs.python.org/3/library/shutil.html#shutil.which)` only exists in python3 (support added in python3.3).

could you try running the script again with python3 and see if that works?

**Comment by Thunderbottom** [comment]
seems like you're using python2 to run the script, as [`shutil.which()`](https://docs.python.org/3/library/shutil.html#shutil.which) only exists in python3 (support for `which()` was added in python3.3).

could you try running the script again with python3 and see if that works?

**Comment by vrms** [comment]
> could you try running the script again with python3 and see if that works?
seems that does away with the original error but ends up with failing differently
```
:~# sudo python3 install.py --production --user [frappe-user] --container --version 12 --mysql-root-password [mypassword] --admin-password [admin-password]
Logs are saved under /tmp/logs/install_bench.log
Checking System Compatibility...
Install on debian 9 instead
curl already installed!
wget already installed!
git already installed!
pip installed!
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Input mySQL and Frappe Administrator passwords:
Passwords saved at ~/passwords.txt
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
 [WARNING]: Could not find aptitude. Using apt-get instead
Traceback (most recent call last):
  File "install.py", line 428, in <module>
    install_bench(args)
  File "install.py", line 254, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 369, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'), stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=franch']' returned non-zero exit status 2.
```
that now looks similar to https://github.com/frappe/bench/issues/838

**Comment by iMoshi** [comment]
Same error on Ubuntu 18.04. Fresh install.

**Comment by gavindsouza** [comment]
@iMoshi @vrms can you share the error log file?

**Comment by iMoshi** [comment]
> @iMoshi @vrms can you share the error log file?

Similar to the first post if I recall, but I was in a hurry so I proceeded to install on 16.04, which was a success.

**Comment by vrms** [comment]
@gavindsouza what I have posted above is all there is apparently. The referenced logfile (`/tmp/logs/install_bench.log`) is empty

**Comment by gavindsouza** [comment]
Closing this issue then.

**Comment by vrms** [comment]
> Closing this issue then.

because you regard this a duplicate of https://github.com/frappe/bench/issues/838 @gavindsouza ?

**Comment by gavindsouza** [comment]
@vrms it's not a duplicate. So I closed this issue because we can't replicate it and your error log was empty. If you can still replicate it, share the error log file and we'll re-open this issue.

**Comment by MindLaborDev** [comment]
```ansible-playbook 2.8.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
statically imported: /tmp/.bench/bench/playbooks/roles/mariadb/tasks/centos.yml
statically imported: /tmp/.bench/bench/playbooks/roles/mariadb/tasks/ubuntu-trusty.yml
statically imported: /tmp/.bench/bench/playbooks/roles/mariadb/tasks/ubuntu-xenial_bionic.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.8/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: site.yml *****************************************************************************************************
Positional arguments: site.yml
verbosity: 4
connection: local
timeout: 10
become: True
become_method: sudo
become_user: frappe
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
extra_vars: ('@/tmp/extra_vars.json',)
forks: 5
2 plays in site.yml

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
task path: /tmp/.bench/bench/playbooks/site.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960 `" && echo ansible-tmp-1601880271.0907056-7086965913960="` echo /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-657ft9avbb9/tmpu9lqqki1 TO /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960/ /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1601880271.0907056-7086965913960/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [common : include_tasks] ******************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/main.yml:4
included: /tmp/.bench/bench/playbooks/roles/common/tasks/debian_family.yml for localhost

TASK [common : Install prerequisites using apt-get] ********************************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/debian_family.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545 `" && echo ansible-tmp-1601880272.338977-140880813595545="` echo /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/packaging/os/apt.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-657ft9avbb9/tmp09q5owsk TO /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545/AnsiballZ_apt.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545/ /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1601880272.338977-140880813595545/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "cache_update_time": 1601880263,
    "cache_updated": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": true,
            "force_apt_get": false,
            "install_recommends": null,
            "only_upgrade": false,
            "package": [
                "dnsmasq",
                "fontconfig",
                "git",
                "htop",
                "libcrypto++-dev",
                "libfreetype6-dev",
                "liblcms2-dev",
                "libwebp-dev",
                "libxext6",
                "libxrender1",
                "libxslt1-dev",
                "libxslt1.1",
                "libffi-dev",
                "ntp",
                "postfix",
                "python3-dev",
                "python-tk",
                "screen",
                "vim",
                "xfonts-75dpi",
                "xfonts-base",
                "zlib1g-dev",
                "apt-transport-https",
                "libsasl2-dev",
                "libldap2-dev",
                "libcups2-dev",
                "pv"
            ],
            "pkg": [
                "dnsmasq",
                "fontconfig",
                "git",
                "htop",
                "libcrypto++-dev",
                "libfreetype6-dev",
                "liblcms2-dev",
                "libwebp-dev",
                "libxext6",
                "libxrender1",
                "libxslt1-dev",
                "libxslt1.1",
                "libffi-dev",
                "ntp",
                "postfix",
                "python3-dev",
                "python-tk",
                "screen",
                "vim",
                "xfonts-75dpi",
                "xfonts-base",
                "zlib1g-dev",
                "apt-transport-https",
                "libsasl2-dev",
                "libldap2-dev",
                "libcups2-dev",
                "pv"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "upgrade": null
        }
    }
}

TASK [common : include_tasks] ******************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/debian_family.yml:38
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [common : include_tasks] ******************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/debian_family.yml:41
included: /tmp/.bench/bench/playbooks/roles/common/tasks/ubuntu.yml for localhost

TASK [common : install pillow prerequisites for Ubuntu < 14.04] ********************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/ubuntu.yml:3
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [common : install pillow prerequisites for Ubuntu >= 14.04] *******************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/ubuntu.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854 `" && echo ansible-tmp-1601880273.2500873-21838832300854="` echo /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/packaging/os/apt.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-657ft9avbb9/tmpqayl680x TO /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854/AnsiballZ_apt.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854/ /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1601880273.2500873-21838832300854/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "cache_update_time": 1601880263,
    "cache_updated": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": true,
            "force_apt_get": false,
            "install_recommends": null,
            "only_upgrade": false,
            "package": [
                "libjpeg8-dev",
                "libtiff5-dev",
                "tcl8.6-dev",
                "tk8.6-dev"
            ],
            "pkg": [
                "libjpeg8-dev",
                "libtiff5-dev",
                "tcl8.6-dev",
                "tk8.6-dev"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "upgrade": null
        }
    }
}

TASK [common : install pdf prerequisites for Ubuntu < 18.04] ***********************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/ubuntu.yml:25
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [common : install pdf prerequisites for Ubuntu >= 18.04] **********************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/ubuntu.yml:33
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873 `" && echo ansible-tmp-1601880273.9421425-236151953095873="` echo /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/packaging/os/apt.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-657ft9avbb9/tmptjtjk5_p TO /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873/AnsiballZ_apt.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873/ /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873/AnsiballZ_apt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1601880273.9421425-236151953095873/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "cache_update_time": 1601880263,
    "cache_updated": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": true,
            "force_apt_get": false,
            "install_recommends": null,
            "only_upgrade": false,
            "package": [
                "libssl1.1"
            ],
            "pkg": [
                "libssl1.1"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "upgrade": null
        }
    }
}

TASK [common : include_tasks] ******************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/common/tasks/main.yml:7
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [locale : Check current locale] ***********************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/locale/tasks/main.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594 `" && echo ansible-tmp-1601880274.644126-118192057576594="` echo /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-657ft9avbb9/tmp1j1exi27 TO /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594/ /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1601880274.644126-118192057576594/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "localectl",
    "delta": "0:00:00.012958",
    "end": "2020-10-05 08:44:34.859294",
    "invocation": {
        "module_args": {
            "_raw_params": "localectl",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-10-05 08:44:34.846336",
    "stderr": "\u001b[0;1;31mSystem has not been booted with systemd as init system (PID 1). Can't operate.\u001b[0m\n\u001b[0;1;31mFailed to create bus connection: Host is down\u001b[0m",
    "stderr_lines": [
        "\u001b[0;1;31mSystem has not been booted with systemd as init system (PID 1). Can't operate.\u001b[0m",
        "\u001b[0;1;31mFailed to create bus connection: Host is down\u001b[0m"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

Install script run at 06:44 on 2020-10-05
```

**Comment by shiraski** [comment]
Getting this error
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-67dho3rp/cryptography/

**Comment by daraul** [comment]
Any luck @MindLaborDev?

**Comment by web-dev-sam** [comment]
@daraul sadly not
