### ISSUE TITLE
Error while installing using install.py script

### ISSUE THREAD

**Issue by atishagrawal** [frappe/bench#905]
Ubuntu 16.04.6 (LTS) x64 and same on Ubuntu 18.04.3 (LTS) x64

```
frappe-user@erp:~$ sudo python3 install.py --production --user frappe-user --container
[sudo] password for frappe-user:
Logs are saved under /tmp/logs/easy-install__2020-01-18__13-29.log
Checking System Compatibility...
ubuntu 16 is compatible!
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
  Failed building wheel for cryptography
  Can't rollback cryptography, nothing uninstalled.
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-avzkhhz3/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-uz0m5j8y-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-avzkhhz3/cryptography/
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_prerequisites()
  File "install.py", line 132, in install_prerequisites
    'python3': "sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip"
  File "install.py", line 107, in run_os_command
    returncode = subprocess.check_call(command, shell=True, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip' returned non-zero exit status 1
frappe-user@erp:~$

```

**OS INFO**

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by starlays** [comment]
Another error on my side:

```
frappe-user@vm-erp:~$ sudo python3 install.py --production --user frappe-user
Logs are saved under /tmp/logs/easy-install__2020-01-19__21-32.log
Checking System Compatibility...
ubuntu 18 is compatible!
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Input MySQL and Frappe Administrator passwords:
Passwords saved at ~/passwords.txt
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Traceback (most recent call last):
  File "install.py", line 414, in <module>
    install_bench(args)
  File "install.py", line 230, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 351, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'), stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe-user']' returned non-zero exit status 2.
```

OS info:
```
frappe-user@vm-erp:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

Kernel info:
`Linux 4.15.0-74-generic x86_64`

**Comment by gavindsouza** [comment]
@starlays can you share the log file at `/tmp/logs/easy-install__2020-01-19__21-32.log`?

**Comment by gavindsouza** [comment]
@atishagrawal what error does running `sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip` in the command line give you?

**Comment by starlays** [comment]
> 
> 
> @starlays can you share the log file at `/tmp/logs/easy-install__2020-01-19__21-32.log`?

@gavindsouza  here it is: https://pastebin.com/raw/gApdUmyC

**Comment by atishagrawal** [comment]
> @atishagrawal what error does running `sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip` in the command line give you?

It doesn't give any error. 
```
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/dist-packages (45.1.0)
Requirement already up-to-date: cryptography in /usr/local/lib/python3.6/dist-packages (2.8)
Requirement already up-to-date: ansible==2.8.5 in /usr/local/lib/python3.6/dist-packages (2.8.5)
Requirement already up-to-date: pip in /usr/local/lib/python3.6/dist-packages (20.0.1)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from cryptography) (1.14.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography) (1.13.2)
Requirement already satisfied, skipping upgrade: jinja2 in /usr/local/lib/python3.6/dist-packages (from ansible==2.8.5) (2.10.3)
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python3.6/dist-packages (from ansible==2.8.5) (5.3)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography) (2.19)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->ansible==2.8.5) (1.1.1)

```

**Comment by atishagrawal** [comment]
> @starlays can you share the log file at `/tmp/logs/easy-install__2020-01-19__21-32.log`?

I am uploading the two log files which were generated while installing.

I guess, **EASY INSTALL** is not that easy.


[easy-install__2020-01-23__10-30.log](https://github.com/frappe/bench/files/4102611/easy-install__2020-01-23__10-30.log)
[easy-install__2020-01-23__10-36.log](https://github.com/frappe/bench/files/4102612/easy-install__2020-01-23__10-36.log)

**Comment by atishagrawal** [comment]
I am posting the output of the command 

`sudo python3 install.py --production --user frappe-user`

```
Checking System Compatibility...
ubuntu 18 is compatible!
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Input MySQL and Frappe Administrator passwords:
Passwords saved at ~/passwords.txt
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Traceback (most recent call last):
  File "install.py", line 414, in <module>
    install_bench(args)
  File "install.py", line 230, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 351, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'), stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe-user']' returned non-zero exit status 2.

```

**Comment by atishagrawal** [comment]
I even tried manual setup referring to https://github.com/frappe/bench/blob/master/docs/installation.md. But faced same issues.

Additional Information 

```
root@erp:~# python -V
Python 2.7.17
root@erp:~# node -v
v10.18.1
root@erp:~# redis-server -v
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3
root@erp:~# mariadb -V
mariadb  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
root@erp:~# yarn -v
1.21.1
root@erp:~# pip -V
pip 20.0.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@erp:~# wkhtmltopdf -V
wkhtmltopdf 0.12.4 (with patched qt)
root@erp:~# nginx -v
nginx version: nginx/1.14.0 (Ubuntu)
root@erp:~#
```

**Comment by atishagrawal** [comment]
Closing this issue after successful installtion.

https://github.com/frappe/bench/issues/838#issuecomment-578051805
