### ISSUE TITLE
ERPnext and Docker

### ISSUE THREAD

**Issue by adithep** [frappe/bench#96]
I am trying to build ERP next in docker with base image as Debian wheezy, this is the error that I got.

```
Adding debian mariadb repo
Installing packages for debian. This might take time...
Installing wkhtmltopdf
Adding frappe user
Installing frappe-bench
su: Authentication failure
(Ignored)
Already using interpreter /usr/bin/python
Cloning into 'frappe'...
Wrote ./assets/js/frappe-web.min.js - 90k
Wrote ./assets/js/print_format_v3.min.js - 18k
Wrote ./assets/css/frappe.css - 224k
Wrote ./assets/css/frappe-web.css - 163k
Wrote ./assets/js/editor.min.js - 27k
Wrote ./assets/js/frappe.min.js - 609k
Wrote ./assets/js/slickgrid.min.js - 102k
Wrote ./assets/js/canvasResize.min.js - 22k
installing frappe
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/dock/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/dock/bench-repo/bench/cli.py", line 106, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch)
  File "/home/dock/bench-repo/bench/utils.py", line 53, in init
    setup_backups(bench=path)
  File "/home/dock/bench-repo/bench/utils.py", line 120, in setup_backups
    logfile=os.path.join(get_bench_dir(bench=bench), 'logs', 'backup.log')))
  File "/home/dock/bench-repo/bench/utils.py", line 123, in add_to_crontab
    current_crontab = read_crontab()
  File "/home/dock/bench-repo/bench/utils.py", line 131, in read_crontab
    s = subprocess.Popen(["crontab", "-l"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
INFO[1096] The command [/bin/sh -c sudo wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh     && sudo bash /setup_frappe.sh --setup-production] returned a non-zero code: 1
```

**Comment by williamjmorenor** [comment]
Ca you share the docker file than you are using?

**Comment by adithep** [comment]
FROM debian:wheezy


RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends git wget openssl ca-certificates

RUN echo 'aa' && cat /etc/sudoers
ADD test.sh test.sh
USER dock
RUN sudo bash test.sh
RUN sudo wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh \
    && sudo bash /setup_frappe.sh --setup-production

**Comment by pdvyas** [comment]
Is crontab installed?

**Comment by adithep** [comment]
I am very sorry but I am not a pro at this. After installing cron I am getting this error

Installing for debian 7 amd64
In case you encounter an error, you can post on https://discuss.frappe.io

Adding debian mariadb repo
Installing packages for debian. This might take time...
Installing wkhtmltopdf
Adding frappe user
Installing frappe-bench
Setting up first site
su: Authentication failure
(Ignored)
Traceback (most recent call last):
  File "/home/dock/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.9.3', 'console_scripts', 'frappe')()
  File "/home/dock/frappe-bench/apps/frappe/frappe/cli.py", line 54, in main
    return run(fn, parsed_args)
  File "/home/dock/frappe-bench/apps/frappe/frappe/cli.py", line 82, in run
    out = globals().get(fn)(*args.get(fn), **args)
  File "/home/dock/frappe-bench/apps/frappe/frappe/cli.py", line 68, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/dock/frappe-bench/apps/frappe/frappe/cli.py", line 337, in install
    _install(db_name, root_login, root_password, source_sql, admin_password, force, site_config, reinstall, quiet, install_apps)
  File "/home/dock/frappe-bench/apps/frappe/frappe/cli.py", line 318, in _install
    admin_password = admin_password, verbose=verbose, force=force, site_config=site_config, reinstall=reinstall)
  File "/home/dock/frappe-bench/apps/frappe/frappe/installer.py", line 31, in install_db
    create_database_and_user(force, verbose)
  File "/home/dock/frappe-bench/apps/frappe/frappe/installer.py", line 48, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/home/dock/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 359, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/home/dock/frappe-bench/apps/frappe/frappe/database.py", line 79, in sql
    self.connect()
  File "/home/dock/frappe-bench/apps/frappe/frappe/database.py", line 49, in connect
    use_unicode=True, charset='utf8')
  File "/home/dock/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/dock/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/dock/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/dock/bench-repo/bench/cli.py", line 129, in new_site
    _new_site(site, mariadb_root_password=mariadb_root_password, admin_password=admin_password)
  File "/home/dock/bench-repo/bench/utils.py", line 86, in new_site
    ), cwd=os.path.join(bench, 'sites'))
  File "/home/dock/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/dock/frappe-bench/env/bin/frappe --install site1.local site1.local --root_password QMZIWVaJUJSMYqne --admin_password P914qYdi4IuM3h69' returned non-zero exit status 1
INFO[1192] The command [/bin/sh -c cd home/dock && wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh     && sudo bash setup_frappe.sh --setup-production] returned a non-zero code: 1

**Comment by toskes** [comment]
try to use phusion/baseimage:latest image

Its better to install all manually, because from script I get 
Installing frappe-bench
Setting up first site
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.10.2', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 54, in main
    return run(fn, parsed_args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 82, in run
    out = globals().get(fn)(*args.get(fn), **args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 68, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 337, in install
    _install(db_name, root_login, root_password, source_sql, admin_password, force, site_config, reinstall, quiet, install_apps)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 318, in _install
    admin_password = admin_password, verbose=verbose, force=force, site_config=site_config, reinstall=reinstall)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 31, in install_db
    create_database_and_user(force, verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 48, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 359, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 79, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 49, in connect
    use_unicode=True, charset='utf8')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 131, in new_site
    _new_site(site, mariadb_root_password=mariadb_root_password, admin_password=admin_password)
  File "/home/frappe/bench-repo/bench/utils.py", line 86, in new_site
    ), cwd=os.path.join(bench, 'sites'))
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/frappe --install site1.local site1.local --root_password qaPsDgtMQ4T2dkqK --admin_password 0B5KQDnHIJjg1dCq' returned non-zero exit status 1

It error raises because mysql havent started. (docker doesnt start them)
Before "bench init", try to start them manually
sudo service mysql start
sudo service redis-server start
sudo service memcached start

It will be good, if developers include this lines in script

**Comment by williamjmorenor** [comment]
It is better to start this services with the docker file

**Comment by pdvyas** [comment]
In case of deb based distros, they start automatically post install. Also, I haven't used docker but am thinking if officially maintaining a docker image with deps and bench cli installed would be a good idea. So, after setting up the container, you can start with `bench init`. Let us know.

**Comment by adithep** [comment]
For now I ran the sh script on Amazon ec2 instance, and everything has been working fine. I cant speak for everyone but for myself, lately I have been running all web service on docker container and am much happier for it, So I would very much appreciate if ERPNext will come in officially supported Docker image.

**Comment by williamjmorenor** [comment]
+1

There is many Odoo containers in the Docker Hub, so get a oficial Container for ERPNext can help to get more users of this great app

**Comment by rydersaint** [comment]
+1
erpnext on Docker Hub please that would be wonderful!

**Comment by pdvyas** [comment]
Great! Nice to see so much interest. Will work on it post v5 release. Let's keep this issue open.

**Comment by pfy** [comment]
Hi, we have a working docker build for erpnext, based on debian:wheezy
https://registry.hub.docker.com/u/davidgu/erpnext/

**Comment by pdvyas** [comment]
browsed through your dockerfile. Looks correct (based on commands are from the install script :)).
We can do an official docker image (based on a ansible playbook) after the released.

**Comment by williamjmorenor** [comment]
:+1: 

I will test this image with cockpit .... and can be good a image based in Centos, will work in it on weekend

**Comment by williamjmorenor** [comment]
The image is 901.3 MB size..... but works :)

![captura de pantalla de 2015-03-18 16 59 52](https://cloud.githubusercontent.com/assets/3522386/6721264/fd9e0f2e-cd90-11e4-8edd-a0de4f5cb4fd.png)

:+1:

**Comment by rydersaint** [comment]
Wow Pfy!
Your container is awesome!
I have linked it with a mariadb with UTFMB4 configured.
(Full character support for Japanese, Chinese and Korean).
This a great example of simple is best.
Works great thank you!

williamjmorenor currently using shipyard is cockpit better or just different all together started having a look last night however all the containers have failed thus far. 

pdvyas ansible playbook how would it work ? 
Would it run docker compose and then lunch the services ?
Being able to spin up 500 containers sounds like your about to have the Internet Service Provider version of ERPnext. The possibilities of this project are just endless.

I Really want to start working with version 5 on docker!
This would be really great. 

Thank you

Kind regards

**Comment by pdvyas** [comment]
Great!
I am not familiar with docker yet but I am aiming for a common solution to setup a production instance (setup_frappe.sh replacement) on a VM / making a container image / virtual machine image.

**Comment by williamjmorenor** [comment]
@rydersaint did you asing a port to your container? 

![captura de pantalla de 2015-03-20 08 36 52](https://cloud.githubusercontent.com/assets/3522386/6753580/abd74fbe-cedc-11e4-946a-bab463d00f1b.png)

This ERPNext docker image exposes the 80 port, so you need to define the port to use in your host machine, 

Cockpit is not just a docker admin tool, is a full server admin tool part of the Project Atomic Host ( http://www.projectatomic.io/ ) but currently is missing two docker features:

Linking Containers: https://github.com/cockpit-project/cockpit/issues/297  Example: oficial Wordpress image need to be linked to a database image, currently this is not posible inside Cokpit yet

Volumes Admin: https://github.com/cockpit-project/cockpit/issues/1451

With this two features in place Cockpit will be just amaizing 

The Project Atomic Host is the Docker aproach to Docker admin in RHEL/CentOS/Fedora and really good

**Comment by rydersaint** [comment]
pdvyas I think docker setup_frappe.sh replacement is a great idea. 
If you follow Pfy example for version 5.
However have a frappe docker registry.
This would make it very easy for you to commit full systems at a time.
Commit a docker image for each of your releases. (5.0, 5.1, 5.2 etc....)
Test, debug and commit and then users would have a working ERPnext every time.

**Comment by rydersaint** [comment]
williamjmorenor Thank you for explaining it all I will check into it further on my Dev machine very exciting

**Comment by mhbu50** [comment]
+1

**Comment by thenewguy** [comment]
Did any sort of official docker support ever come about?

**Comment by dmitry-saritasa** [comment]
Would be nice to use docker-compose as well, so bench generates docker-compose which we then simply start. Docker is so nice to help devs start development faster. I just found erpnext and decided to try and immediately locked down by having no local redis server, but I have it up & running as docker container. The same is for DBs and other services I use during development

**Comment by codingCoffee** [comment]
please use https://github.com/frappe/frappe_docker

**Comment by techquila** [comment]
@codingCoffee I'm finding the process hangs after running the ./dbench init command.  It appears to stall when cloning frappe_io repo.  i've tried this a couple times now with same result.

perhaps the install instructions are not as clear as the seem?  Any chance you can clarify the process step by step in order to get this working please?  It'd be great to not have to reinvent the wheel, but i've found both docker erpnext candidates to be either non-functional, as is the case with this example, or inadequate as is the case with the other one I tried.

many thanks.

**Comment by codingCoffee** [comment]
@techquila open the issue in https://github.com/frappe/frappe_docker repository
