### ISSUE TITLE
Command new-site not working. 

### ISSUE THREAD

**Issue by Adamhingoro** [frappe/bench#963]
Bug Report. 

`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.14.0 (/home/ubuntu/.local/lib/python3.6/site-packages), Requirement.parse('six==1.12.0'), {'bench'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six==1.12.0' distribution was not found and is required by bench`

To reproduce. 
`just running bench command after bench init. 
`
I am using AWS EC2 Ubuntu 18. 

I was getting these errors too but I used PIP to download the mentioned versions. and these errors vanished but then bench new-site not working. 
```
ERROR: frappe-bench 5.0.0 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
ERROR: frappe-bench 5.0.0 has requirement semantic-version==2.8.2, but you'll have semantic-version 2.8.4 which is incompatible.
ERROR: frappe-bench 5.0.0 has requirement six==1.12.0, but you'll have six 1.14.0 which is incompatible.
ERROR: bench 4.1.0 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
ERROR: bench 4.1.0 has requirement semantic-version==2.8.2, but you'll have semantic-version 2.8.4 which is incompatible.
ERROR: bench 4.1.0 has requirement six==1.12.0, but you'll have six 1.14.0 which is incompatible.
```

**Comment by gavindsouza** [comment]
It seems like the editable install is not removed from the system. 

To check if the previous bench has been uninstalled correctly: 

 - Try deleting the `bench-repo` or `.bench` folders in your home directory (or where ever you had it cloned) 
 - Delete the corresponding egg-link file from under your Python `site-packages` folder.
 - Perhaps, also remove the bench entry point file by running rm $(which bench) 
 - Finally, run `pip install --no-cache-dir --force-reinstall frappe-bench`


Hope this helps.
