### ISSUE TITLE
bench clear-cache fails with "TypeError: 'Nonetype' object is not iterable

### ISSUE THREAD

**Issue by cybertoast** [frappe/bench#971]
**Steps to reproduce the behavior: 
1. Set up a new app and a new site
2. Change a configuration (say developer_mode=1 in site-config.json)
3. Run `bench clear-cache`
4. See error (see backtrace below)

**Expected behavior** :chart_with_upwards_trend:
I would expect a prompt for the `--site` option with a list of sites that I can supply to `bench clear-cache`. The correct command is `bench --site mysite.local clear-cache`, which should be suggested by the system.

**OS (please complete the following information):** :cyclone:
- [x] Linux: Ubuntu 19.10
- [x] macOS: 10.15.3

**Version Information**
- erpnext 12.x.x-develop
- frappe 12.x.x-develop

**Additional context** :page_facing_up:
```
$ bench clear-cache 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/sundar/Personal/Projects/MOTF/frappe-bench/apps/frappe/frappe/commands/utils.py", line 46, in clear_cache
    for site in context.sites:
TypeError: 'NoneType' object is not iterable
```

**Possible Solution** :bookmark_tabs:

**Comment by martinhbramwell** [comment]
I am finding this error too and it applies to ```bench migrate``` and ```bench mariadb``` as well (although the error messages are different)

My ```currentsite.txt``` file was empty, so I tried specifying one of my sites there.  It made no difference.

**Comment by gavindsouza** [comment]
@martinhbramwell Can't replicate this issue in your case
![Screenshot 2020-04-17 at 6 42 11 PM](https://user-images.githubusercontent.com/36654812/79572791-2b3f8e00-80db-11ea-9fe0-8f19acb217d5.png)


@cybertoast From the way I see it, deprecation of `bench use` or a refactor of `frappe.commands` will only fix this issue (at the root). The fix for this should either follow in the methods `frappe.init` or `frappe.connect`
