### ISSUE TITLE
[Develop] Error while creating new app

### ISSUE THREAD

**Issue by Alchez** [frappe/bench#977]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue?

- I've seen this happen everytime I've run `bench new-app`.

 - [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

- I was able to do a temporary workaround by removing the logic for the creation of the `hooks.py` file (and manually creating that file), but I didn't dig deeper as to why it could be happening. 

**Describe the bug** :chart_with_downwards_trend:

Everytime I run `bench new-app <app_name>`, I get the following error after entering all the prompted details:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rohan/jhb/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/rohan/jhb/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rohan/jhb/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rohan/jhb/apps/frappe/frappe/commands/utils.py", line 574, in make_app
    make_boilerplate(destination, app_name)
  File "/home/rohan/jhb/apps/frappe/frappe/utils/boilerplate.py", line 91, in make_boilerplate
    f.write(frappe.as_unicode(hooks_template.format(**hooks)))
KeyError: '"doctype"'
```

**To Reproduce** :page_with_curl:

1. Run `bench new-app test_new_app`
2. Enter all the app details
3. See error

**Expected behavior** :chart_with_upwards_trend:

The new app gets created without breaking at any stage.

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [x] Linux: `Ubuntu 20.04 LTS`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder

- Bench Branch: `develop` _(Only master is supported)_
- Frappe Version: 12.3.0
- ERPNext Version: 12.5.2

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by gavindsouza** [comment]
The `new-app` command actually is executed via Frappe. Although, I tested creating an app with Frappe `develop` and the specified version; both of which executed successfully.

![Screenshot 2020-04-23 at 12 20 33 PM](https://user-images.githubusercontent.com/36654812/80068383-26585f80-855d-11ea-84f2-86bdefb357ed.png)
