### ISSUE TITLE
bench update fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/bench#989]
I have installed bench using `pip install frappe-bench`.
`bench update` is asking for root password and is eventually failing with the below logs. `bench restart` also results in the same logs.

I tried following
- reinstalling bench, supervisor but to no avail.
- recreated env and it did not help.
- `bench setup production` to generate new configurations.
- created a new bench and the result is the same.
 
```
$ find . -name "*.pyc" -delete
Updating Python libraries...
$ /home/mujeerhashmi/erpnext/test-bench/env/bin/pip install -q -U pip
INFO:bench.app:installing frappe
$ /home/mujeerhashmi/erpnext/test-bench/env/bin/pip install -q -U -e /home/mujeerhashmi/erpnext/test-bench/apps/frappe 
[sudo] password for mujeerhashmi: 
Traceback (most recent call last):
  File "/home/mujeerhashmi/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/cli.py", line 41, in cli
    bench_command()
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/commands/update.py", line 25, in update
    update(pull=pull, patch=patch, build=build, requirements=requirements, restart_supervisor=restart_supervisor, restart_systemd=restart_systemd, backup=not no_backup, force=force, reset=reset)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/utils.py", line 199, in update
    update_requirements(bench_path=bench_path)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/utils.py", line 566, in update_requirements
    install_app(app, bench_path=bench_path, skip_assets=True)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/app.py", line 190, in install_app
    restart_supervisor_processes(bench_path=bench_path)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/utils.py", line 519, in restart_supervisor_processes
    supervisor_status = subprocess.check_output(['sudo', 'supervisorctl', 'status'], cwd=bench_path)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'supervisorctl', 'status']' returned non-zero exit status 3.
```

**Comment by gavindsouza** [comment]
@mujeerhashmi is frappe sudoers set for your user?

**Comment by mujeerhashmi** [comment]
hi @gavindsouza 
The user is set for sudoers. I did not get what you mean by `frappe sudoers` though.

**Comment by gavindsouza** [comment]
>  I did not get what you mean by frappe sudoers though.

is `bench setup sudoers` run for your user?

**Comment by mujeerhashmi** [comment]
I don't remeber doing it. The user with which I run the bench commands is a sudo user.

**Comment by mujeerhashmi** [comment]
@gavindsouza 
I tried `bench setup sudoers`. I get the following error on `bench restart`
```
>>> /etc/sudoers.d/frappe: syntax error near line 18 <<<
sudo: parse error in /etc/sudoers.d/frappe near line 18
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
Traceback (most recent call last):
  File "/home/mujeerhashmi/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/cli.py", line 41, in cli
    bench_command()
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/commands/utils.py", line 26, in restart
    restart_supervisor_processes(bench_path='.', web_workers=web)
  File "/home/mujeerhashmi/.local/lib/python3.8/site-packages/bench/utils.py", line 519, in restart_supervisor_processes
    supervisor_status = subprocess.check_output(['sudo', 'supervisorctl', 'status'], cwd=bench_path)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'supervisorctl', 'status']' returned non-zero exit status 1.
```
I figured out that line 18 has `None` which should be in all caps `NONE`. But even after that the error remains.

**Comment by gavindsouza** [comment]
Oh, maybe sudoers was set when bench wasn't in PATH; replace the None with the absolute path of your bench entry point file, which you can find by `which bench`

**Comment by mujeerhashmi** [comment]
`which bench` gives me `/home/mujeerhashmi/.local/bin/bench`

I have added this to `/etc/sudoers.d/frappe` after which this file look like this

```
mujeerhashmi ALL = (root) /usr/sbin/service
mujeerhashmi ALL = (root) NOPASSWD: /usr/sbin/service nginx *
mujeerhashmi ALL = (root) NOPASSWD: /usr/sbin/service supervisord *


mujeerhashmi ALL = (root) /bin/systemctl
mujeerhashmi ALL = (root) NOPASSWD: /bin/systemctl * nginx
mujeerhashmi ALL = (root) NOPASSWD: /bin/systemctl * supervisord


mujeerhashmi ALL = (root) NOPASSWD: /usr/bin/supervisorctl


mujeerhashmi ALL = (root) NOPASSWD: /usr/sbin/nginx

mujeerhashmi ALL = (root) NOPASSWD: /opt/certbot-auto
mujeerhashmi ALL = (root) NOPASSWD: /home/mujeerhashmi/.local/bin/bench
Defaults:mujeerhashmi !requiretty
```
The problem continues to persist.

**Comment by mujeerhashmi** [comment]
With latest version of bench i.e, `v5.1`

`bench restart` resulted in the below error
```
\$ supervisorctl restart frappe:
error: <class 'PermissionError'>, [Errno 13] Permission denied: file: /usr/lib/python3/dist-packages/supervisor/xmlrpc.py line: 560
```

I added below line to  `/etc/supervisor/supervisord.conf` under `[unix_http_server]` directive

```
chown=mujeerhashmi:root         ; (username:group)
```
and voila! the bench restart properly now. I am not sure if this is correct way to fix it  @gavindsouza.

**Comment by gavindsouza** [comment]
Closing due to inactivity + Issue is about 13 minor releases in the past.

**Comment by sentient-russ** [comment]
I now have this issue in v14 with a fresh install.
The supervisor service would not start and the supervisord.conf was missing.  I created it in the /etc/supervisor  as follows.
Before doing this supervisor status was activating but not started.
Now supervisor does start; however, "ERROR: Command 'sudo supervisorctl status' returned non-zero exit status 2" exists when bench restart.

**Comment by makwinraj** [comment]
did u found any solution for 

> I now have this issue in v14 with a fresh install. The supervisor service would not start and the supervisord.conf was missing. I created it in the /etc/supervisor as follows. Before doing this supervisor status was activating but not started. Now supervisor does start; however, "ERROR: Command 'sudo supervisorctl status' returned non-zero exit status 2" exists when bench restart.

did u found any solution for this error,if you know pls let me know.

**Comment by sentient-russ** [comment]
Yes. 

sudo apt-get --purge remove supervisor
sudo apt-get install supervisor
supervisor had been installed via pip which I believe was the issue on Ubuntu 22.04.  This allowed bench start to run error free.

**Comment by makwinraj** [comment]
> Yes.
> 
> sudo apt-get --purge remove supervisor sudo apt-get install supervisor supervisor had been installed via pip which I believe was the issue on Ubuntu 22.04. This allowed bench start to run error free.

thank you for the help :)
