### ISSUE TITLE
Setup Frappe not Efficient

### ISSUE THREAD

**Issue by codewaziri** [frappe/bench#99]
setup_frappe.sh keeps repeating the install process even if repo and packages already exist and is generally slow not sure why, see the steps below:

Adding ubuntu mariadb repo (should be skipped if already exists)
Installing packages for Ubuntu. This might take time...(should be skipped if already exists)
Installing wkhtmltopdf (should be skipped since it is optional or y / N question prompted with default set as No)

Additional messages on each of the steps success or failure would be great as well.

Currently, Unpacking wkhtmltox (0.12.2.1) ... fails but messages come from dpkg-deb hence install didn't succeed even though wkhtmltopdf is meant to be optional.

**Comment by pdvyas** [comment]
Agree that the script needs better error handling

- We can detect mariadb config and not add it again
- If you ask yum, apt-get to install already installed packages, they skip it automatically. I would prefer apt/yum to handle this
- We can add `--skip-wkhtmltopdf` option to script. But curious. What is the error message?

Any suggestions on additional messages that should we add?

**Comment by codewaziri** [comment]
What is the error message?

The error message on ubuntu-14.04 is shown below:

Unpacking wkhtmltox (0.12.2.1) ...
dpkg-deb (subprocess): cannot copy archive member from 'wkhtmltox-0.12.2.1_linux-trusty-amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive wkhtmltox-0.12.2.1_linux-trusty-amd64.deb (--install):
 cannot copy extracted data for './usr/local/lib/libwkhtmltox.so.0.12.2' to '/usr/local/lib/libwkhtmltox.so.0.12.2.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 wkhtmltox-0.12.2.1_linux-trusty-amd64.deb

Any suggestions on additional messages that should we add? 

Manual Install shows a number of pre-requisites are to be installed these should be mirrored in the setup_frappe script in similar order for instance:

Adding missing pre-requisites to Ubuntu repo...
...mariadb was added to repo 

Installing packages for Ubuntu. This might take time...
...Python 2.7 is already latest
...MariaDB successfully installed etc.

Do you want to install wkhtmltopdf (y / N): 
Installing wkhtmltopdf ...

or use --skip-wkhtmltopdf as you'd suggested in script run to jump user prompt above.

**Comment by codewaziri** [comment]
After manual install of wkhtmltox-0.12.2.1_linux-trusty-amd64.deb I repeat the process only for it to fail again at this point below:

Adding frappe user
Installing frappe-bench
Setting up first site
Traceback (most recent call last):
  File "/home/mwai/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/mwai/frappe-bench/apps/frappe/frappe/cli.py", line 53, in main
    return run(fn, parsed_args)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/cli.py", line 81, in run
    out = globals().get(fn)(*args.get(fn), **args)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/cli.py", line 336, in install
    _install(db_name, root_login, root_password, source_sql, admin_password, force, site_config, reinstall, quiet, install_apps)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/cli.py", line 317, in _install
    admin_password = admin_password, verbose=verbose, force=force, site_config=site_config, reinstall=reinstall)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/installer.py", line 31, in install_db
    create_database_and_user(force, verbose)
  File "/home/mwai/frappe-bench/apps/frappe/frappe/installer.py", line 48, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/home/mwai/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 359, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/home/mwai/frappe-bench/apps/frappe/frappe/database.py", line 79, in sql
    self.connect()
  File "/home/mwai/frappe-bench/apps/frappe/frappe/database.py", line 49, in connect
    use_unicode=True, charset='utf8')
  File "/home/mwai/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/mwai/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/mwai/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/mwai/bench-repo/bench/cli.py", line 131, in new_site
    _new_site(site, mariadb_root_password=mariadb_root_password, admin_password=admin_password)
  File "/home/mwai/bench-repo/bench/utils.py", line 88, in new_site
    ), cwd=os.path.join(bench, 'sites'))
  File "/home/mwai/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/mwai/frappe-bench/env/bin/frappe site1.local --install 1bd3e0294d --root_password J6V3jNqfyF3wl87Y --admin_password xUegGQU9JVg6FkMb' returned non-zero exit status 1

**Comment by pdvyas** [comment]
Yes, the previous run would have already set a mysql password.
Can you try on a clean install?
I tried on an Ubuntu 12.04 and 14.04 this morning and it worked. Could be a temp problem with the wkhtmltopdf packages on sf.

**Comment by codewaziri** [comment]
I just decided to clone the bench repo instead and do a pip install so I have it working now.

**Comment by yashodhank** [comment]
### NOT FOR PRODUCTION SYSTEM
** Instead of clean installation, following commands worked for me to get ERPNext re-installed on Development server **
** Following command permantly distroy Nginx, Supervisor, MySQL Database, Configuration etc.

To Perform Clean up on Ubuntu/Debian use following commands, Then execute bench to re-install ERPNext

```
# userdel -f -r frappe
# apt-get purge mysql* maria* -y
# apt-get purge nginx supervisor -y
# rm /var/lib/mysql -fr
# rm /etc/mysql -fr
# rm -fr /etc/supervisor
# rm -fr /var/log/supervisor
```
